import { PlannerTemplateId, DayOfWeek } from '../../types/plannerAndCertificates';

export interface PlannerTemplateConfig {
  id: PlannerTemplateId;
  name: string;
  nameFr: string;
  nameAr: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  accentBg: string;
  cellBorderColor: string;
  headerBg: string;
  headerTextColor: string;
  dayHeaderBg: string;
  dayHeaderTextColor: string;
  fontFamily: string;
  rounded: string;
  decorativeBadgeEmoji: string;
  styleVariant: 'academic' | 'pastel' | 'kawaii' | 'minimal' | 'playful' | 'monochrome' | 'elegant' | 'teacher';
}

export const PLANNER_TEMPLATES: Record<PlannerTemplateId, PlannerTemplateConfig> = {
  classic_school: {
    id: 'classic_school',
    name: 'Classic Academic',
    nameFr: 'Classique Scolaire',
    nameAr: 'المدرسي الأكاديمي الكلاسيكي',
    description: 'Structure équilibrée, lisibilité optimale et clarté des matières pour l’école.',
    primaryColor: '#1E3A8A',
    secondaryColor: '#3B82F6',
    accentBg: '#EFF6FF',
    cellBorderColor: '#BFDBFE',
    headerBg: '#1E3A8A',
    headerTextColor: '#FFFFFF',
    dayHeaderBg: '#DBEAFE',
    dayHeaderTextColor: '#1E40AF',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-lg',
    decorativeBadgeEmoji: '🏛️',
    styleVariant: 'academic',
  },
  pastel_school: {
    id: 'pastel_school',
    name: 'Pastel School',
    nameFr: 'Pastel Douceur',
    nameAr: 'المدرسي الباستيل الهادئ',
    description: 'Nuances pastel douces, cellules arrondies et présentation soignée pour les élèves.',
    primaryColor: '#7C3AED',
    secondaryColor: '#A78BFA',
    accentBg: '#FAF5FF',
    cellBorderColor: '#E9D5FF',
    headerBg: '#EDE9FE',
    headerTextColor: '#5B21B6',
    dayHeaderBg: '#F3E8FF',
    dayHeaderTextColor: '#6D28D9',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-xl',
    decorativeBadgeEmoji: '🌸',
    styleVariant: 'pastel',
  },
  kawaii_school: {
    id: 'kawaii_school',
    name: 'Kawaii School',
    nameFr: 'Kawaii & Mignon',
    nameAr: 'الكواي اللطيف المبهج',
    description: 'Illustrations originales, pastels fruités et stickers mignons pour les plus jeunes.',
    primaryColor: '#E11D48',
    secondaryColor: '#FB7185',
    accentBg: '#FFF1F2',
    cellBorderColor: '#FECDD3',
    headerBg: '#FFE4E6',
    headerTextColor: '#9F1239',
    dayHeaderBg: '#FFF1F2',
    dayHeaderTextColor: '#BE123C',
    fontFamily: 'Comic Neue, cursive, sans-serif',
    rounded: 'rounded-2xl',
    decorativeBadgeEmoji: '🐰',
    styleVariant: 'kawaii',
  },
  modern_minimal: {
    id: 'modern_minimal',
    name: 'Modern Minimal',
    nameFr: 'Minimaliste Épuré',
    nameAr: 'العصري الأنيق البسيط',
    description: 'Lignes épurées, contraste net et espace d’écriture généreux pour collège & lycée.',
    primaryColor: '#0F172A',
    secondaryColor: '#475569',
    accentBg: '#F8FAFC',
    cellBorderColor: '#E2E8F0',
    headerBg: '#F1F5F9',
    headerTextColor: '#0F172A',
    dayHeaderBg: '#F8FAFC',
    dayHeaderTextColor: '#334155',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-none',
    decorativeBadgeEmoji: '📐',
    styleVariant: 'minimal',
  },
  colorful_kids: {
    id: 'colorful_kids',
    name: 'Colorful Kids',
    nameFr: 'Primaire Coloré',
    nameAr: 'ألوان الابتدائي الحيوية',
    description: 'Palette vive, ludique et stimulante spécialement adaptée aux classes primaires.',
    primaryColor: '#D97706',
    secondaryColor: '#F59E0B',
    accentBg: '#FEF3C7',
    cellBorderColor: '#FDE68A',
    headerBg: '#F59E0B',
    headerTextColor: '#FFFFFF',
    dayHeaderBg: '#FEF9C3',
    dayHeaderTextColor: '#92400E',
    fontFamily: 'Patrick Hand, cursive, sans-serif',
    rounded: 'rounded-xl',
    decorativeBadgeEmoji: '🎨',
    styleVariant: 'playful',
  },
  bw_printable: {
    id: 'bw_printable',
    name: 'Black & White',
    nameFr: 'Éco Noir & Blanc',
    nameAr: 'أبيض وأسود اقتصادي',
    description: 'Contraste pur sans aplats d’encre, parfait pour photocopies et impressions économiques.',
    primaryColor: '#000000',
    secondaryColor: '#4B5563',
    accentBg: '#FFFFFF',
    cellBorderColor: '#9CA3AF',
    headerBg: '#FFFFFF',
    headerTextColor: '#000000',
    dayHeaderBg: '#F3F4F6',
    dayHeaderTextColor: '#111827',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-md',
    decorativeBadgeEmoji: '🖨️',
    styleVariant: 'monochrome',
  },
  premium_student: {
    id: 'premium_student',
    name: 'Student Stationery',
    nameFr: 'Papeterie Étudiante',
    nameAr: 'قرطاسية الطالب المميزة',
    description: 'Style carnet de papeterie chic avec teintes sauge, doré et typographie raffinée.',
    primaryColor: '#065F46',
    secondaryColor: '#10B981',
    accentBg: '#ECFDF5',
    cellBorderColor: '#A7F3D0',
    headerBg: '#D1FAE5',
    headerTextColor: '#064E3B',
    dayHeaderBg: '#ECFDF5',
    dayHeaderTextColor: '#047857',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-xl',
    decorativeBadgeEmoji: '🌿',
    styleVariant: 'elegant',
  },
  teacher_planner: {
    id: 'teacher_planner',
    name: 'Teacher Master Plan',
    nameFr: 'Organiseur Enseignant',
    nameAr: 'منظم الأستاذ والمعلم',
    description: 'Disposition complète avec colonnes de matières, salles de classe et notes de cours.',
    primaryColor: '#1E293B',
    secondaryColor: '#0284C7',
    accentBg: '#F0F9FF',
    cellBorderColor: '#BAE6FD',
    headerBg: '#0369A1',
    headerTextColor: '#FFFFFF',
    dayHeaderBg: '#E0F2FE',
    dayHeaderTextColor: '#075985',
    fontFamily: 'Outfit, sans-serif',
    rounded: 'rounded-lg',
    decorativeBadgeEmoji: '🎓',
    styleVariant: 'teacher',
  },
};

export const DEFAULT_SCHOOL_SUBJECTS = [
  { id: 'maths', name: 'Mathématiques', nameAr: 'رياضيات', color: '#DBEAFE', textColor: '#1E40AF', icon: '📐' },
  { id: 'francais', name: 'Français', nameAr: 'فرنسية', color: '#FCE7F3', textColor: '#9D174D', icon: '📖' },
  { id: 'arabe', name: 'Arabe', nameAr: 'لغة عربية', color: '#DCFCE7', textColor: '#166534', icon: '🖋️' },
  { id: 'anglais', name: 'Anglais', nameAr: 'إنجليزية', color: '#FEF3C7', textColor: '#92400E', icon: '🌍' },
  { id: 'sciences', name: 'Sciences / SVT', nameAr: 'علوم طبيعية', color: '#CCFBF1', textColor: '#115E59', icon: '🔬' },
  { id: 'histoire_geo', name: 'Histoire - Géo', nameAr: 'تاريخ وجغرافيا', color: '#FFEDD5', textColor: '#9A3412', icon: '🗺️' },
  { id: 'sport', name: 'Sport / EPS', nameAr: 'تربية بدنية', color: '#EDE9FE', textColor: '#5B21B6', icon: '⚽' },
  { id: 'arts', name: 'Arts Plastiques', nameAr: 'تربية تشكيلية', color: '#FEE2E2', textColor: '#991B1B', icon: '🎨' },
  { id: 'musique', name: 'Musique', nameAr: 'تربية موسيقية', color: '#E0E7FF', textColor: '#3730A3', icon: '🎵' },
  { id: 'informatique', name: 'Informatique', nameAr: 'إعلام آلي', color: '#CFFAFE', textColor: '#155E75', icon: '💻' },
  { id: 'islamique', name: 'Éduc. Islamique', nameAr: 'تربية إسلامية', color: '#D1FAE5', textColor: '#065F46', icon: '🕌' },
];

export const ALL_DAYS: { id: DayOfWeek; labelFr: string; labelShortFr: string; labelAr: string; labelShortAr: string }[] = [
  { id: 'mon', labelFr: 'Lundi', labelShortFr: 'Lun', labelAr: 'الإثنين', labelShortAr: 'اثن' },
  { id: 'tue', labelFr: 'Mardi', labelShortFr: 'Mar', labelAr: 'الثلاثاء', labelShortAr: 'ثلا' },
  { id: 'wed', labelFr: 'Mercredi', labelShortFr: 'Mer', labelAr: 'الأربعاء', labelShortAr: 'أرب' },
  { id: 'thu', labelFr: 'Jeudi', labelShortFr: 'Jeu', labelAr: 'الخميس', labelShortAr: 'خمي' },
  { id: 'fri', labelFr: 'Vendredi', labelShortFr: 'Ven', labelAr: 'الجمعة', labelShortAr: 'جمع' },
  { id: 'sat', labelFr: 'Samedi', labelShortFr: 'Sam', labelAr: 'السبت', labelShortAr: 'سبت' },
  { id: 'sun', labelFr: 'Dimanche', labelShortFr: 'Dim', labelAr: 'الأحد', labelShortAr: 'أحد' },
];
