import { StoryTemplate, BookPageCount, StoryPageTemplate } from './types';

export const STORY_TEMPLATES: StoryTemplate[] = [
  // 1. LA FORÊT MAGIQUE
  {
    id: 'magical_forest',
    titleFr: 'La Forêt Enchantée',
    titleAr: 'الغابة السحرية العجيبة',
    titleEn: 'The Enchanted Forest',
    subtitleFr: 'Une aventure magique au cœur des arbres scintillants',
    subtitleAr: 'مغامرة سحرية رائعة بين الأشجار المضيئة',
    subtitleEn: 'A magical journey into the heart of glowing trees',
    descriptionFr: 'Un matin paisible, {{childName}} découvre un sentier doré qui mène à une forêt féerique peuplée d’animaux bienveillants et d’arbres lumineux.',
    descriptionAr: 'في صباح مشرق، تكتشف {{childName}} ممراً ذهبياً سرياً يقود إلى غابة ساحرة تسكنها حيوانات لطيفة وأشجار متلألئة.',
    descriptionEn: 'On a sunny morning, {{childName}} discovers a hidden golden path leading to an enchanted woodland full of kind animals and glowing trees.',
    badgeFr: 'Nature & Magie',
    badgeAr: 'طبيعة وسحر',
    badgeEn: 'Nature & Magic',
    themes: ['Amitié', 'Bienveillance', 'Curiosité', 'Nature'],
    ageMin: 2,
    ageMax: 8,
    colorScheme: {
      primary: '#059669',
      primaryLight: '#d1fae5',
      primaryDark: '#064e3b',
      accent: '#f59e0b',
      badgeBg: '#ecfdf5',
      badgeText: '#047857',
      coverGradient: 'from-emerald-600 via-teal-700 to-emerald-900',
    },
    coverIllustrationId: 'forest_cover',
    supportedPageCounts: [8, 10, 12],
    pagesByCount: {
      8: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'forest_cover',
          textFr: '{{childName}} et la Forêt Enchantée',
          textAr: '{{childName}} والغابة السحرية العجيبة',
          textEn: '{{childName}} and the Enchanted Forest',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'forest_dedication',
          textFr: 'Ce livre a été écrit tout spécialement pour {{childName}}, {{childAge}} ans. Que chaque page t’apporte du bonheur, du courage et de la magie dans ton cœur.',
          textAr: 'كُتب هذا الكتاب بكل حب وفخر لأجل {{childName}}، ذات {{childAge}} سنوات. نتمنى لك رحلة مليئة بالأحلام السعيدة والبهجة الدائمة.',
          textEn: 'This book was created with love especially for {{childName}}, {{childAge}} years old. May each page bring you joy, wonder and bravery.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_clearing',
          textFr: 'Il était une fois {{childName}}, {{notre_cher_chere}} petit{{accord_e}} explorat{{accord_ne}}rice au cœur curieux. Ce matin-là, un petit papillon scintillant voletait devant sa fenêtre, l’invitant à le suivre dans les grands bois.',
          textAr: 'في يوم مشرق وجميل، كانت {{childName}}، {{batal}} ذات الروح الطيبة، تراقب فراشة براقة ترفرف أمام نافذتها وتدعوها للعب في الحديقة الواسعة.',
          textEn: 'Once upon a time, {{childName}}, our bright and curious explorer, noticed a shimmering butterfly fluttering outside, gently guiding the way into the woods.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_animal_meet',
          textFr: 'Au détour d’un chêne centenaire, {{childName}} fit la rencontre de Barnabé, le {{favoriteAnimal}}. Ses petites oreilles frémissaient. « Bonjour ! J’ai perdu ma clé d’étoile pour allumer les fleurs de la nuit », murmura l’animal.',
          textAr: 'وهناك، بين أشجار البلوط العالية، التقت {{childName}} بـ{{favoriteAnimal}}. همس بحياء: «مرحباً يا صديقتي! لقد أضعت مفتاح النجمة الذي يضيء أزهار الغابة ليلاً».',
          textEn: 'Behind an ancient oak tree, {{childName}} met Barnaby, the friendly {{favoriteAnimal}}. "Hello!" whispered the animal. "I lost my little starlight key that helps the night blossoms shine."',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_glowing_stream',
          textFr: '« Ne t’en fais pas, je vais t’aider ! », répondit {{childName}} avec un doux sourire. Guidé{{accord_e}} par son intuition et sa patience, {{il_elle}} chercha près de la rivière aux reflets argentés.',
          textAr: 'ابتسمت {{childName}} بكل دفء وقالت: «لا تقلق، سأساعدك بكل سرور!»، وبكل صبر وذكاء، بدأت تبحث قرب النهر الرقراق ذي المياه النقية اللامعة.',
          textEn: '"Do not worry, I will help you!" replied {{childName}} with a warm smile. Guided by kindness and curiosity, {{he_she}} searched near the crystal stream.',
        },
        {
          pageNumber: 6,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'forest_magic_tree',
          textFr: 'Soudain, sous une fougère illuminée par les lucioles, la petite clé étincelait ! Dès que Barnabé et {{childName}} la posèrent sur le grand Arbre des Songes, toute la forêt s’illumina de mille couleurs joyeuses.',
          textAr: 'وفجأة، تحت ورقة سرخس مخضرة، لمع المفتاح الذهبي! وما إن وضعته {{childName}} على شجرة الأحلام، حتى أضاءت الغابة بأكملها بأنوار خلابة ملأت القلوب بهجة.',
          textEn: 'Suddenly, nestled beneath a glowing fern, the golden key sparkled! As soon as {{childName}} placed it upon the Dream Tree, the entire forest burst into radiant glowing colors.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_celebration',
          textFr: 'Tous les animaux de la forêt vinrent remercier {{childName}} en chantant une douce mélodie. « Tu as prouvé qu’un grand cœur et un geste d’amitié peuvent illuminer le monde entier », dit le vieux hibou sage.',
          textAr: 'اجتمعت كل حيوانات الغابة لتشكر {{childName}} بأغنية رقيقة من وحي الصداقة. قال البوم الحكيم: «لقد أثبتّ اليوم أن العطف والمحبة ينيران أبهى الدروب».',
          textEn: 'All forest friends gathered to celebrate {{childName}} with a lovely song. "You have shown that a kind heart and a gentle hand can light up the entire world," said the wise owl.',
        },
        {
          pageNumber: 8,
          layout: 'back_cover',
          sceneIllustrationId: 'forest_back',
          textFr: 'Une histoire personnalisée pour {{childName}}. Que tes rêves soient toujours aussi doux et scintillants que la Forêt Enchantée. Fait avec amour pour toi.',
          textAr: 'قصة مخصصة كُتبت خصيصاً لأجل {{childName}}. لتكن أحلامك دوماً وضاءة وبديعة كسحر الغابة. صُنعت بحب واعتزاز.',
          textEn: 'A personalized bedtime tale for {{childName}}. May your dreams always be as soft, sweet and sparkling as the Enchanted Forest.',
        },
      ],
      10: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'forest_cover',
          textFr: '{{childName}} et la Forêt Enchantée',
          textAr: '{{childName}} والغابة السحرية العجيبة',
          textEn: '{{childName}} and the Enchanted Forest',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'forest_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que chaque aventure de ta vie soit guidée par ta curiosité, ta tendresse et ton merveilleux sourire.',
          textAr: 'إلى {{childName}} الغالية، بمناسبة بلوغك {{childAge}} سنوات. دمتِ دائماً رمزاً للبراءة والنور في كل خطوة.',
          textEn: 'For {{childName}}, {{childAge}} years old. May every step of your journey be filled with wonder, warmth and your bright lovely smile.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_clearing',
          textFr: 'Ce matin-là, le soleil réveillait doucement les pétales du jardin. {{childName}} enfila ses chaussures d’aventurier{{accord_e}} et aperçut un sentier secret bordé de mousse violette.',
          textAr: 'في صباح باكر، كانت خيوط الشمس الذهبية تداعب أزهار الصباح. ارتدت {{childName}} حذاء المغامرة، ولاحظت درباً سرياً مخضراً يناديها بلطف.',
          textEn: 'On that morning, soft golden sunbeams woke the garden blossoms. {{childName}} slipped on explorer shoes and noticed a hidden mossy path leading into the trees.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_portal',
          textFr: 'En passant sous l’arche d’aubépine, les bruissements devinrent des mélodies. Les feuilles chantaient au vent et les champignons projetaient de tendres reflets arc-en-ciel.',
          textAr: 'وعندما عبرت تحت قوس الأغصان المتشابكة، تحولت حفيف الأشجار إلى أنغام عذبة، وبدت قطرات الندى كأنها حبات لؤلؤ نادرة تبتسم للصباح.',
          textEn: 'Stepping beneath the archway of sweet wild blossoms, the rustling leaves sang gentle melodies, reflecting soft pastel rainbow light in every dewdrop.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_animal_meet',
          textFr: '« Bienvenue dans notre refuge, {{childName}} ! », gazouilla Barnabé le {{favoriteAnimal}}. « Nous t’attendions pour retrouver la Clé d’Étoile avant le coucher du soleil. »',
          textAr: '«أهلاً بك في ملاذنا السري يا {{childName}}!» هتف {{favoriteAnimal}} بفرح غامر: «كنا بانتظارك لتساعدينا في العثور على مفتاح النجوم قبل أن تغرب الشمس.»',
          textEn: '"Welcome to our woodland haven, {{childName}}!" chirped Barnaby the {{favoriteAnimal}}. "We have been hoping a kind friend like you could help find the Starlight Key before twilight."',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_glowing_stream',
          textFr: 'Ensemble, ils longèrent le ruisseau scintillant. {{childName}} observa les reflets de l’eau claire et remarqua une douce lueur nichée au fond d’une coquille nacrée.',
          textAr: 'سارت {{childName}} جنباً إلى جنب مع أصدقائها بجانب الجدول الصافي، فلاحظت بريقاً دافئاً يستقر داخل صدفة لامعة بين الحصى الملونة.',
          textEn: 'Hand in paw, they walked beside the singing brook. {{childName}} looked closely into the calm water and spotted a tiny glow nestled inside a pearly shell.',
        },
        {
          pageNumber: 7,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'forest_magic_tree',
          textFr: 'Avec précaution, {{childName}} ramassa la clé brillante et la tendit à Barnabé. En la plaçant sur l’Arbre des Songes, une pluie d’étoiles bienveillantes enlaça toute la forêt.',
          textAr: 'التقطت {{childName}} المفتاح بحذر ونظرة فخر تملأ عينيها. وحين وضعته في قفل الشجرة القديمة، تساقطت أنوار فضية عطرة تغمر الغابة بدفء لا يوصف.',
          textEn: 'With gentle care, {{childName}} lifted the shining key. As it touched the hollow of the ancient Dream Tree, a shower of comforting stardust embraced the canopy.',
        },
        {
          pageNumber: 8,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_celebration',
          textFr: 'Les écureuils, les hérissons et les faons partagèrent des baies sucrées et des gâteaux au miel pour célébrer le courage et la douceur de {{childName}}.',
          textAr: 'اجتمع السناجب والغزلان والطيور ليقتسموا الفواكه اللذيذة وحلوى العسل، محتفلين بذكاء وشجاعة {{childName}} التي أسعدت الجميع.',
          textEn: 'The squirrels, deer and songbirds shared sweet berries and honey treats, singing praises of {{childName}}’s bravery and warm spirit.',
        },
        {
          pageNumber: 9,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_bedtime_calm',
          textFr: 'Le soleil se couchait doucement en teintes d’or et de rose. Les paupières de {{childName}} devenaient lourdes. « Reviens quand tu voudras, la forêt sera toujours ton amie », souffla le vent.',
          textAr: 'ومع غروب الشمس بألوان الشفق البرتقالية الرائعة، أحست {{childName}} بدفء النعاس يغمر جفونها: «عودي متى شئتِ، فالغابة ستظل بيتك وصديقتك دوماً».',
          textEn: 'As the twilight painted the sky in shades of peach and violet, {{childName}} smiled contentedly. "Whenever you need wonder, the enchanted forest will welcome you," whispered the gentle breeze.',
        },
        {
          pageNumber: 10,
          layout: 'back_cover',
          sceneIllustrationId: 'forest_back',
          textFr: 'Livre d’histoire créé pour {{childName}}. Garde toujours cette lumière et cette générosité dans ton cœur. Fin de l’histoire.',
          textAr: 'كتاب قصة فريد أُهدي إلى {{childName}}. احتفظي دائماً بروح المحبة والجمال التي تضيء كل مكان. نهاية القصة.',
          textEn: 'A keepsake story created for {{childName}}. Always carry this radiant warmth and kindness in your heart. The End.',
        },
      ],
      12: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'forest_cover',
          textFr: '{{childName}} et la Forêt Enchantée',
          textAr: '{{childName}} والغابة السحرية العجيبة',
          textEn: '{{childName}} and the Enchanted Forest',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'forest_dedication',
          textFr: 'À {{childName}}, {{childAge}} ans. Que chaque jour soit une page remplie d’amitié, de rires et de merveilleuses découvertes.',
          textAr: 'إلى قرة العين {{childName}} في عامها الـ{{childAge}}. كوني دائماً واثقة الخطى ومحبة للخير ومصدر فخر لمن حولك.',
          textEn: 'To {{childName}}, {{childAge}} years old. May every day unfold like an inspiring page filled with laughter, friendship and discovery.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_clearing',
          textFr: 'Au bord d’une petite clairière baignée de rosée matinale, {{childName}} aimait écouter le chant des oiseaux. C’est là qu’apparut un sentier parsemé de cailloux bleus.',
          textAr: 'عند أطراف مرج أخضر يغتسل بقطرات الندى، كانت {{childName}} تستمتع بزقزقة العصافير، حين لفت انتباهها ممر مزين بحصى زرقاء متلألئة.',
          textEn: 'At the edge of a dewy meadow, {{childName}} loved listening to bird songs. Right there appeared a little path speckled with blue pebbles.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_portal',
          textFr: 'Curieu{{curieux_curieuse}}, {{childName}} fit un pas, puis deux. Les grands arbres semblaient s’écarter avec révérence pour laisser passer {{notre_cher_chere}} explorat{{accord_ne}}rice.',
          textAr: 'خطت {{childName}} خطوتها الأولى بكل حماس ورشاقة، وبدت الأغصان وكأنها تفسح لها المجال بمحبة وترحاب كبيرين.',
          textEn: 'Curious and bold, {{childName}} took one step, then two. The tall trees seemed to gently lean aside to welcome our brave explorer.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_animal_meet',
          textFr: 'Sous un saule argenté, Barnabé le {{favoriteAnimal}} regardait le ciel d’un air soucieux. « Sans la Clé d’Étoile, les lanternes des lucioles ne pourront pas briller ce soir », expliqua-t-il.',
          textAr: 'تحت شجرة صفصاف فضية، كان {{favoriteAnimal}} ينظر بقلق إلى السماء: «إن لم نجد مفتاح النجوم، فلن تستطيع اليرقات المضيئة إنارة درب العودة لأطفال الحيوانات الليلة».',
          textEn: 'Under a silver willow, Barnaby the {{favoriteAnimal}} looked up with worry. "Without the Starlight Key, the firefly lanterns cannot glow tonight," he explained.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_clues',
          textFr: '{{childName}} posa une main rassurante sur son épaule : « Ne perdons pas espoir ! Cherchons des indices ensemble. Regarde ces empreintes dorées près de la mousse ! »',
          textAr: 'وضعت {{childName}} يدها الرقيقة على كتف صديقها وقالت بحنان: «لا تيأس أبداً! فلنبحث معاً، انظر إلى هذه الآثار اللامعة قرب الصخور!»',
          textEn: '{{childName}} placed a comforting hand on his shoulder: "Never lose hope! Let us follow the clues together. Look at these golden footprints beside the moss!"',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_glowing_stream',
          textFr: 'Les traces les conduisirent vers un pont de bois fleuri au-dessus d’une eau si claire qu’on y voyait nager de petits poissons luminescents de couleur {{favoriteColor}}.',
          textAr: 'قادتهما الآثار نحو جسر خشبي مغطى بالأزهار فوق مياه نقية تسبح فيها أسماك براقة بلون {{favoriteColor}} المفضل لدى {{childName}}.',
          textEn: 'The footprints led them toward a wooden footbridge where little glowing fish in beautiful shades of {{favoriteColor}} danced beneath the ripples.',
        },
        {
          pageNumber: 8,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_magic_tree',
          textFr: 'Et là, nichée entre deux racines moussues, reposait la précieuse Clé d’Étoile. Dès que {{childName}} la prit, elle diffusa une chaleur douce et apaisante.',
          textAr: 'وهناك تماماً، بين جذور الشجرة القديمة، كان المفتاح يشع ببريق هادئ يبعث الطمأنينة والأمل في الأرجاء.',
          textEn: 'And there, nestled between two leafy roots, lay the precious Starlight Key. As {{childName}} lifted it, a comforting warmth spread through their hands.',
        },
        {
          pageNumber: 9,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'forest_tree_bloom',
          textFr: 'Ensemble, ils tournèrent la clé dans le cœur de l’Arbre des Songes. Instantanément, des millions de boutons floraux s’ouvrirent dans une explosion de parfums et de lumières féeriques.',
          textAr: 'معاً، أدارا المفتاح في قلب الشجرة الكبرى، ففتحت في الحال ملايين البراعم أزهارها لتعم روائح الياسمين والمسك كل ركن في الغابة.',
          textEn: 'Together, they turned the key inside the Dream Tree. Instantly, millions of flowers blossomed in an orchestra of sweet fragrances and starlit colors.',
        },
        {
          pageNumber: 10,
          layout: 'illustration_top',
          sceneIllustrationId: 'forest_celebration',
          textFr: 'Une fête grandiose débuta ! Tous les animaux offrirent à {{childName}} une couronne de feuilles dorées, en la proclamant Protect{{accord_ne}}rice de la Forêt Enchantée.',
          textAr: 'انطلقت احتفالات بهيجة، وقدم أصدقاء الغابة لـ{{childName}} إكليلاً من الأوراق الذهبية تكريماً لشجاعتها ونبل أخلاقها.',
          textEn: 'A magnificent party began! All animals gifted {{childName}} a crown of golden leaves, naming our hero the Guardian Friend of the Enchanted Forest.',
        },
        {
          pageNumber: 11,
          layout: 'side_by_side',
          sceneIllustrationId: 'forest_bedtime_calm',
          textFr: 'Le crépuscule venu, {{childName}} regagna sa chambre le cœur rempli d’étoiles. En s’endormant, {{il_elle}} entendit un doux chant d’oiseau lui murmurer : « Merci pour ton amour. »',
          textAr: 'ومع حلول الليل الهادئ، عادت {{childName}} إلى سريرها الدافئ وقلبها ينبض بالفرح، ونامت وهي تسمع تغريدة عصفور يهمس: «شكراً لقلبك الطيب».',
          textEn: 'As dusk arrived, {{childName}} tucked safely into bed with a heart full of stars, listening to the soft night breeze whisper: "Thank you for your gentle heart."',
        },
        {
          pageNumber: 12,
          layout: 'back_cover',
          sceneIllustrationId: 'forest_back',
          textFr: 'Ce livre appartient à {{childName}}. Que la magie de la bienveillance t’accompagne tout au long de ta vie. Édition souvenir.',
          textAr: 'هذا الكتاب ملك خاص لـ{{childName}}. لتبقَ روح الطيبة والعطاء رفيقتك في كل زمان ومكان. طبعة تذكارية مميزة.',
          textEn: 'This book belongs to {{childName}}. May the magic of friendship and kindness light your path forever. Souvenir Edition.',
        },
      ],
    },
  },

  // 2. LE PETIT EXPLORATEUR DE L'ESPACE
  {
    id: 'little_space_explorer',
    titleFr: 'Le Petit Explorateur de l’Espace',
    titleAr: 'مستكشف الفضاء الصغير',
    titleEn: 'The Little Space Explorer',
    subtitleFr: 'Un voyage interstellaire vers la planète des rêves',
    subtitleAr: 'رحلة بين الكواكب والنجوم نحو كوكب الأحلام السعيدة',
    subtitleEn: 'An interstellar voyage to the Planet of Dreams',
    descriptionFr: 'À bord d’une fusée étincelante, {{childName}} traverse la voie lactée, aide un petit robot réparateur et découvre une planète aux anneaux de cristal.',
    descriptionAr: 'على متن مركبة فضائية لامعة، تنطلق {{childName}} في رحلة عبر مجرة درب التبانة لمساعدة روبوت صغير واكتشاف كوكب الحلقات الكريستالية.',
    descriptionEn: 'Aboard a gleaming spaceship, {{childName}} glides across the Milky Way, helps a friendly little robot, and discovers a crystal-ring planet.',
    badgeFr: 'Cosmos & Science',
    badgeAr: 'فضاء وعلوم',
    badgeEn: 'Cosmos & Science',
    themes: ['Imagination', 'Curiosité', 'Science', 'Courage'],
    ageMin: 3,
    ageMax: 9,
    colorScheme: {
      primary: '#4f46e5',
      primaryLight: '#e0e7ff',
      primaryDark: '#312e81',
      accent: '#06b6d4',
      badgeBg: '#eef2ff',
      badgeText: '#4338ca',
      coverGradient: 'from-indigo-700 via-slate-900 to-sky-900',
    },
    coverIllustrationId: 'space_cover',
    supportedPageCounts: [8, 10, 12],
    pagesByCount: {
      8: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'space_cover',
          textFr: '{{childName}} et le Secret des Étoiles',
          textAr: '{{childName}} وسر النجوم المتلألئة',
          textEn: '{{childName}} and the Secret of the Stars',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'space_dedication',
          textFr: 'Dédié à {{childName}}, {{childAge}} ans. Vise toujours la lune, car même en cas d’échec, tu atterriras parmi les étoiles.',
          textAr: 'مهدى إلى {{childName}}، {{childAge}} سنوات. اصعدي دائماً نحو القمم، فمكانك دوماً بين النجوم الساطعة.',
          textEn: 'Dedicated to {{childName}}, {{childAge}} years old. Always reach for the stars, for your curiosity can light up galaxies.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_rocket_launch',
          textFr: '3... 2... 1... Décollage ! Dans sa combinaison argentée sur mesure, {{childName}} pilote sa navette vers les constellations lointaines.',
          textAr: 'ثلاثة... اثنان... واحد... انطلاق! ببدلتها الفضائية الأنيقة، تقود {{childName}} مركبتها الفضائية نحو المجرات البعيدة بشجاعة.',
          textEn: '3... 2... 1... Blast off! In a custom silver spacesuit, {{childName}} steers the sleek starship toward distant constellations.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_robot_meet',
          textFr: 'Près d’une comète bleutée, un petit robot tout rond nommé Bip-Bip flottait doucement. « Bip ! Ma batterie solaire s’est déchargée en admirant Saturne », fit-il tristement.',
          textAr: 'قرب مذنب لامع، كان روبوت فضائي لطيف يدعى بيبو يطفو في الفضاء: «لقد نفدت بطاريتي الشمسية وأنا أتأمل جمال الكواكب الزرقاء».',
          textEn: 'Near an azure comet, a cute round robot named Beep-Beep floated gently. "Beep! My solar core ran low while admiring the rings of Saturn," it beeped.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_crystal_rings',
          textFr: 'Sans hésiter, {{childName}} utilisa son miroir de poche en verre poli pour capter les rayons d’une étoile filante et recharger Bip-Bip en un clin d’œil !',
          textAr: 'دون تردد، استخدمت {{childName}} مرآة عاكسة لتركز أشعة النجوم الذهبية، وسرعان ما امتلأت بطارية بيبو بالطاقة والحيوية!',
          textEn: 'Without hesitation, {{childName}} angled a polished starlight reflector to catch the glow of a passing nebula, instantly recharging Beep-Beep!',
        },
        {
          pageNumber: 6,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'space_planet_wonder',
          textFr: 'Pour remercier {{childName}}, Bip-Bip la guida vers la planète Céleslia, où le sol est fait de poussière de diamant et où les aurores boréales dansent au son de la flûte.',
          textAr: 'عرفاناً بجميلها، رافق بيبو {{childName}} إلى كوكب زمردي عجيب ترقص فيه الأضواء القطبية بألوان البنفسج والوردي البديعة.',
          textEn: 'In gratitude, Beep-Beep guided {{childName}} to Planet Caelum, where iridescent crystal dust glimmers and aurora waves dance in harmony.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_homecoming',
          textFr: 'Après avoir dégusté un délicieux chocolat chaud en apesanteur, {{childName}} salua ses nouveaux amis et remit le cap sur la Terre, berceau de ses plus beaux rêves.',
          textAr: 'وبعد لحظات لا تُنسى من المرح وتبادل الضحكات في انعدام الجاذبية، ودعت {{childName}} أصدقاء الفضاء عائدة إلى كوكب الأرض المحبوب.',
          textEn: 'After savoring a warm zero-gravity cocoa, {{childName}} waved goodbye to the cosmic friends and set coordinates back home to Earth.',
        },
        {
          pageNumber: 8,
          layout: 'back_cover',
          sceneIllustrationId: 'space_back',
          textFr: 'L’univers est infini, tout comme l’imagination de {{childName}}. Bonne nuit petit{{accord_e}} cosmonaute !',
          textAr: 'الكون فسيح وبلا حدود، تماماً مثل خيال {{childName}} الخصب. ليلة سعيدة يا بطلة الفضاء الصغيرة!',
          textEn: 'The universe is boundless, just like {{childName}}’s soaring imagination. Sleep tight, little astronaut!',
        },
      ],
      10: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'space_cover',
          textFr: '{{childName}} et le Secret des Étoiles',
          textAr: '{{childName}} وسر النجوم المتلألئة',
          textEn: '{{childName}} and the Secret of the Stars',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'space_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que ton esprit voyage toujours plus haut que les galaxies.',
          textAr: 'إلى {{childName}}، {{childAge}} سنوات. لتكن طموحاتك دوماً أعلى من أبعد المجرات.',
          textEn: 'For {{childName}}, {{childAge}} years old. May your spirit always fly higher than the farthest stars.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_control_room',
          textFr: 'Dans sa chambre transformée en base de lancement, {{childName}} étudiait une mystérieuse carte stellaire quand les écrans s’allumèrent en bleu turquoise.',
          textAr: 'في غرفتها التي حولتها لمقر فضائي مصغر، كانت {{childName}} تتفحص خريطة المجموعات النجمية عندما أضاءت الشاشة بزرقة جذابة.',
          textEn: 'In a room turned into a space control station, {{childName}} studied a map of constellations as the consoles glowed with soft cyan light.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_rocket_launch',
          textFr: 'Un signal sonore amical retentit. La porte du vaisseau « Nova-{{childAge}} » s’ouvrit pour accueillir {{childName}}, paré{{accord_e}} pour la grande odyssée.',
          textAr: 'انطلقت نغمة موسيقية عذبة، وفُتح باب المركبة الفضائية لترحب بـ{{childName}} الجاهزة لخوض أعظم رحلة استكشافية.',
          textEn: 'A friendly chime sounded. The hatch of starcraft "Nova-{{childAge}}" opened to welcome {{childName}}, fully ready for the grand odyssey.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_milky_way',
          textFr: 'À travers le hublot panoramique, la Terre ressemblait à une magnifique bille bleue et blanche flottant dans un velours d’encre étoilé.',
          textAr: 'من خلال نافذة المركبة الدائرية، بدا كوكب الأرض كأنه جوهرة زرقاء براقة تسبح في سماء مخملية منثورة بالنجوم.',
          textEn: 'Through the panoramic viewport, Earth looked like a breathtaking blue and white marble resting peacefully upon dark starry velvet.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_robot_meet',
          textFr: 'C’est alors que {{childName}} aperçut Bip-Bip le robot explorateur, coincé près d’une ceinture d’astéroïdes dorés. « Besoin d’un coup de main ? », demanda {{childName}}.',
          textAr: 'وحينها لمحت {{childName}} الروبوت بيبو معلقاً قرب حزام كويكبات ذهبي: «هل تحتاج يد عون يا صديقي الصغير؟» سألته بلطف.',
          textEn: 'That was when {{childName}} spotted Beep-Beep the scout bot, drifting near a golden asteroid belt. "Need a helping hand?" asked {{childName}}.',
        },
        {
          pageNumber: 7,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'space_crystal_rings',
          textFr: 'Grâce à son esprit d’équipe et son calme olympien, {{childName}} guida le bras télescopique pour ramener Bip-Bip en sécurité à bord.',
          textAr: 'بكل هدوء ومهارة، وجهت {{childName}} الذراع الآلي لتنقذ بيبو بأمان وتدخله إلى قمرة القيادة وسط تصفيق شاشات التحكم.',
          textEn: 'With cool focus and quick thinking, {{childName}} piloted the docking arm to bring Beep-Beep safely inside the airlock.',
        },
        {
          pageNumber: 8,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_planet_wonder',
          textFr: 'Ensemble, ils contemplèrent la grande pluie d’étoiles filantes de couleur {{favoriteColor}} qui illuminait l’horizon cosmique.',
          textAr: 'معاً، شاهدا عرضاً مبهراً لشهب مضيئة بدرجات لون {{favoriteColor}} المفضل، أضاءت الأفق الكوني بجمال لا يضاهى.',
          textEn: 'Together, they marveled at a sparkling meteor shower in vibrant shades of {{favoriteColor}} illuminating the cosmic horizon.',
        },
        {
          pageNumber: 9,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_homecoming',
          textFr: '« Mission accomplie, capitaine {{childName}} ! », gazouilla le petit robot en lui remettant une médaille forgée dans un éclat de météorite douce.',
          textAr: '«تمت المهمة بنجاح باهر يا كابتن {{childName}}!» هتف الروبوت الصغير وهو يقدم لها وسام الشرف الفضائي المرصع بالنجوم.',
          textEn: '"Mission accomplished, Captain {{childName}}!" chirped the happy bot, presenting a shining constellation badge.',
        },
        {
          pageNumber: 10,
          layout: 'back_cover',
          sceneIllustrationId: 'space_back',
          textFr: 'La tête pleine d’étoiles et le cœur empli de bravoure. Un livre souvenir pour {{childName}}.',
          textAr: 'برأس مفعم بالأفكار النيرة وقلب شجاع. كتاب ذكريات رائع لأجل {{childName}}.',
          textEn: 'Head full of constellations, heart full of courage. A keepsake book for {{childName}}.',
        },
      ],
      12: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'space_cover',
          textFr: '{{childName}} et le Secret des Étoiles',
          textAr: '{{childName}} وسر النجوم المتلألئة',
          textEn: '{{childName}} and the Secret of the Stars',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'space_dedication',
          textFr: 'À notre merveilleux{{accord_e}} {{childName}}, {{childAge}} ans. Explore le monde avec passion et bienveillance.',
          textAr: 'إلى بطلتنا المحبوبة {{childName}} في عيدها الـ{{childAge}}. استكشفي العالم بشغف وعطاء لا ينضب.',
          textEn: 'To our wonderful {{childName}}, {{childAge}} years old. Explore the world with passion, kindness and wonder.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_control_room',
          textFr: 'Chaque soir, {{childName}} regardait le ciel par sa fenêtre en rêvant de toucher les nébuleuses scintillantes.',
          textAr: 'كل مساء، كانت {{childName}} تتأمل السماء من نافذتها وتحلم بملامسة السدم المضيئة والتحليق بين الكواكب.',
          textEn: 'Every evening, {{childName}} gazed through the window, dreaming of dancing with the glowing nebulae.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_rocket_launch',
          textFr: 'Mais ce soir était magique : un rayon stellaire vint matérialiser une porte lumineuse menant au poste de pilotage du vaisseau Cosmos-One.',
          textAr: 'وفي تلك الليلة المميزة، نزل شعاع سحري ليفتح بوابة براقة تقود مباشرة إلى قمرة قيادة المركبة الفضائية الحديثة.',
          textEn: 'Tonight was magical: a gentle beam of starlight formed a glowing doorway directly to the bridge of starship Cosmos-One.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_milky_way',
          textFr: 'D’une main assurée, {{childName}} actionna les commandes. Les propulseurs à poussière d’étoiles propulsèrent la navette à travers le système solaire.',
          textAr: 'بيد واثقة، ضغطت {{childName}} على زر التشغيل، فانطلقت المحركات لتطير المركبة بسلاسة خارقة بين كواكب المجموعة الشمسية.',
          textEn: 'With steady hands, {{childName}} engaged the thrusters, propelling the ship smoothly through the solar neighborhood.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_saturn_rings',
          textFr: 'En contournant les majestueux anneaux de glace, {{childName}} admira les fragments brillants qui tournoyaient comme des carrousels de verre.',
          textAr: 'أثناء دورانها حول حلقات الكواكب الجليدية، تأملت {{childName}} البلورات الناصعة وهي تدور كأنها مدن ألعاب كونية مذهلة.',
          textEn: 'Gliding past giant icy rings, {{childName}} admired billions of bright crystals spinning like carousels of light.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_robot_meet',
          textFr: 'Soudain, un message de détresse clignota : Bip-Bip, l’assistant robotique de la station lunaire, s’était égaré dans la nébuleuse pourpre.',
          textAr: 'وفجأة، ومض نداء استغاثة ودي: كان الروبوت بيبو قد تاه في سحابة كونية بنفسجية أثناء جمعه لعينات الغبار الفضائي.',
          textEn: 'Suddenly, a friendly distress signal pulsed: Beep-Beep, the moon station’s assistant bot, was adrift in the purple nebula.',
        },
        {
          pageNumber: 8,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_crystal_rings',
          textFr: '« Tiens bon Bip-Bip, j’arrive ! », lança {{childName}}. En combinant les capteurs optiques et sa carte astrale, {{il_elle}} le localisa en quelques instants.',
          textAr: '«اصمد يا بيبو، أنا قادمة لمساعدتك!» نادت {{childName}}، وباستخدام ذكائها وخريطتها حددت موقعه بدقة متناهية.',
          textEn: '"Hang tight Beep-Beep, I am on my way!" called {{childName}}. Using radar sensors and star coordinates, our hero located him in no time.',
        },
        {
          pageNumber: 9,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'space_planet_wonder',
          textFr: 'Bip-Bip fut accueilli chaleureusement à bord. Pour fêter cette réussite, les deux explorateurs atterrirent sur la Planète aux Cristaux Chantants.',
          textAr: 'صعد بيبو إلى المركبة بفرح غامر، واحتفالاً بالنجاح هبط المستكشفان على كوكب الكريستال الساحر ليستمتعا بأنغامه الرائعة.',
          textEn: 'Beep-Beep was welcomed warmly aboard. To celebrate, the two explorers touched down on the Planet of Singing Crystals.',
        },
        {
          pageNumber: 10,
          layout: 'illustration_top',
          sceneIllustrationId: 'space_celebration',
          textFr: 'Chaque cristal effleuré jouait une mélodie douce, composant une berceuse cosmique spécialement dédiée à {{childName}}.',
          textAr: 'كل بلورة يلمسانها كانت تعزف لحناً عذباً، مشكلة سيمفونية دافئة أُهديت إلى {{childName}} تقديراً لجمال روحها.',
          textEn: 'Each crystal touched hummed a harmonious tone, composing a cosmic lullaby dedicated especially to {{childName}}.',
        },
        {
          pageNumber: 11,
          layout: 'side_by_side',
          sceneIllustrationId: 'space_homecoming',
          textFr: 'Le voyage de retour se fit en douceur. Les étoiles veillaient sur la navette alors que {{childName}} retrouvait son oreiller moelleux.',
          textAr: 'كانت رحلة العودة في غاية الراحة والسكينة، ونامت {{childName}} على وسادتها الوثيرة وأحلام المغامرة تملأ قلبها أملاً.',
          textEn: 'The flight home was tranquil and smooth. Starlight guarded the starship as {{childName}} settled back into a cozy pillow.',
        },
        {
          pageNumber: 12,
          layout: 'back_cover',
          sceneIllustrationId: 'space_back',
          textFr: 'Pour {{childName}}, gardien{{accord_ne}} des étoiles. Le ciel nocturne te sourira toujours. Fin.',
          textAr: 'إلى {{childName}}، حارسة النجوم المتألقة. ستبتسم لك سماء الليل دائماً بكل محبة. النهاية.',
          textEn: 'To {{childName}}, guardian of constellations. The night sky will always smile upon you. The End.',
        },
      ],
    },
  },

  // 3. L'AVENTURE SOUS-MARINE
  {
    id: 'underwater_adventure',
    titleFr: 'Le Mystère du Lagon Bleu',
    titleAr: 'مغامرة أعماق البحار العجيبة',
    titleEn: 'The Mystery of the Blue Lagoon',
    subtitleFr: 'Nager parmi les coraux aux côtés de joyeux dauphins',
    subtitleAr: 'السباحة بين الشعاب المرجانية برفقة الدلافين والأسماك الذهبية',
    subtitleEn: 'Swimming among coral reefs with playful dolphins',
    descriptionFr: 'Équipé{{accord_e}} de son masque magique, {{childName}} plonge dans les eaux cristallines pour aider une petite tortue marine à retrouver le récif aux mille perles.',
    descriptionAr: 'ترتدي {{childName}} قناع الغوص السحري وتغوص في أعماق المياه الفيروزية لتساعد سلحفاة بحرية لطيفة في العثور على موطن اللآلئ المضيئة.',
    descriptionEn: 'Equipped with a magic diving mask, {{childName}} dives into crystal waters to help a baby sea turtle find the Reef of a Thousand Pearls.',
    badgeFr: 'Océan & Nature',
    badgeAr: 'محيطات وبيئة',
    badgeEn: 'Ocean & Wildlife',
    themes: ['Nature', 'Écologie', 'Découverte', 'Amitié'],
    ageMin: 3,
    ageMax: 9,
    colorScheme: {
      primary: '#0284c7',
      primaryLight: '#e0f2fe',
      primaryDark: '#0369a1',
      accent: '#f97316',
      badgeBg: '#f0f9ff',
      badgeText: '#0284c7',
      coverGradient: 'from-cyan-600 via-sky-800 to-blue-950',
    },
    coverIllustrationId: 'ocean_cover',
    supportedPageCounts: [8, 10, 12],
    pagesByCount: {
      8: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'ocean_cover',
          textFr: '{{childName}} et le Mystère du Lagon Bleu',
          textAr: '{{childName}} ومغامرة أعماق البحار العجيبة',
          textEn: '{{childName}} and the Blue Lagoon Mystery',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'ocean_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que ton cœur soit aussi vaste, généreux et libre que le grand océan.',
          textAr: 'إلى {{childName}} الغالية في عامها الـ{{childAge}}. ليكن قلبك دوماً نقياً وفسيحاً كأعماق البحار الساحرة.',
          textEn: 'For {{childName}}, {{childAge}} years old. May your spirit be as vast, kind and free as the open ocean.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_beach_start',
          textFr: 'Sur une plage de sable chaud, {{childName}} trouva un coquillage nacré qui chuchotait une chanson marine. En le posant sur son oreille, l’eau devint une invitation.',
          textAr: 'على شاطئ رملي ذهبي دافئ، عثرت {{childName}} على صدفة لؤلؤية تعزف لحناً هادئاً كأنها تدعوها لزيارة عالم البحار العجيب.',
          textEn: 'On a warm sandy shore, {{childName}} discovered a pearly seashell whispering an ocean song, gently welcoming our hero into the clear waves.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_turtle_meet',
          textFr: 'Sous la surface turquoise, Nori la petite tortue marine nageait timidement : « Bonjour {{childName}} ! Un courant malicieux a emporté notre coquillage de cristal. »',
          textAr: 'تحت سطح الماء الفيروزي، اقتربت السلحفاة اللطيفة نوري: «مرحباً {{childName}}! لقد جرف تيار مائي سريع صدفة الكريستال التي تنير مأوانا».',
          textEn: 'Beneath turquoise waves, Nori the baby sea turtle swam up gently: "Hello {{childName}}! A playful current carried away our crystal shell."',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_coral_reef',
          textFr: '« N’aie pas peur, Nori, nous allons le retrouver ensemble ! », assura {{childName}} en nageant gracieusement aux côtés de bancs de poissons jaunes et argentés.',
          textAr: '«لا تخافي يا نوري، سنبحث عنها معاً بكل تأكيد!»، طمأنتها {{childName}} وهي تسبح بخفة وسرور برفقة أسراب الأسماك الملونة.',
          textEn: '"Do not worry, Nori, we will find it together!" assured {{childName}}, gliding effortlessly alongside schools of bright shimmering fish.',
        },
        {
          pageNumber: 6,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'ocean_pearl_find',
          textFr: 'Au cœur d’une forêt d’anémones bienveillantes, la coquille scintillait dans un rayon de soleil sous-marin. En la replaçant sur le récif, les coraux se mirent à rayonner.',
          textAr: 'في قلب حديقة الشعاب المرجانية، كانت الصدفة تلألأ مع أشعة الشمس المتسللة للماء. وحين أعادتها {{childName}}، أضاء المرجان بأكمله بألوان مبهرة.',
          textEn: 'Deep inside a grove of friendly sea anemones, the shell sparkled in a sunbeam. As {{childName}} placed it back on the reef, every coral branch glowed with life.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_dolphin_dance',
          textFr: 'Deux dauphins joueurs vinrent offrir à {{childName}} un ballet aquatique inoubliable, faisant jaillir des gerbes d’eau scintillantes sous le ciel radieux.',
          textAr: 'قدم دلفينان مرحان رقصة مائية مذهلة لـ{{childName}}، محلقين فوق الأمواج وسط هتافات كائنات البحر المحتفية بصداقتهما.',
          textEn: 'Two playful dolphins performed a joyful water dance for {{childName}}, leaping playfully above sparkling waves under the blue sky.',
        },
        {
          pageNumber: 8,
          layout: 'back_cover',
          sceneIllustrationId: 'ocean_back',
          textFr: 'Un livre marin dédié à {{childName}}. Prends toujours soin de la nature et de ses trésors. Fin.',
          textAr: 'كتاب بحري مهدى إلى {{childName}}. كوني دوماً صديقة وفية للطبيعة وحامية لجمالها. النهاية.',
          textEn: 'An ocean adventure book for {{childName}}. Always treasure and protect our living nature. The End.',
        },
      ],
      10: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'ocean_cover',
          textFr: '{{childName}} et le Mystère du Lagon Bleu',
          textAr: '{{childName}} ومغامرة أعماق البحار العجيبة',
          textEn: '{{childName}} and the Blue Lagoon Mystery',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'ocean_dedication',
          textFr: 'À {{childName}}, {{childAge}} ans. Que ta vie soit aussi douce et fascinante qu’un lagon ensoleillé.',
          textAr: 'إلى {{childName}}، {{childAge}} سنوات. نتمنى لك حياة هانئة تملؤها السعادة والتوفيق.',
          textEn: 'To {{childName}}, {{childAge}} years old. May your path be as tranquil and fascinating as a sunlit lagoon.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_beach_start',
          textFr: 'Le clapotis des vagues rythmait les pas de {{childName}} le long du rivage. Des reflets d’émeraude dansaient à la surface du lagon paisible.',
          textAr: 'كانت أمواج البحر الهادئة تعزف سمفونية طبيعية عذبة، بينما سارت {{childName}} على الرمال الناعمة متأملة مياه الخليج الزمردية.',
          textEn: 'Gentle waves lapped softly at the shore. Shimmers of emerald and sapphire danced across the peaceful lagoon.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_mask_wear',
          textFr: 'En ajustant son masque magique, l’eau devint aussi limpide que l’air pur. Un monde féerique de bulles et de lumières s’ouvrit devant ses yeux ébahis.',
          textAr: 'وضعت قناع الغوص، فبدت مياه البحر صافية كالهواء النقي، وظهر أمام عينيها عالم مدهش من الألوان والشعاب الزاهية.',
          textEn: 'Adjusting the diving goggles, the water appeared crystal clear, unveiling an undersea wonderland of coral gardens and soft light.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_turtle_meet',
          textFr: 'Nori la tortue de mer s’approcha avec élégance : « Bienvenue {{childName}} ! Le récif des Mille Perles a perdu sa lueur protectrice. Peux-tu nous guider ? »',
          textAr: 'سبحت السلحفاة نوري نحوها بدلال وأناقة: «مرحباً بك يا {{childName}}! هل يمكنك مساعدتنا في استعادة نور حيد اللآلئ المضيء؟»',
          textEn: 'Nori the sea turtle glided forward gracefully: "Welcome, {{childName}}! The Thousand Pearl Reef has lost its protective glow. Can you guide us?"',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_coral_reef',
          textFr: '{{childName}} accepta avec enthousiasme. Nageant en harmonie, ils contournèrent de majestueux jardins de coraux violets et dorés.',
          textAr: 'وافقت {{childName}} بفرح كبير، وسبحا معاً بتناغم رائع بين حدائق المرجان البنفسجية والذهبية الأخاذة.',
          textEn: '{{childName}} joyfully agreed. Swimming in harmony, they navigated magnificent fields of golden and purple sea fans.',
        },
        {
          pageNumber: 7,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'ocean_pearl_find',
          textFr: 'Grâce à l’œil attentif de {{childName}}, le grand coquillage protecteur fut retrouvé dans une crique sablonneuse, sain et sauf.',
          textAr: 'بفضل دقة ملاحظة {{childName}} وذكائها، عثرا على الصدفة الكريستالية في مأمن بين الرمال الناعمة، واستعادت بريقها فوراً.',
          textEn: 'Thanks to {{childName}}’s keen eye, the guardian pearl shell was located safely upon a velvet sandbed, glowing with warmth.',
        },
        {
          pageNumber: 8,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_dolphin_dance',
          textFr: 'Toutes les créatures marines célébrèrent cette victoire en formant un immense cercle d’amitié autour de {{childName}}.',
          textAr: 'احتفلت جميع كائنات البحر بهذا اليوم السعيد، وشكلت دائرة من المحبة والصداقة حول {{childName}} تقديراً لوفائها.',
          textEn: 'Every sea creature joined in celebration, forming a grand circle of friendship around {{childName}}.',
        },
        {
          pageNumber: 9,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_sunset_beach',
          textFr: 'De retour sur la berge dorée, le coucher de soleil embrasait l’horizon. {{childName}} savait que l’océan veillerait toujours sur ses amis.',
          textAr: 'وعند العودة إلى الشاطئ وقت الغروب الذهبي، كانت {{childName}} تدرك أن ذكريات هذا اليوم ستبقى محفورة في قلبها إلى الأبد.',
          textEn: 'Resting on the golden beach at sunset, {{childName}} knew the ocean and its gentle creatures would always hold a special place.',
        },
        {
          pageNumber: 10,
          layout: 'back_cover',
          sceneIllustrationId: 'ocean_back',
          textFr: 'Histoire personnalisée pour {{childName}}. Un souvenir marin inoubliable. Fait avec passion.',
          textAr: 'قصة بحرية خاصة بأبطالنا الصغار. أُهديت إلى {{childName}} بكل اعتزاز.',
          textEn: 'A personalized ocean story for {{childName}}. An unforgettable seaside memory.',
        },
      ],
      12: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'ocean_cover',
          textFr: '{{childName}} et le Mystère du Lagon Bleu',
          textAr: '{{childName}} ومغامرة أعماق البحار العجيبة',
          textEn: '{{childName}} and the Blue Lagoon Mystery',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'ocean_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que ta curiosité t’emmène explorer les plus beaux secrets du monde.',
          textAr: 'إلى {{childName}} الغالية في عامها الـ{{childAge}}. كوني دائماً شغوفة باستكشاف جمال العالم من حولك.',
          textEn: 'For {{childName}}, {{childAge}} years old. May your curiosity always lead you to uncover life’s most beautiful treasures.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_beach_start',
          textFr: 'Il était une fois une crique secrète où le sable blanc brillait comme du sucre glace sous le soleil d’été.',
          textAr: 'كان يا ما كان، في خليج هادئ تحرسه النخيل، كانت الرمال البيضاء تلمع كالسكر الناعم تحت أشعة الشمس الصيفية.',
          textEn: 'Once upon a time, in a hidden lagoon where white sands glistened like powdered sugar under the warm summer sun.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_mask_wear',
          textFr: '{{childName}} ajusta son masque et trempa la pointe de ses pieds dans l’eau tiède. Une vaguelette sembla lui murmurer un secret d’aventure.',
          textAr: 'وضعت {{childName}} قناع الغوص وغمست قدميها في الماء الدافئ، فداعبتها موجة لطيفة كأنها تدعوها لبدء المغامرة.',
          textEn: '{{childName}} fitted the diving mask and dipped toes into warm water. A tiny wave seemed to whisper a friendly invitation.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_turtle_meet',
          textFr: 'À quelques brasses, Nori la tortue marine salua notre petit{{accord_e}} nageu{{accord_ne}}r d’un battement de nageoire gracieux.',
          textAr: 'وعلى بُعد أمتار قليلة، لوحت السلحفاة نوري بزعانفها مرحبة بـ{{childName}} بحرارة واحترام فائقين.',
          textEn: 'Just a few strokes away, Nori the sea turtle waved a flipper gracefully to greet our adventurous swimmer.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_coral_reef',
          textFr: '« Les étoiles de mer nous ont parlé de toi, {{childName}} ! Tu es la seule personne capable de déchiffrer la carte corallienne », affirma Nori.',
          textAr: '«لقد حدثتنا نجوم البحر عن شجاعتك يا {{childName}}! وأنتِ القادرة على قراءة خريطة المرجان الذهبية»، قالت نوري بثقة.',
          textEn: '"The starfish spoke of your kind heart, {{childName}}! You are the friend who can help read the ancient coral map," Nori said.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_pearl_find',
          textFr: 'En observant les arabesques des récifs, {{childName}} repéra un motif en forme d’étoile indiquant une grotte aux reflets de nacre.',
          textAr: 'بملاحظة نقوش المرجان البديعة، اكتشفت {{childName}} علامة تشبه النجمة تشير إلى كهف صغير تعلوه حبات اللؤلؤ.',
          textEn: 'Observing the delicate coral patterns, {{childName}} spotted a star-shaped clue pointing to a peaceful pearl grotto.',
        },
        {
          pageNumber: 8,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_grotto_glow',
          textFr: 'Dans la grotte, la perle magique reposait sur un coussin de mousse aquatique. {{childName}} la prit doucement dans ses mains.',
          textAr: 'داخل الكهف، كانت اللؤلؤة الكبرى ترتاح على وسادة من العشب البحري، فحملتها {{childName}} بكل أمانة ورعاية.',
          textEn: 'Inside the grotto, the great guardian pearl rested on soft sea moss. {{childName}} held it gently with both hands.',
        },
        {
          pageNumber: 9,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'ocean_reef_restored',
          textFr: 'Dès que la perle fut remise en place au sommet du grand autel sous-marin, une onde turquoise revivifia tous les coraux du lagon.',
          textAr: 'وما إن وُضعت اللؤلؤة في مكانها، حتى سرت موجة من الضوء الفيروزي أنعشت كل كائنات وخبايا البحر المحيطة.',
          textEn: 'The moment the pearl returned to its sanctuary, a wave of bright turquoise light rejuvenated every coral in the bay.',
        },
        {
          pageNumber: 10,
          layout: 'illustration_top',
          sceneIllustrationId: 'ocean_dolphin_dance',
          textFr: 'Les dauphins sautèrent au-dessus de {{childName}} en esquissant des arcs-en-ciel d’embruns. Quelle fabuleuse symphonie marine !',
          textAr: 'قفزت الدلافين برشاقة مذهلة صانعة أقواس قزح من قطرات الماء المتطايرة تكريماً لـ{{childName}} وصنيعها البهي.',
          textEn: 'The dolphins leaped high above, tracing sparkling rainbows in the sea spray. What an unforgettable ocean symphony!',
        },
        {
          pageNumber: 11,
          layout: 'side_by_side',
          sceneIllustrationId: 'ocean_sunset_beach',
          textFr: 'De retour sur la plage, {{childName}} glissa le coquillage dans sa poche comme témoin de cette merveilleuse journée.',
          textAr: 'وعند العودة إلى الشاطئ، وضعت {{childName}} صدفة صغيرة في جيبها كذكرى خالدة ليوم ملؤه السحر والنقاء.',
          textEn: 'Back on the warm shore, {{childName}} slipped a tiny keepsake shell into pocket as a reminder of this magical voyage.',
        },
        {
          pageNumber: 12,
          layout: 'back_cover',
          sceneIllustrationId: 'ocean_back',
          textFr: 'Pour {{childName}}, ami{{accord_e}} des mers. Que tes rêves soient toujours aussi purs et limpides que l’océan. Fin.',
          textAr: 'إلى {{childName}}، صديقة البحار الوفية. لتكن أحلامك دائماً نقية وعذبة كأعماق المحيط. النهاية.',
          textEn: 'For {{childName}}, friend of the seas. May your dreams forever remain pure and bright. The End.',
        },
      ],
    },
  },

  // 4. MON AMI LE DINOSAURE
  {
    id: 'dinosaur_friend',
    titleFr: 'Mon Ami le Petit Dinosaure',
    titleAr: 'صديقي الديناصور اللطيف',
    titleEn: 'My Dinosaur Friend',
    subtitleFr: 'Une aventure préhistorique pleine d’humour et de courage',
    subtitleAr: 'مغامرة شيقة في وادي الديناصورات العجيب',
    subtitleEn: 'A prehistoric adventure filled with fun and courage',
    descriptionFr: 'En jouant dans son jardin, {{childName}} découvre un gentil bébé tricératops perdu et l’aide à retrouver sa maman dans la vallée aux fougères géantes.',
    descriptionAr: 'أثناء لعبها في الحديقة، تلتقي {{childName}} بصغير ديناصور ظريف تائه، وتساعده بكل شجاعة في العودة إلى والدته في الوادي الأخضر.',
    descriptionEn: 'While playing outside, {{childName}} finds a friendly baby triceratops and helps him find his mother in the Valley of Giant Ferns.',
    badgeFr: 'Aventure & Histoire',
    badgeAr: 'مغامرات وتاريخ',
    badgeEn: 'Adventure & Fun',
    themes: ['Courage', 'Coopération', 'Amitié', 'Aventure'],
    ageMin: 3,
    ageMax: 8,
    colorScheme: {
      primary: '#ca8a04',
      primaryLight: '#fef08a',
      primaryDark: '#854d0e',
      accent: '#ea580c',
      badgeBg: '#fefce8',
      badgeText: '#a16207',
      coverGradient: 'from-amber-600 via-orange-700 to-yellow-900',
    },
    coverIllustrationId: 'dino_cover',
    supportedPageCounts: [8, 10, 12],
    pagesByCount: {
      8: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'dino_cover',
          textFr: '{{childName}} et le Petit Dinosaure',
          textAr: '{{childName}} وصديقها الديناصور اللطيف',
          textEn: '{{childName}} and the Little Dinosaur',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'dino_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. N’aie jamais peur d’être courageu{{courageux_courageuse}} et d’aider les plus petits que toi.',
          textAr: 'إلى {{childName}} البطلة في عامها الـ{{childAge}}. كوني دوماً شجاعة وعوناً لمن يحتاج مساعدتك.',
          textEn: 'For {{childName}}, {{childAge}} years old. Never be afraid to be brave and help friends big and small.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_garden_find',
          textFr: 'Derrière les buissons du jardin, un bruit inhabituel attira l’attention de {{childName}} : « Crounch, crounch ! » Un bébé dinosaure vert grignotait des pissenlits.',
          textAr: 'خلف شجيرات الحديقة، سمعت {{childName}} صوتاً ظريفاً: «قرمش، قرمش!» وإذا بديناصور صغير أخضر يبتسم ويأكل أوراق الزهور.',
          textEn: 'Behind the garden hedges, a soft rustle caught {{childName}}’s ear: "Crunch, crunch!" A green baby dinosaur was happily munching clover.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_meet_friend',
          textFr: 'Le petit dinosaure s’appelait Titou. Il avait trois petites cornes douces et de grands yeux pétillants. « J’ai perdu ma maman près de la colline aux cascades », soupira-t-il.',
          textAr: 'كان الديناصور الصغير يدعى تيتو، بعينين براقتين ووجه بريء: «لقد ابتعدت عن أمي قرب تلال الشلالات الجميلة»، قال بحزن خفيف.',
          textEn: 'The friendly little dinosaur was named Tito. He had three tiny soft horns and bright eyes. "I wandered away from my mommy near the waterfall hill," he said.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_valley_walk',
          textFr: '« Viens avec moi Titou, je connais le chemin ! », déclara fièrement {{childName}}. En route, ils traversèrent la vallée aux fougères géantes en chantonnant.',
          textAr: '«لا تحزن يا تيتو، سأرافقك حتى تجدها!» قالت {{childName}} بفخر وشجاعة، وانطلقا معاً عبر وادي النباتات العملاقة بأمان.',
          textEn: '"Come with me Tito, we will find her together!" declared {{childName}} proudly. Together they crossed the Valley of Giant Ferns with happy songs.',
        },
        {
          pageNumber: 6,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'dino_bridge_crossing',
          textFr: 'Devant un ruisseau impétueux, {{childName}} eut l’idée géniale d’utiliser un tronc de palmier creux comme pont suspendu. Titou put traverser sans mouiller ses petites pattes !',
          textAr: 'وعندما وصلا إلى نهر سريع الجريان، ابتكرت {{childName}} فكرة ذكية بوضع جذع شجرة كنطاق عبور آمن، فمر تيتو دون أن تتبلل أقدامه الصغيرة!',
          textEn: 'Facing a swift stream, {{childName}} cleverly placed a fallen palm trunk as a safe footbridge. Tito crossed easily without even dampening a paw!',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_mom_reunion',
          textFr: 'De l’autre côté, une immense maman tricératops poussa un grondement joyeux en voyant son petit. Elle posa délicatement son museau sur l’épaule de {{childName}} pour la remercier.',
          textAr: 'وعلى الجانب الآخر، أطلت الأم بحنان وفرح غامر حين رأت صغيرها، ولمست كتف {{childName}} بلطف كبير تعبيراً عن امتنانها.',
          textEn: 'On the other side, a majestic mother dinosaur let out a joyful rumble upon seeing her baby. She gently nuzzled {{childName}}’s shoulder in heartfelt thanks.',
        },
        {
          pageNumber: 8,
          layout: 'back_cover',
          sceneIllustrationId: 'dino_back',
          textFr: 'Les plus grandes amitiés n’ont pas d’âge ni d’époque. Une aventure préhistorique pour {{childName}}.',
          textAr: 'الصداقة الحقيقية تتجاوز كل الحدود والأزمنة. مغامرة رائعة مهداة إلى {{childName}}.',
          textEn: 'True friendship knows no time or distance. A prehistoric adventure keepsake for {{childName}}.',
        },
      ],
      10: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'dino_cover',
          textFr: '{{childName}} et le Petit Dinosaure',
          textAr: '{{childName}} وصديقها الديناصور اللطيف',
          textEn: '{{childName}} and the Little Dinosaur',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'dino_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que chaque pas dans la vie soit une aventure grandiose.',
          textAr: 'إلى {{childName}} في عيدها الـ{{childAge}}. ليكن كل يوم في حياتك مغامرة ملؤها النور.',
          textEn: 'For {{childName}}, {{childAge}} years old. May every step you take be filled with grand adventures.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_garden_find',
          textFr: 'Ce samedi-là, {{childName}} construisait un château dans le jardin quand une feuille géante bougea toute seule.',
          textAr: 'في يوم مشمس، كانت {{childName}} تبني بيتاً من الحجارة في الحديقة عندما تحركت ورقة شجر ضخمة فجأة.',
          textEn: 'That sunny morning, {{childName}} was building a play castle when a giant leafy branch began to rustle on its own.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_meet_friend',
          textFr: 'Deux yeux ronds comme des billes dorées apparurent. C’était Titou, le plus mignon des petits dinosaures à collerette.',
          textAr: 'ظهرت عينان عسليتان تلمعان بالبراءة: إنه تيتو، ألطف ديناصور صغير قد تراه عين.',
          textEn: 'Two curious golden eyes peeked out. It was Tito, the sweetest baby dinosaur anyone could ever meet.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_snack_time',
          textFr: '{{childName}} partagea son goûter de pommes croquantes. Titou remua la queue de joie comme un petit chiot préhistorique !',
          textAr: 'اقتسمت {{childName}} تفاحتها الشهية مع تيتو، فهز ذيله فرحاً كأنه جرو صغير مفعم بالنشاط!',
          textEn: '{{childName}} shared a crisp red apple. Tito wagged his tail excitedly just like a prehistoric puppy!',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_valley_walk',
          textFr: '« Mettons-nous en route avant la nuit », dit {{childName}}. Ensemble, ils bravèrent le vent doux de la grande vallée.',
          textAr: '«هيا بنا قبل حلول المساء»، قالت {{childName}}، وسارا معاً بروح المغامرة والتحدي عبر التلال.',
          textEn: '"Let us start our journey before sunset," said {{childName}}. Hand in hand, they marched across the sunlit valley.',
        },
        {
          pageNumber: 7,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'dino_bridge_crossing',
          textFr: 'Pour traverser le grand ravin, {{childName}} guida Titou pas à pas avec patience et réconfort.',
          textAr: 'وعند الممر الصخري الضيق، ساعدت {{childName}} صديقها خطوة بخطوة بكل صبر ورعاية.',
          textEn: 'Carefully guiding each step across the rocky pass, {{childName}} gave Tito reassuring encouragement.',
        },
        {
          pageNumber: 8,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_mom_reunion',
          textFr: 'Soudain, au pied du volcan endormi, sa maman apparut. Quel soulagement et quelle fête pour toute la famille dino !',
          textAr: 'وفجأة، عند سفح الجبل الهادئ، ظهرت والدته لتلتقي بصغيرها وسط مشاعر فرح لا توصف.',
          textEn: 'Suddenly, at the base of the gentle hill, his mother appeared. What relief and happiness for the dinosaur family!',
        },
        {
          pageNumber: 9,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_goodbye_hug',
          textFr: 'Titou fit un gros câlin à {{childName}} en promettant d’être toujours prudent. Les grands yeux du dinosaure brillaient d’amitié.',
          textAr: 'عانق تيتو صديقته {{childName}} بحرارة ووعدها بأن يكون حذراً دائماً، وبقيت الابتسامة تضيء وجهيهما.',
          textEn: 'Tito gave {{childName}} a warm dinosaur hug, promising to always stay close to home. Their friendship was forever sealed.',
        },
        {
          pageNumber: 10,
          layout: 'back_cover',
          sceneIllustrationId: 'dino_back',
          textFr: 'Une histoire personnalisée pour {{childName}}. Le courage commence toujours par un geste de bienveillance. Fin.',
          textAr: 'قصة أطفال مخصصة لأجل {{childName}}. الشجاعة الحقيقية تبدأ دوماً بلمسة لطف. النهاية.',
          textEn: 'A personalized story for {{childName}}. True bravery always begins with an act of kindness. The End.',
        },
      ],
      12: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'dino_cover',
          textFr: '{{childName}} et le Petit Dinosaure',
          textAr: '{{childName}} وصديقها الديناصور اللطيف',
          textEn: '{{childName}} and the Little Dinosaur',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'dino_dedication',
          textFr: 'À notre adorable {{childName}}, {{childAge}} ans. Que ta joie de vivre fasse rugir de bonheur tous ceux qui t’aiment.',
          textAr: 'إلى {{childName}} الحبيبة في عامها الـ{{childAge}}. دامت ابتسامتك المشرقة تنشر البهجة أينما حللتِ.',
          textEn: 'To our darling {{childName}}, {{childAge}} years old. May your joyful spirit brighten every corner of your world.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_garden_find',
          textFr: 'Dans le grand livre d’images de {{childName}}, les dinosaures semblaient si impressionnants.',
          textAr: 'في كتاب الصور الكبير الخاص بـ{{childName}}، كانت الديناصورات تبدو مدهشة ومثيرة للفضول.',
          textEn: 'In {{childName}}’s big picture book, dinosaurs always looked so fascinating and grand.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_meet_friend',
          textFr: 'Mais lorsqu’elle aperçut Titou dans le jardin, elle comprit vite que ce petit bébé avait surtout besoin d’un ami loyal.',
          textAr: 'ولكن عندما رأت تيتو الصغير في الحديقة، أدركت في الحال أنه بحاجة ماسة لصديق مخلص يرعاه.',
          textEn: 'Yet when she saw Tito in the backyard, she immediately saw a gentle baby in need of a loyal friend.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_snack_time',
          textFr: 'Titou adorait les feuilles tendres et les fruits juteux de couleur {{favoriteColor}}. Quel gourmand préhistorique !',
          textAr: 'كان تيتو يعشق أكل أوراق الأشجار الطازجة والفواكه اللذيذة بلون {{favoriteColor}} المفضل لدى {{childName}}.',
          textEn: 'Tito loved tender leaves and juicy berries in {{childName}}’s favorite shade of {{favoriteColor}}.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_valley_walk',
          textFr: 'Équipé{{accord_e}} d’une loupe et d’une gourde, {{childName}} se mit en marche avec Titou trottinant à ses côtés.',
          textAr: 'تسلحت {{childName}} بعدسة مكبرة وقارورة ماء، وسارت بكل عزيمة بينما كان تيتو يهرول بجانبها بمرح.',
          textEn: 'Equipped with a magnifying glass and water bottle, {{childName}} set off with Tito trotting happily alongside.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_bird_help',
          textFr: 'Un gentil ptérodactyle aux ailes soyeuses vola au-dessus d’eux pour leur indiquer la bonne direction au-delà des collines.',
          textAr: 'حلق طائر فضائي أليف فوقهما ليرشدهما إلى الطريق الصحيح نحو موطن الديناصورات العشبية.',
          textEn: 'A friendly flying pterodactyl soared gently above, pointing the right way beyond the emerald hills.',
        },
        {
          pageNumber: 8,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_bridge_crossing',
          textFr: 'Le chemin n’était pas facile, mais {{childName}} savait toujours encourager son petit compagnon avec un mot doux.',
          textAr: 'لم يكن الطريق خالياً من الصعاب، ولكن كلمات {{childName}} المشجعة كانت تمنح تيتو القوة لمواصلة المسير.',
          textEn: 'The path had challenges, but {{childName}}’s cheerful words always gave Tito the courage to press onward.',
        },
        {
          pageNumber: 9,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'dino_mom_reunion',
          textFr: 'Enfin, la maman apparut au coucher du soleil. Les retrouvailles furent pleines de câlins et de tendresse.',
          textAr: 'وأخيراً، أطلت الأم الحنون مع مغيب الشمس، ليكون اللقاء مليئاً بالأحضان الدافئة والامتنان العظيم.',
          textEn: 'At last, Tito’s mother appeared at twilight. The joyful reunion was filled with warm nuzzles and happy cries.',
        },
        {
          pageNumber: 10,
          layout: 'illustration_top',
          sceneIllustrationId: 'dino_goodbye_hug',
          textFr: 'En signe d’amitié éternelle, la maman dinosaure offrit à {{childName}} un fossile poli sculpté en forme de cœur.',
          textAr: 'وكرمز للصداقة الخالدة، أهدت الأم لـ{{childName}} حجراً كريماً مصقولاً على شكل قلب دافئ.',
          textEn: 'As a token of eternal friendship, the mother dinosaur gifted {{childName}} a smooth river stone shaped like a heart.',
        },
        {
          pageNumber: 11,
          layout: 'side_by_side',
          sceneIllustrationId: 'dino_bedtime_calm',
          textFr: 'Rentré{{accord_e}} à la maison, {{childName}} posa le fossile sur sa table de chevet avant de s’endormir avec un grand sourire.',
          textAr: 'عادت {{childName}} إلى غرفتها ووضعت الحجر التذكاري بجانب سريرها، وغفت في نوم عميق وابتسامتها تضيء المكان.',
          textEn: 'Safely home, {{childName}} placed the special stone upon the nightstand, drifting into sweet slumber with a glowing smile.',
        },
        {
          pageNumber: 12,
          layout: 'back_cover',
          sceneIllustrationId: 'dino_back',
          textFr: 'Livre d’histoire créé pour {{childName}}. Sois toujours l’ami{{accord_e}} bienveillant{{accord_e}} dont le monde a besoin. Fin.',
          textAr: 'قصة مميزة كُتبت لأجل {{childName}}. كوني دائماً الصديقة الصادقة التي يحتاجها العالم. النهاية.',
          textEn: 'A storybook crafted for {{childName}}. Always be the gentle, caring friend the world needs. The End.',
        },
      ],
    },
  },

  // 5. LA PETITE ÉTOILE PERDUE
  {
    id: 'lost_little_star',
    titleFr: 'La Petite Étoile Perdue',
    titleAr: 'النجمة الصغيرة التائهة',
    titleEn: 'The Lost Little Star',
    subtitleFr: 'Une douce histoire du soir pour s’endormir paisiblement',
    subtitleAr: 'قصة نوم دافئة تساعد الأطفال على النوم بهدوء وطمأنينة',
    subtitleEn: 'A gentle bedtime story for a peaceful night of sleep',
    descriptionFr: 'Un soir étoilé, une petite étoile filante nommée Stella atterrit doucement sur le balcon de {{childName}}. Ensemble, ils construisent une échelle de nuages pour lui faire retrouver sa constellation.',
    descriptionAr: 'في ليلة مقمرة، تهبط نجمة صغيرة لامعة تدعى ستيلا على شرفة {{childName}}، فتبتكران معاً سلماً من السحب الوردية لتعود النجمة إلى حضن سمائها.',
    descriptionEn: 'On a starry night, a little star named Stella lands on {{childName}}’s balcony. Together they build a ladder of soft clouds to help her return to her constellation.',
    badgeFr: 'Conte du Soir',
    badgeAr: 'قصص ما قبل النوم',
    badgeEn: 'Bedtime Tale',
    themes: ['Empathie', 'Persévérance', 'Sommeil', 'Tendresse'],
    ageMin: 2,
    ageMax: 7,
    colorScheme: {
      primary: '#8b5cf6',
      primaryLight: '#ede9fe',
      primaryDark: '#5b21b6',
      accent: '#facc15',
      badgeBg: '#f5f3ff',
      badgeText: '#7c3aed',
      coverGradient: 'from-violet-800 via-indigo-900 to-slate-950',
    },
    coverIllustrationId: 'star_cover',
    supportedPageCounts: [8, 10, 12],
    pagesByCount: {
      8: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'star_cover',
          textFr: '{{childName}} et la Petite Étoile Perdue',
          textAr: '{{childName}} والنجمة الصغيرة التائهة',
          textEn: '{{childName}} and the Lost Little Star',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'star_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Fais de beaux rêves étoilés. Tu es la plus brillante de nos étoiles.',
          textAr: 'إلى {{childName}}، {{childAge}} سنوات. أحلاماً سعيدة ونوماً هنيئاً يا ألمع نجمة في سمائنا.',
          textEn: 'For {{childName}}, {{childAge}} years old. Sweet starry dreams. You are the brightest star in our lives.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_balcony_fall',
          textFr: 'La lune brillait tout doucement. Assis{{accord_e}} sur son lit en pyjama, {{childName}} aperçut une lueur dorée tomber comme une plume sur le rebord de la fenêtre.',
          textAr: 'كان القمر يبتسم في هدوء الليل. وبينما كانت {{childName}} تستعد للنوم في ثوبها المريح، لمحت ضوءاً ذهبياً يهبط برقة على حافة النافذة.',
          textEn: 'The moon smiled softly through the curtains. Tucked in pajamas, {{childName}} noticed a golden spark drifting down gently onto the windowsill.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_crying_baby',
          textFr: 'C’était Stella, une minuscule étoile aux branches soyeuses. Deux larmes de lumière coulaient sur ses joues : « J’ai trébuché sur un nuage et je ne sais plus remonter là-haut ! »',
          textAr: 'كانت النجمة الصغيرة ستيلا تبكي بدموع من لؤلؤ وضاء: «لقد انزلقتُ من فوق سحابة بيضاء ولا أعرف كيف أعود لأمي في السماء العالية!»',
          textEn: 'It was Stella, a tiny star with velvet tips. Two tears of starlight rolled down her cheeks: "I tumbled off a fluffy cloud and cannot fly back up!"',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_pillow_comfort',
          textFr: '{{childName}} la prit délicatement dans le creux de ses mains : « Sèche tes larmes, Stella. Nous allons demander au Vent du Soir de nous prêter son souffle d’argent. »',
          textAr: 'حملتها {{childName}} برفق وحنان بين كفيها وقالت: «لا تبكي يا ستيلا، سنطلب من نسيم الليل العليل أن يحملك على أجنحته الفضية لتصلي لأحضان السماء».',
          textEn: '{{childName}} cradled the star gently: "Dry your tears, Stella. We will ask the gentle Night Breeze to carry you home on silver wings."',
        },
        {
          pageNumber: 6,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'star_balloon_ascent',
          textFr: '{{childName}} attacha un ruban soyeux de couleur {{favoriteColor}} à un ballon léger en forme de cœur. Stella s’y accrocha avec confiance et s’éleva doucement vers la voûte céleste.',
          textAr: 'ربطت {{childName}} شريطاً حريرياً بلون {{favoriteColor}} ببالون وردي خفيف، فتمسكت به ستيلا وطارت بهدوء نحو النجوم المتلألئة.',
          textEn: '{{childName}} tied a silky ribbon in vibrant {{favoriteColor}} to a soft balloon. Stella held on tightly and drifted upward into the velvety indigo sky.',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_constellation_smile',
          textFr: 'Arrivée dans sa constellation, Stella cligna des yeux avec bonheur. Dès lors, chaque nuit, cette étoile scintille plus fort que les autres en hommage à {{childName}}.',
          textAr: 'وحين استقرت ستيلا في مكانها بين عائلتها النجمية، أخذت تومض بفرح وامتنان لـ{{childName}}، لتضيء غرفتها بأجمل الأنوار كل ليلة.',
          textEn: 'Safely back in her constellation, Stella twinkled with pure joy. Ever since, that star shines brighter than all others to say goodnight to {{childName}}.',
        },
        {
          pageNumber: 8,
          layout: 'back_cover',
          sceneIllustrationId: 'star_back',
          textFr: 'Dors bien, {{childName}}. Les étoiles veillent sur ton sommeil et protègent tes rêves. Fin.',
          textAr: 'نوماً هنيئاً يا {{childName}}. النجوم تحرس نومك وترعى أحلامك الجميلة دائماً. النهاية.',
          textEn: 'Sleep peacefully, {{childName}}. The stars watch over your slumber and cradle your dreams. The End.',
        },
      ],
      10: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'star_cover',
          textFr: '{{childName}} et la Petite Étoile Perdue',
          textAr: '{{childName}} والنجمة الصغيرة التائهة',
          textEn: '{{childName}} and the Lost Little Star',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'star_dedication',
          textFr: 'Pour {{childName}}, {{childAge}} ans. Que chaque nuit soit un voyage tendre au pays des rêves.',
          textAr: 'إلى {{childName}}، {{childAge}} سنوات. دامت لياليكِ عامرة بالسكينة والسلام.',
          textEn: 'For {{childName}}, {{childAge}} years old. May each night be a gentle voyage to dreamland.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_bedroom_calm',
          textFr: 'La maison s’endormait. La veilleuse projetait des ombres douces sur les murs de la chambre de {{childName}}.',
          textAr: 'كان الهدوء يسود البيت، والمصباح الليلي يلقي بظلال دافئة على جدران غرفة {{childName}} الجميلة.',
          textEn: 'The whole house was quiet. A tiny nightlight cast comforting pastel shadows upon {{childName}}’s bedroom walls.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_balcony_fall',
          textFr: 'Un doux tintement, pareil à une clochette d’argent, se fit entendre sur le balcon.',
          textAr: 'رن جرس فضي ناعم خارج الشرفة، كأنه رنة بلور عذبة توقظ الفضول الجميل.',
          textEn: 'A soft chime, like a silver bell, echoed from the balcony ledge.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_crying_baby',
          textFr: '{{childName}} s’approcha sur la pointe des pieds et découvrit Stella qui tremblait de froid.',
          textAr: 'اقتربت {{childName}} على أطراف أصابعها لتجد النجمة ستيلا ترتعش من برد الليل الخفيف.',
          textEn: 'Tiptoeing softly, {{childName}} discovered little Stella shivering in the evening air.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_pillow_comfort',
          textFr: '{{childName}} l’enveloppa dans un mouchoir chaud : « N’aie plus peur, je suis là pour t’aider. »',
          textAr: 'لفتها {{childName}} بقطعة قماش مخملية دافئة: «لا تخافي أبداً، أنا هنا بجانبك».',
          textEn: '{{childName}} wrapped her in a soft warm blanket: "Do not fear, I am right here with you."',
        },
        {
          pageNumber: 7,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'star_cloud_ladder',
          textFr: 'Ensemble, elles empilèrent des coussins et appelèrent les nuages de coton pour former un escalier féerique.',
          textAr: 'معاً، ابتكرتا سلماً من وسائد الريش والسحب القطنية لتبدأ النجمة رحلة الصعود.',
          textEn: 'Together, they stacked cozy pillows and called upon puffy clouds to form a staircase to the stars.',
        },
        {
          pageNumber: 8,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_balloon_ascent',
          textFr: 'Portée par une brise bienveillante, Stella monta marche après marche vers la Grande Ourse.',
          textAr: 'وبمساعدة نسمات الليل، صعدت ستيلا درجة بعد أخرى نحو كوكبتها الحبيبة بأمان.',
          textEn: 'Carried by the gentle breeze, Stella stepped upward towards the Big Dipper.',
        },
        {
          pageNumber: 9,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_constellation_smile',
          textFr: 'Depuis le ciel, Stella envoya une pluie d’étincelles dorées pour border {{childName}} de tendresse.',
          textAr: 'ومن أعلى السماء، نثرت ستيلا ذرات من الضوء الذهبي لتبارك نوم {{childName}} الهادئ.',
          textEn: 'From high above, Stella showered golden sparks to tuck {{childName}} into bed with tenderness.',
        },
        {
          pageNumber: 10,
          layout: 'back_cover',
          sceneIllustrationId: 'star_back',
          textFr: 'Fais de beaux rêves, {{childName}}. Que la nuit t’apporte réconfort et sérénité. Fin.',
          textAr: 'أحلاماً هنيئة يا {{childName}}. لتكن ليلتك عامرة بالطمأنينة والنور. النهاية.',
          textEn: 'Sweet dreams, {{childName}}. May the night bring you comfort and serenity. The End.',
        },
      ],
      12: [
        {
          pageNumber: 1,
          layout: 'cover_hero',
          sceneIllustrationId: 'star_cover',
          textFr: '{{childName}} et la Petite Étoile Perdue',
          textAr: '{{childName}} والنجمة الصغيرة التائهة',
          textEn: '{{childName}} and the Lost Little Star',
        },
        {
          pageNumber: 2,
          layout: 'dedication_page',
          sceneIllustrationId: 'star_dedication',
          textFr: 'À {{childName}}, {{childAge}} ans. Que ta bonté continue d’illuminer le cœur de ceux qui t’entourent.',
          textAr: 'إلى {{childName}} في عيدها الـ{{childAge}}. ليبقَ قلبك الطيب مصباحاً ينير دروب كل من يحبك.',
          textEn: 'To {{childName}}, {{childAge}} years old. May your kindness always brighten the hearts of those around you.',
        },
        {
          pageNumber: 3,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_bedroom_calm',
          textFr: 'La lune veillait sur la ville silencieuse tandis que les étoiles jouaient à cache-cache.',
          textAr: 'كان القمر يحرس المدينة الهادئة، والنجوم في السماء تداعب السحب بنورها الدافئ.',
          textEn: 'The moon watched over the quiet town while stars played peek-a-boo between the clouds.',
        },
        {
          pageNumber: 4,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_balcony_fall',
          textFr: 'Soudain, une étoile filante traversa l’obscurité pour se poser sur le rebord de la fenêtre de {{childName}}.',
          textAr: 'وفجأة، عبر شهاب لامع عتمة الليل ليهبط برفق على نافذة غرفة {{childName}}.',
          textEn: 'Suddenly, a shooting star glided across the dark sky, landing softly upon {{childName}}’s window.',
        },
        {
          pageNumber: 5,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_crying_baby',
          textFr: 'C’était Stella, une petite étoile tombée du ciel pendant la grande danse céleste.',
          textAr: 'كانت ستيلا، نجمة صغيرة سقطت أثناء رقصة الشهب الصيفية، ولم تعد قادرة على الطيران.',
          textEn: 'It was Stella, a baby star who had slipped during the great celestial dance.',
        },
        {
          pageNumber: 6,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_pillow_comfort',
          textFr: '{{childName}} la réconforta : « Ne t’inquiète pas, nous allons trouver une solution ensemble ! »',
          textAr: 'طمأنتها {{childName}} بحنان: «لا تحزني، سنصل معاً إلى فكرة رائعة تعيدك إلى السماء!»',
          textEn: '{{childName}} comforted her: "Do not worry, we will find a way back home together!"',
        },
        {
          pageNumber: 7,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_cloud_ladder',
          textFr: '{{childName}} dessina un plan d’envol avec ses crayons dorés et confectionna une nacelle de soie.',
          textAr: 'رسمت {{childName}} خطة طيران بألوانها الزاهية وصنعت مظلة حريرية خفيفة الوزن.',
          textEn: '{{childName}} drew a flight blueprint with golden crayons, fashioning a silk parachute basket.',
        },
        {
          pageNumber: 8,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_balloon_ascent',
          textFr: 'Le grand Hibou nocturne vint prêter ses ailes pour hisser la petite étoile jusqu’au premier nuage.',
          textAr: 'جاء البوم الحكيم ليساعد بجناحيه القويين في رفع النجمة إلى أول سحابة في السماء.',
          textEn: 'The wise night owl flew in to offer his feathers, lifting the little star to the first cloud.',
        },
        {
          pageNumber: 9,
          layout: 'full_illustration_badge',
          sceneIllustrationId: 'star_constellation_smile',
          textFr: 'De nuage en nuage, Stella reprit de la vitesse et bondit joyeusement dans sa constellation.',
          textAr: 'ومن سحابة إلى سحابة، استعادت ستيلا نورها وقفزت إلى مكانها بين إخوتها النجوم.',
          textEn: 'Leaping from cloud to cloud, Stella regained her glow, jumping right into her constellation.',
        },
        {
          pageNumber: 10,
          layout: 'illustration_top',
          sceneIllustrationId: 'star_night_sky_glow',
          textFr: 'Toute la voûte céleste s’illumina d’une clarté féerique en remerciement à {{childName}}.',
          textAr: 'أضاءت السماء كلها بنور ساحر تعبيراً عن امتنان النجوم لـ{{childName}} وذكائها النبيل.',
          textEn: 'The entire night sky glowed with a magnificent shimmer in gratitude to {{childName}}.',
        },
        {
          pageNumber: 11,
          layout: 'side_by_side',
          sceneIllustrationId: 'star_bedtime_calm',
          textFr: 'Baigné{{accord_e}} de cette douce lumière, {{childName}} glissa sous sa couette, les yeux mi-clos et le cœur en paix.',
          textAr: 'في ذلك الضوء الحنون، دخلت {{childName}} تحت غطائها الدافئ ونامت بسلام واطمئنان.',
          textEn: 'Bathed in gentle starlight, {{childName}} slid under the cozy duvet with quiet joy.',
        },
        {
          pageNumber: 12,
          layout: 'back_cover',
          sceneIllustrationId: 'star_back',
          textFr: 'Bonne nuit {{childName}}. Que les étoiles éclairent toujours le chemin de tes plus beaux songes. Fin.',
          textAr: 'تصبحي على خير يا {{childName}}. لتكن النجوم دوماً دليلك في طريق الأحلام الوردية. النهاية.',
          textEn: 'Goodnight {{childName}}. May the stars forever illuminate the path of your sweetest dreams. The End.',
        },
      ],
    },
  },
];

// Helper to get a template by ID
export function getStoryTemplateById(id: string): StoryTemplate {
  return STORY_TEMPLATES.find((t) => t.id === id) || STORY_TEMPLATES[0];
}
