import { KawaiiTheme, KawaiiThemeId } from '../../types/stationery';

export const KAWAII_THEMES: Record<KawaiiThemeId, KawaiiTheme> = {
  peachy_dreams: {
    id: 'peachy_dreams',
    name: 'Peachy Dreams',
    nameFr: 'Rêverie de Pêche',
    nameAr: 'أحلام الخوخ اللطيفة',
    description: 'Soft peach and cream palette. Cute smiling peaches, tiny leaves, delicate flowers and pastel warmth.',
    descriptionFr: 'Pêches souriantes, petites feuilles dorées, fleurs pastel et douceur fruitée.',
    primaryColor: '#F97316',
    secondaryColor: '#FB923C',
    accentColor: '#FDBA74',
    lineColor: '#FDBA74',
    bgTint: '#FFF7ED',
    badgeBg: '#FFEDD5',
    borderColor: '#FED7AA',
    mascotEmoji: '🍑',
    keywords: ['peach', 'fruit', 'warm', 'cream', 'delicate'],
  },
  hamster_paradise: {
    id: 'hamster_paradise',
    name: 'Hamster Paradise',
    nameFr: 'Paradis des Hamsters',
    nameAr: 'جنة الهامستر اللطيف',
    description: 'Cute hamsters, tiny snacks, soft beige and pastel brown. Playful and cozy stationery.',
    descriptionFr: 'Petits hamsters malicieux, graines gourmandes, tons beiges et noisette réconfortants.',
    primaryColor: '#B45309',
    secondaryColor: '#D97706',
    accentColor: '#FDE68A',
    lineColor: '#FDE68A',
    bgTint: '#FEFCE8',
    badgeBg: '#FEF3C7',
    borderColor: '#FDE68A',
    mascotEmoji: '🐹',
    keywords: ['hamster', 'cozy', 'beige', 'snack'],
  },
  bunny_garden: {
    id: 'bunny_garden',
    name: 'Bunny Garden',
    nameFr: 'Jardin des Lapinous',
    nameAr: 'حديقة الأرانب والزهور',
    description: 'Adorable rabbits, small flowers, butterflies and soft pastel greenery. Gentle spring vibe.',
    descriptionFr: 'Lapins aux grandes oreilles, pâquerettes printanières, papillons et vert d’eau pastel.',
    primaryColor: '#059669',
    secondaryColor: '#10B981',
    accentColor: '#A7F3D0',
    lineColor: '#A7F3D0',
    bgTint: '#F0FDF4',
    badgeBg: '#D1FAE5',
    borderColor: '#A7F3D0',
    mascotEmoji: '🐰',
    keywords: ['rabbit', 'bunny', 'flower', 'garden', 'green'],
  },
  strawberry_milk: {
    id: 'strawberry_milk',
    name: 'Strawberry Milk',
    nameFr: 'Lait Fraise Kawaii',
    nameAr: 'حليب الفراولة الوردي',
    description: 'Pastel pink, juicy strawberries, milk cartons and hearts. Authentic Japanese stationery spirit.',
    descriptionFr: 'Fraises croquantes, briques de lait rétro japonaises, cœurs doux et rose poudré.',
    primaryColor: '#E11D48',
    secondaryColor: '#FB7185',
    accentColor: '#FECDD3',
    lineColor: '#FECDD3',
    bgTint: '#FFF1F2',
    badgeBg: '#FFE4E6',
    borderColor: '#FECDD3',
    mascotEmoji: '🍓',
    keywords: ['strawberry', 'milk', 'pink', 'japan', 'heart'],
  },
  cloudy_sky: {
    id: 'cloudy_sky',
    name: 'Cloudy Sky',
    nameFr: 'Ciel Nuageux & Étoiles',
    nameAr: 'سماء الغيوم والنجوم',
    description: 'Smiling clouds, tiny stars, soft dreamy blue and lavender. Serene and peaceful.',
    descriptionFr: 'Petits nuages bienveillants, étoiles scintillantes, bleu ciel et lavande apaisante.',
    primaryColor: '#0284C7',
    secondaryColor: '#38BDF8',
    accentColor: '#BAE6FD',
    lineColor: '#BAE6FD',
    bgTint: '#F0F9FF',
    badgeBg: '#E0F2FE',
    borderColor: '#BAE6FD',
    mascotEmoji: '☁️',
    keywords: ['cloud', 'sky', 'stars', 'dream', 'blue'],
  },
  little_panda: {
    id: 'little_panda',
    name: 'Little Panda',
    nameFr: 'Petit Panda & Bambou',
    nameAr: 'الباندا الصغير والخيزران',
    description: 'Cute pandas, fresh bamboo leaves, soft sage green and cream. Minimalist and expressive.',
    descriptionFr: 'Pandas joueurs, pousses de bambou fraîches, vert sauge et écru naturel.',
    primaryColor: '#15803D',
    secondaryColor: '#22C55E',
    accentColor: '#BBF7D0',
    lineColor: '#BBF7D0',
    bgTint: '#F0FDF4',
    badgeBg: '#DCFCE7',
    borderColor: '#BBF7D0',
    mascotEmoji: '🐼',
    keywords: ['panda', 'bamboo', 'green', 'minimal'],
  },
  cherry_blossom: {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    nameFr: 'Fleur de Cerisier Sakura',
    nameAr: 'أزهار الكرز الساكورا',
    description: 'Delicate sakura flowers, petals drifting in the wind, soft pink, cream and refined branches.',
    descriptionFr: 'Pétales de sakura en vol, branches fines traditionnelles, nuances poudrées raffinées.',
    primaryColor: '#DB2777',
    secondaryColor: '#F472B6',
    accentColor: '#FBCFE8',
    lineColor: '#FBCFE8',
    bgTint: '#FDF2F8',
    badgeBg: '#FCE7F3',
    borderColor: '#FBCFE8',
    mascotEmoji: '🌸',
    keywords: ['sakura', 'cherry', 'blossom', 'japan', 'pink'],
  },
  kitty_cafe: {
    id: 'kitty_cafe',
    name: 'Kitty Café',
    nameFr: 'Café des Chatons',
    nameAr: 'مقهى القطط الدافئ',
    description: 'Original cute kitten characters, hot cocoa cups, cookies and warm pastel café tones.',
    descriptionFr: 'Chatons mignons, tasses de chocolat chaud fumantes, biscuits et ambiance salon de thé.',
    primaryColor: '#9333EA',
    secondaryColor: '#C084FC',
    accentColor: '#E9D5FF',
    lineColor: '#E9D5FF',
    bgTint: '#FAF5FF',
    badgeBg: '#F3E8FF',
    borderColor: '#E9D5FF',
    mascotEmoji: '🐱',
    keywords: ['cat', 'cafe', 'coffee', 'cookie', 'cozy'],
  },
  ocean_friends: {
    id: 'ocean_friends',
    name: 'Ocean Friends',
    nameFr: 'Les Amis de l’Océan',
    nameAr: 'أصدقاء المحيط اللطيفون',
    description: 'Cute baby whales, gentle sea turtles, tiny bubbles and refreshing turquoise waters.',
    descriptionFr: 'Bébés baleines joyeuses, tortues de mer paisibles, coquillages et turquoise lagon.',
    primaryColor: '#0D9488',
    secondaryColor: '#2DD4BF',
    accentColor: '#99F6E4',
    lineColor: '#99F6E4',
    bgTint: '#F0FDFA',
    badgeBg: '#CCFBF1',
    borderColor: '#99F6E4',
    mascotEmoji: '🐳',
    keywords: ['whale', 'ocean', 'sea', 'turtle', 'turquoise'],
  },
  little_duck: {
    id: 'little_duck',
    name: 'Little Duck',
    nameFr: 'Caneton Joyeux',
    nameAr: 'البطة الصفراء الصغيرة',
    description: 'Cheerful yellow ducklings, tiny daisies, soft sky blue and warm sunshine yellow.',
    descriptionFr: 'Petits canetons jaunes, marguerites des prés, gouttelettes et jaune ensoleillé.',
    primaryColor: '#CA8A04',
    secondaryColor: '#FACC15',
    accentColor: '#FEF08A',
    lineColor: '#FEF08A',
    bgTint: '#FEFCE8',
    badgeBg: '#FEF9C3',
    borderColor: '#FEF08A',
    mascotEmoji: '🐥',
    keywords: ['duck', 'yellow', 'sunshine', 'flower'],
  },
  magic_unicorn: {
    id: 'magic_unicorn',
    name: 'Magic Unicorn',
    nameFr: 'Licorne Enchantée',
    nameAr: 'وحيد القرن السحري',
    description: 'Delicate unicorn silhouettes, pastel rainbows, sparkling stardust and soft lilac dreams.',
    descriptionFr: 'Licornes féeriques, arcs-en-ciel pastels, poussière d’étoiles et lilas magique.',
    primaryColor: '#7C3AED',
    secondaryColor: '#A855F7',
    accentColor: '#DDD6FE',
    lineColor: '#DDD6FE',
    bgTint: '#F5F3FF',
    badgeBg: '#EDE9FE',
    borderColor: '#DDD6FE',
    mascotEmoji: '🦄',
    keywords: ['unicorn', 'magic', 'rainbow', 'purple', 'star'],
  },
  cozy_study: {
    id: 'cozy_study',
    name: 'Cozy Study',
    nameFr: 'Atelier Étude & Papeterie',
    nameAr: 'ركن المذاكرة والقرطاسية',
    description: 'Pencil shavings, books, warm tea, cute desk companions. Perfect for students and planner lovers.',
    descriptionFr: 'Piles de livres soignés, crayons taillés, sabliers, thé tiède et esprit studieux.',
    primaryColor: '#475569',
    secondaryColor: '#64748B',
    accentColor: '#CBD5E1',
    lineColor: '#CBD5E1',
    bgTint: '#F8FAFC',
    badgeBg: '#F1F5F9',
    borderColor: '#E2E8F0',
    mascotEmoji: '📚',
    keywords: ['study', 'book', 'pencil', 'student', 'planner'],
  },
};
