import { BirthdayThemeDefinition, BirthdayThemeId } from '../types/birthdayKit';

export const BIRTHDAY_THEMES: BirthdayThemeDefinition[] = [
  {
    id: 'magical_unicorn',
    name: {
      fr: 'Licorne Magique',
      ar: 'وحيد القرن السحري',
      en: 'Magical Unicorn',
    },
    subtitle: {
      fr: 'Nuages pastel, arcs-en-ciel, étoiles scintillantes & douceur féerique',
      ar: 'غيوم ناعمة، قوس قزح، نجوم برّاقة وأجواء خيالية',
      en: 'Pastel clouds, rainbows, twinkling stars & magical dreamland',
    },
    badgeColor: 'bg-pink-100 text-pink-700 border-pink-200',
    primaryColor: '#EC4899',
    secondaryColor: '#A855F7',
    accentColor: '#F472B6',
    bgColor: '#FDF2F8',
    cardBg: '#FFF1F2',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    illustrationKey: 'unicorn',
    emoji: '🦄',
  },
  {
    id: 'dinosaur_adventure',
    name: {
      fr: 'Aventure Dinosaures',
      ar: 'مغامرة الديناصورات',
      en: 'Dinosaur Adventure',
    },
    subtitle: {
      fr: 'Dinosaures rigolos, feuilles tropicales, empreintes préhistoriques',
      ar: 'ديناصورات لطيفة، أوراق استوائية وآثار أقدام أثرية',
      en: 'Friendly dinos, jungle leaves & fossil footprints',
    },
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    primaryColor: '#059669',
    secondaryColor: '#D97706',
    accentColor: '#10B981',
    bgColor: '#ECFDF5',
    cardBg: '#F0FDF4',
    borderColor: '#A7F3D0',
    textColor: '#064E3B',
    illustrationKey: 'dino',
    emoji: '🦖',
  },
  {
    id: 'space_explorer',
    name: {
      fr: 'Explorateur Spatial',
      ar: 'مستكشف الفضاء',
      en: 'Space Explorer',
    },
    subtitle: {
      fr: 'Fusées cosmiques, planètes lointaines, constellations et galaxies',
      ar: 'صواريخ فضائية، كواكب ملونة، نجوم ومجرات بعيدة',
      en: 'Cosmic rockets, glowing planets & starry galaxies',
    },
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    primaryColor: '#4F46E5',
    secondaryColor: '#06B6D4',
    accentColor: '#6366F1',
    bgColor: '#EEF2FF',
    cardBg: '#F5F3FF',
    borderColor: '#C7D2FE',
    textColor: '#1E1B4B',
    illustrationKey: 'space',
    emoji: '🚀',
  },
  {
    id: 'princess_garden',
    name: {
      fr: 'Jardin des Princesses',
      ar: 'حديقة الأميرات',
      en: 'Princess Garden',
    },
    subtitle: {
      fr: 'Château enchanté, couronnes dorées, papillons et fleurs royales',
      ar: 'قصر ساحر، تيجان ذهبية، فراشات وزهور ملكية',
      en: 'Enchanted castle, golden crowns, butterflies & royal blooms',
    },
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-200',
    primaryColor: '#E11D48',
    secondaryColor: '#D97706',
    accentColor: '#FB7185',
    bgColor: '#FFF1F2',
    cardBg: '#FFFBEB',
    borderColor: '#FECDD3',
    textColor: '#881337',
    illustrationKey: 'princess',
    emoji: '👑',
  },
  {
    id: 'jungle_safari',
    name: {
      fr: 'Safari dans la Jungle',
      ar: 'سفاري الغابة والأدغال',
      en: 'Jungle Safari',
    },
    subtitle: {
      fr: 'Petits lions, girafes rieuses, singes espiègles et grandes feuilles',
      ar: 'أسود صغيرة، زرافات لطيفة، قرود مرحة ونباتات خضراء',
      en: 'Cute baby lions, happy giraffes, cheeky monkeys & palm leaves',
    },
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    primaryColor: '#D97706',
    secondaryColor: '#16A34A',
    accentColor: '#F59E0B',
    bgColor: '#FFFBEB',
    cardBg: '#FEF3C7',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    illustrationKey: 'safari',
    emoji: '🦁',
  },
  {
    id: 'ocean_adventure',
    name: {
      fr: 'Aventure Océanique',
      ar: 'عالم البحار والمحيطات',
      en: 'Ocean Adventure',
    },
    subtitle: {
      fr: 'Baleines joyeuses, tortues marines, coraux et coquillages nacrés',
      ar: 'حيتان زرقاء، سلاحف بحرية، أسماك وشعب مرجانية لطيفة',
      en: 'Friendly blue whales, sea turtles, corals & seashell treasures',
    },
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    primaryColor: '#0891B2',
    secondaryColor: '#3B82F6',
    accentColor: '#06B6D4',
    bgColor: '#ECFEFF',
    cardBg: '#F0F9FF',
    borderColor: '#A5F3FC',
    textColor: '#164E63',
    illustrationKey: 'ocean',
    emoji: '🐳',
  },
  {
    id: 'teddy_bear_party',
    name: {
      fr: 'Fête des Oursons',
      ar: 'حفل الدببة اللطيفة',
      en: 'Teddy Bear Party',
    },
    subtitle: {
      fr: 'Oursons en peluche, ballons dorés, paquets cadeaux chaleureux',
      ar: 'دباديب ناعمة، بالونات دافئة وصناديق هدايا جميلة',
      en: 'Cuddly teddy bears, golden balloons & cozy gift boxes',
    },
    badgeColor: 'bg-orange-100 text-orange-800 border-orange-200',
    primaryColor: '#C2410C',
    secondaryColor: '#EAB308',
    accentColor: '#EA580C',
    bgColor: '#FFF7ED',
    cardBg: '#FEF3C7',
    borderColor: '#FED7AA',
    textColor: '#7C2D12',
    illustrationKey: 'teddy',
    emoji: '🧸',
  },
  {
    id: 'rainbow_birthday',
    name: {
      fr: 'Fête Arc-en-Ciel',
      ar: 'عيد ميلاد قوس قزح',
      en: 'Rainbow Birthday',
    },
    subtitle: {
      fr: 'Arcs-en-ciel vifs, soleils souriants, confettis festifs et joie',
      ar: 'أقواس قزح زاهية، شموس ضاحكة، قصاصات ورق ملونة وأفراح',
      en: 'Vibrant rainbows, smiling sunbeams, festive confetti & pure joy',
    },
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    primaryColor: '#7C3AED',
    secondaryColor: '#F59E0B',
    accentColor: '#8B5CF6',
    bgColor: '#F5F3FF',
    cardBg: '#EDE9FE',
    borderColor: '#DDD6FE',
    textColor: '#4C1D95',
    illustrationKey: 'rainbow',
    emoji: '🌈',
  },
  {
    id: 'cute_animals',
    name: {
      fr: 'Animaux Kawaii',
      ar: 'حيوانات كواي اللطيفة',
      en: 'Cute Animals Kawaii',
    },
    subtitle: {
      fr: 'Lapins, chatons et chiots coiffés de chapeaux de fête colorés',
      ar: 'أرانب وقطط وجراء ترتدي قبعات عيد ميلاد ملونة ومرحة',
      en: 'Bunnies, kittens & puppies wearing party hats with confetti',
    },
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-200',
    primaryColor: '#0D9488',
    secondaryColor: '#EC4899',
    accentColor: '#14B8A6',
    bgColor: '#F0FDFA',
    cardBg: '#CCFBF1',
    borderColor: '#99F6E4',
    textColor: '#134E4A',
    illustrationKey: 'kawaii_animals',
    emoji: '🐰',
  },
  {
    id: 'football_party',
    name: {
      fr: 'Champion de Football',
      ar: 'بطل كرة القدم',
      en: 'Football Party',
    },
    subtitle: {
      fr: 'Ballons ronds, trophée doré, drapeaux et ambiance de grand match',
      ar: 'كرات قدم، كؤوس ذهبية، رايات وأجواء الملعب الاحتفالية',
      en: 'Soccer balls, golden victory cups, team banners & stadium cheers',
    },
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    primaryColor: '#15803D',
    secondaryColor: '#EAB308',
    accentColor: '#22C55E',
    bgColor: '#F0FDF4',
    cardBg: '#DCFCE7',
    borderColor: '#BBF7D0',
    textColor: '#14532D',
    illustrationKey: 'football',
    emoji: '⚽',
  },
  {
    id: 'construction_party',
    name: {
      fr: 'Chantier & Engins',
      ar: 'حفلة الشاحنات والبناء',
      en: 'Construction Party',
    },
    subtitle: {
      fr: 'Pelleteuses, camions bennes, cônes de signalisation et briques',
      ar: 'شاحنات وجرافات صفراء، أقماع مرورية وقوالب بناء ممتعة',
      en: 'Excavators, dump trucks, safety cones & playful builders',
    },
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    primaryColor: '#D97706',
    secondaryColor: '#1F2937',
    accentColor: '#F59E0B',
    bgColor: '#FFFBEB',
    cardBg: '#FEF3C7',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    illustrationKey: 'construction',
    emoji: '🚜',
  },
  {
    id: 'candy_cupcake',
    name: {
      fr: 'Bonbons & Cupcakes',
      ar: 'حفلة الحلوى والكب كيك',
      en: 'Candy & Cupcake Party',
    },
    subtitle: {
      fr: 'Cupcakes givrés, sucettes multicolores, fraises et friandises',
      ar: 'كب كيك ملون، مصاصات سكرية، فراولة وحلويات لذيذة',
      en: 'Frosted cupcakes, rainbow lollipops, sweet strawberries & treats',
    },
    badgeColor: 'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
    primaryColor: '#C026D3',
    secondaryColor: '#F43F5E',
    accentColor: '#D946EF',
    bgColor: '#FDF4FF',
    cardBg: '#FAE8FF',
    borderColor: '#F5D0FE',
    textColor: '#701A75',
    illustrationKey: 'sweets',
    emoji: '🧁',
  },
];

export function getBirthdayTheme(themeId: BirthdayThemeId): BirthdayThemeDefinition {
  return (
    BIRTHDAY_THEMES.find((t) => t.id === themeId) || BIRTHDAY_THEMES[0]
  );
}
