import { ThemeDefinition, NotebookSubject, ColorPalette, IllustrationDefinition } from '../types';

export const GENERAL_THEMES: ThemeDefinition[] = [
  {
    id: 'cute',
    name: { fr: 'Cute Pastel', ar: 'Cute Pastel', en: 'Cute Pastel' },
    icon: '🌸',
    category: 'general',
    primaryColor: '#EC4899',
    secondaryColor: '#FDF2F8',
    accentColor: '#F472B6',
    bgColor: '#FFF5F9',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
    illustrationType: 'cute_bear',
    previewThumbnail: '🌸',
  },
  {
    id: 'dino',
    name: { fr: 'Dino Adventure', ar: 'Dino Adventure', en: 'Dino Adventure' },
    icon: '🦖',
    category: 'general',
    primaryColor: '#059669',
    secondaryColor: '#ECFDF5',
    accentColor: '#10B981',
    bgColor: '#F0FDF4',
    borderColor: '#A7F3D0',
    textColor: '#064E3B',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
    illustrationType: 'dino',
    previewThumbnail: '🦖',
  },
  {
    id: 'space',
    name: { fr: 'Space Explorer', ar: 'Space Explorer', en: 'Space Explorer' },
    icon: '🚀',
    category: 'general',
    primaryColor: '#2563EB',
    secondaryColor: '#EFF6FF',
    accentColor: '#F59E0B',
    bgColor: '#F0F9FF',
    borderColor: '#BAE6FD',
    textColor: '#0C4A6E',
    badgeBg: '#E0F2FE',
    badgeText: '#0369A1',
    illustrationType: 'space_rocket',
    previewThumbnail: '🚀',
  },
  {
    id: 'football',
    name: { fr: 'Football Fun', ar: 'Football Fun', en: 'Football Fun' },
    icon: '⚽',
    category: 'general',
    primaryColor: '#1D4ED8',
    secondaryColor: '#EFF6FF',
    accentColor: '#10B981',
    bgColor: '#F8FAFC',
    borderColor: '#BFDBFE',
    textColor: '#1E3A8A',
    badgeBg: '#DBEAFE',
    badgeText: '#1D4ED8',
    illustrationType: 'football',
    previewThumbnail: '⚽',
  },
  {
    id: 'unicorn',
    name: { fr: 'Magical Unicorn', ar: 'Magical Unicorn', en: 'Magical Unicorn' },
    icon: '🦄',
    category: 'general',
    primaryColor: '#9333EA',
    secondaryColor: '#FAF5FF',
    accentColor: '#EC4899',
    bgColor: '#FDF4FF',
    borderColor: '#E9D5FF',
    textColor: '#581C87',
    badgeBg: '#F3E8FF',
    badgeText: '#6B21A8',
    illustrationType: 'unicorn',
    previewThumbnail: '🦄',
  },
  {
    id: 'rainbow',
    name: { fr: 'Rainbow World', ar: 'Rainbow World', en: 'Rainbow World' },
    icon: '🌈',
    category: 'general',
    primaryColor: '#D97706',
    secondaryColor: '#FFFBEB',
    accentColor: '#06B6D4',
    bgColor: '#FFFDF5',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
    illustrationType: 'rainbow',
    previewThumbnail: '🌈',
  },
  {
    id: 'animals',
    name: { fr: 'Animal Friends', ar: 'Animal Friends', en: 'Animal Friends' },
    icon: '🧸',
    category: 'general',
    primaryColor: '#B45309',
    secondaryColor: '#FFFBEB',
    accentColor: '#84CC16',
    bgColor: '#FDFCF7',
    borderColor: '#FED7AA',
    textColor: '#451A03',
    badgeBg: '#FFEDD5',
    badgeText: '#9A3412',
    illustrationType: 'animals',
    previewThumbnail: '🧸',
  },
  {
    id: 'gamer',
    name: { fr: 'Gamer Kids', ar: 'Gamer Kids', en: 'Gamer Kids' },
    icon: '🎮',
    category: 'general',
    primaryColor: '#7C3AED',
    secondaryColor: '#F5F3FF',
    accentColor: '#06B6D4',
    bgColor: '#FAF5FF',
    borderColor: '#DDD6FE',
    textColor: '#4C1D95',
    badgeBg: '#EDE9FE',
    badgeText: '#6D28D9',
    illustrationType: 'gamer',
    previewThumbnail: '🎮',
  },
  {
    id: 'superhero',
    name: { fr: 'Super Hero', ar: 'Super Hero', en: 'Super Hero' },
    icon: '🦸',
    category: 'general',
    primaryColor: '#DC2626',
    secondaryColor: '#FEF2F2',
    accentColor: '#EAB308',
    bgColor: '#FFF5F5',
    borderColor: '#FECACA',
    textColor: '#7F1D1D',
    badgeBg: '#FEE2E2',
    badgeText: '#991B1B',
    illustrationType: 'superhero',
    previewThumbnail: '🦸',
  },
  {
    id: 'cars',
    name: { fr: 'Little Cars', ar: 'Little Cars', en: 'Little Cars' },
    icon: '🚗',
    category: 'general',
    primaryColor: '#E11D48',
    secondaryColor: '#FFF1F2',
    accentColor: '#F59E0B',
    bgColor: '#FAFAFA',
    borderColor: '#FECDD3',
    textColor: '#881337',
    badgeBg: '#FFE4E6',
    badgeText: '#9F1239',
    illustrationType: 'cars',
    previewThumbnail: '🚗',
  },
  {
    id: 'jurassic',
    name: { fr: 'Jurassic World', ar: 'Jurassic World', en: 'Jurassic World' },
    icon: '🦖',
    category: 'general',
    primaryColor: '#15803D',
    secondaryColor: '#F0FDF4',
    accentColor: '#CA8A04',
    bgColor: '#F7FEE7',
    borderColor: '#BBF7D0',
    textColor: '#14532D',
    badgeBg: '#DCFCE7',
    badgeText: '#166534',
    illustrationType: 'jurassic',
    previewThumbnail: '🦖',
  },
  {
    id: 'candy',
    name: { fr: 'Sweet Candy', ar: 'Sweet Candy', en: 'Sweet Candy' },
    icon: '🧁',
    category: 'general',
    primaryColor: '#DB2777',
    secondaryColor: '#FDF2F8',
    accentColor: '#A855F7',
    bgColor: '#FFF5F9',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
    illustrationType: 'candy',
    previewThumbnail: '🧁',
  },
  {
    id: 'ocean',
    name: { fr: 'Ocean Adventure', ar: 'Ocean Adventure', en: 'Ocean Adventure' },
    icon: '🌊',
    category: 'general',
    primaryColor: '#0284C7',
    secondaryColor: '#F0F9FF',
    accentColor: '#14B8A6',
    bgColor: '#F0FDFF',
    borderColor: '#BAE6FD',
    textColor: '#075985',
    badgeBg: '#E0F2FE',
    badgeText: '#0369A1',
    illustrationType: 'ocean',
    previewThumbnail: '🌊',
  },
  {
    id: 'pirate',
    name: { fr: 'Pirate Adventure', ar: 'Pirate Adventure', en: 'Pirate Adventure' },
    icon: '🏴‍☠️',
    category: 'general',
    primaryColor: '#475569',
    secondaryColor: '#F8FAFC',
    accentColor: '#D97706',
    bgColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    textColor: '#1E293B',
    badgeBg: '#E2E8F0',
    badgeText: '#0F172A',
    illustrationType: 'pirate',
    previewThumbnail: '🏴‍☠️',
  },
  {
    id: 'nature',
    name: { fr: 'Nature Explorer', ar: 'Nature Explorer', en: 'Nature Explorer' },
    icon: '🌳',
    category: 'general',
    primaryColor: '#16A34A',
    secondaryColor: '#F0FDF4',
    accentColor: '#EAB308',
    bgColor: '#FAFAF9',
    borderColor: '#B7E4C7',
    textColor: '#14532D',
    badgeBg: '#DCFCE7',
    badgeText: '#15803D',
    illustrationType: 'nature',
    previewThumbnail: '🌳',
  },
];

export const SUBJECT_THEMES: Record<NotebookSubject, ThemeDefinition[]> = {
  math: [
    {
      id: 'math_cute',
      name: { fr: 'Cute Math', ar: 'رياضيات مرحة', en: 'Cute Math' },
      icon: '📐',
      category: 'math',
      primaryColor: '#2563EB',
      secondaryColor: '#EFF6FF',
      accentColor: '#F59E0B',
      bgColor: '#F8FAFC',
      borderColor: '#93C5FD',
      textColor: '#1E3A8A',
      badgeBg: '#DBEAFE',
      badgeText: '#1D4ED8',
      illustrationType: 'math_cute',
      previewThumbnail: '📐',
    },
    {
      id: 'math_numbers',
      name: { fr: 'Numbers & Digits', ar: 'أرقام وحساب', en: 'Numbers & Digits' },
      icon: '🔢',
      category: 'math',
      primaryColor: '#0D9488',
      secondaryColor: '#F0FDFA',
      accentColor: '#F97316',
      bgColor: '#F8FAFC',
      borderColor: '#99F6E4',
      textColor: '#115E59',
      badgeBg: '#CCFBF1',
      badgeText: '#0F766E',
      illustrationType: 'math_numbers',
      previewThumbnail: '🔢',
    },
    {
      id: 'math_geometry',
      name: { fr: 'Geometry & Shapes', ar: 'هندسة وأشكال', en: 'Geometry & Shapes' },
      icon: '📏',
      category: 'math',
      primaryColor: '#7C3AED',
      secondaryColor: '#FAF5FF',
      accentColor: '#EC4899',
      bgColor: '#FAFAFA',
      borderColor: '#C4B5FD',
      textColor: '#5B21B6',
      badgeBg: '#EDE9FE',
      badgeText: '#6D28D9',
      illustrationType: 'math_geometry',
      previewThumbnail: '📏',
    },
    {
      id: 'math_colorful',
      name: { fr: 'Colorful Math', ar: 'رياضيات ملونة', en: 'Colorful Math' },
      icon: '🎲',
      category: 'math',
      primaryColor: '#EA580C',
      secondaryColor: '#FFF7ED',
      accentColor: '#3B82F6',
      bgColor: '#FFFDF9',
      borderColor: '#FED7AA',
      textColor: '#7C2D12',
      badgeBg: '#FFEDD5',
      badgeText: '#C2410C',
      illustrationType: 'math_colorful',
      previewThumbnail: '🎲',
    },
    {
      id: 'math_space',
      name: { fr: 'Space Math', ar: 'رياضيات الفضاء', en: 'Space Math' },
      icon: '🚀',
      category: 'math',
      primaryColor: '#312E81',
      secondaryColor: '#1E1B4B',
      accentColor: '#F59E0B',
      bgColor: '#0F172A',
      borderColor: '#6366F1',
      textColor: '#F8FAFC',
      badgeBg: '#1E293B',
      badgeText: '#FBBF24',
      illustrationType: 'math_space',
      previewThumbnail: '🚀',
    },
  ],
  geography: [
    {
      id: 'geo_world',
      name: { fr: 'World Explorer', ar: 'مستكشف العالم', en: 'World Explorer' },
      icon: '🌍',
      category: 'humanities',
      primaryColor: '#0284C7',
      secondaryColor: '#F0F9FF',
      accentColor: '#10B981',
      bgColor: '#F8FAFC',
      borderColor: '#7DD3FC',
      textColor: '#075985',
      badgeBg: '#E0F2FE',
      badgeText: '#0369A1',
      illustrationType: 'geo_world',
      previewThumbnail: '🌍',
    },
    {
      id: 'geo_maps',
      name: { fr: 'Maps & Cartography', ar: 'خرائط وأطالس', en: 'Maps & Cartography' },
      icon: '🗺️',
      category: 'humanities',
      primaryColor: '#B45309',
      secondaryColor: '#FFFBEB',
      accentColor: '#059669',
      bgColor: '#FEFDFB',
      borderColor: '#FCD34D',
      textColor: '#78350F',
      badgeBg: '#FEF3C7',
      badgeText: '#92400E',
      illustrationType: 'geo_maps',
      previewThumbnail: '🗺️',
    },
    {
      id: 'geo_earth',
      name: { fr: 'Earth & Nature', ar: 'كوكب الأرض والطبيعة', en: 'Earth & Nature' },
      icon: '🌱',
      category: 'humanities',
      primaryColor: '#15803D',
      secondaryColor: '#F0FDF4',
      accentColor: '#0EA5E9',
      bgColor: '#FAFDFB',
      borderColor: '#86EFAC',
      textColor: '#14532D',
      badgeBg: '#DCFCE7',
      badgeText: '#166534',
      illustrationType: 'geo_earth',
      previewThumbnail: '🌱',
    },
    {
      id: 'geo_adventure',
      name: { fr: 'Adventure & Mountains', ar: 'مغامرة وجبال', en: 'Adventure & Mountains' },
      icon: '🏔️',
      category: 'humanities',
      primaryColor: '#475569',
      secondaryColor: '#F8FAFC',
      accentColor: '#F97316',
      bgColor: '#F8FAFC',
      borderColor: '#CBD5E1',
      textColor: '#1E293B',
      badgeBg: '#F1F5F9',
      badgeText: '#334155',
      illustrationType: 'geo_adventure',
      previewThumbnail: '🏔️',
    },
  ],
  history: [
    {
      id: 'hist_ancient',
      name: { fr: 'Ancient Civilizations', ar: 'حضارات قديمة', en: 'Ancient Civilizations' },
      icon: '🏛️',
      category: 'humanities',
      primaryColor: '#92400E',
      secondaryColor: '#FFFBEB',
      accentColor: '#D97706',
      bgColor: '#FFFDF9',
      borderColor: '#FDE68A',
      textColor: '#78350F',
      badgeBg: '#FEF3C7',
      badgeText: '#92400E',
      illustrationType: 'hist_ancient',
      previewThumbnail: '🏛️',
    },
    {
      id: 'hist_discovery',
      name: { fr: 'Great Discoveries', ar: 'اكتشافات كبرى', en: 'Great Discoveries' },
      icon: '🧭',
      category: 'humanities',
      primaryColor: '#1E3A8A',
      secondaryColor: '#EFF6FF',
      accentColor: '#EAB308',
      bgColor: '#F8FAFC',
      borderColor: '#BFDBFE',
      textColor: '#172554',
      badgeBg: '#DBEAFE',
      badgeText: '#1E40AF',
      illustrationType: 'hist_discovery',
      previewThumbnail: '🧭',
    },
    {
      id: 'hist_monuments',
      name: { fr: 'Heritage & Pyramids', ar: 'أهرامات وتراث', en: 'Heritage & Pyramids' },
      icon: '🏺',
      category: 'humanities',
      primaryColor: '#A16207',
      secondaryColor: '#FEFCE8',
      accentColor: '#CA8A04',
      bgColor: '#FFFEF5',
      borderColor: '#FEF08A',
      textColor: '#713F12',
      badgeBg: '#FEF9C3',
      badgeText: '#854D0E',
      illustrationType: 'hist_monuments',
      previewThumbnail: '🏺',
    },
  ],
  science: [
    {
      id: 'sci_lab',
      name: { fr: 'Laboratory & Chemistry', ar: 'مخبر وكيمياء', en: 'Laboratory & Chemistry' },
      icon: '🧪',
      category: 'science',
      primaryColor: '#059669',
      secondaryColor: '#ECFDF5',
      accentColor: '#3B82F6',
      bgColor: '#F0FDF4',
      borderColor: '#6EE7B7',
      textColor: '#064E3B',
      badgeBg: '#D1FAE5',
      badgeText: '#065F46',
      illustrationType: 'sci_lab',
      previewThumbnail: '🧪',
    },
    {
      id: 'sci_nature',
      name: { fr: 'Biology & Botany', ar: 'أحياء ونباتات', en: 'Biology & Botany' },
      icon: '🔬',
      category: 'science',
      primaryColor: '#16A34A',
      secondaryColor: '#F0FDF4',
      accentColor: '#EAB308',
      bgColor: '#FAFDF8',
      borderColor: '#A7F3D0',
      textColor: '#14532D',
      badgeBg: '#DCFCE7',
      badgeText: '#15803D',
      illustrationType: 'sci_nature',
      previewThumbnail: '🔬',
    },
    {
      id: 'sci_space',
      name: { fr: 'Cosmos & Astronomy', ar: 'فلك وفضاء', en: 'Cosmos & Astronomy' },
      icon: '🪐',
      category: 'science',
      primaryColor: '#4338CA',
      secondaryColor: '#EEF2FF',
      accentColor: '#EC4899',
      bgColor: '#0F172A',
      borderColor: '#818CF8',
      textColor: '#F8FAFC',
      badgeBg: '#1E293B',
      badgeText: '#A5B4FC',
      illustrationType: 'sci_space',
      previewThumbnail: '🪐',
    },
  ],
  arabic: [
    {
      id: 'ar_calligraphy',
      name: { fr: 'Calligraphie & Zakhrafa', ar: 'فن الخط والزخرفة', en: 'Calligraphy & Art' },
      icon: '✒️',
      category: 'languages',
      primaryColor: '#047857',
      secondaryColor: '#ECFDF5',
      accentColor: '#D97706',
      bgColor: '#FDFBF7',
      borderColor: '#6EE7B7',
      textColor: '#064E3B',
      badgeBg: '#D1FAE5',
      badgeText: '#065F46',
      illustrationType: 'ar_calligraphy',
      previewThumbnail: '✒️',
    },
    {
      id: 'ar_letters',
      name: { fr: 'Lettres & Alphabet Arabe', ar: 'حروف ولغة الضاد', en: 'Arabic Letters' },
      icon: '📜',
      category: 'languages',
      primaryColor: '#B45309',
      secondaryColor: '#FFFBEB',
      accentColor: '#059669',
      bgColor: '#FFFDF9',
      borderColor: '#FCD34D',
      textColor: '#78350F',
      badgeBg: '#FEF3C7',
      badgeText: '#92400E',
      illustrationType: 'ar_letters',
      previewThumbnail: '📜',
    },
    {
      id: 'ar_reading',
      name: { fr: 'Lecture & Contes', ar: 'مطالعة وقصص', en: 'Reading & Tales' },
      icon: '📖',
      category: 'languages',
      primaryColor: '#C026D3',
      secondaryColor: '#FDF4FF',
      accentColor: '#F59E0B',
      bgColor: '#FAF5FF',
      borderColor: '#F0ABFC',
      textColor: '#701A75',
      badgeBg: '#FAE8FF',
      badgeText: '#86198F',
      illustrationType: 'ar_reading',
      previewThumbnail: '📖',
    },
  ],
  french: [
    {
      id: 'fr_alphabet',
      name: { fr: 'Alphabet & Vocabulaire', ar: 'أبجدية ومفردات', en: 'Alphabet & Words' },
      icon: '🔤',
      category: 'languages',
      primaryColor: '#1D4ED8',
      secondaryColor: '#EFF6FF',
      accentColor: '#EF4444',
      bgColor: '#F8FAFC',
      borderColor: '#93C5FD',
      textColor: '#1E3A8A',
      badgeBg: '#DBEAFE',
      badgeText: '#1E40AF',
      illustrationType: 'fr_alphabet',
      previewThumbnail: '🔤',
    },
    {
      id: 'fr_stories',
      name: { fr: 'Contes & Lecture', ar: 'قصص ومطالعة فرنسية', en: 'French Stories' },
      icon: '📚',
      category: 'languages',
      primaryColor: '#9333EA',
      secondaryColor: '#FAF5FF',
      accentColor: '#F59E0B',
      bgColor: '#FCF9FE',
      borderColor: '#D8B4FE',
      textColor: '#581C87',
      badgeBg: '#F3E8FF',
      badgeText: '#7E22CE',
      illustrationType: 'fr_stories',
      previewThumbnail: '📚',
    },
  ],
  english: [
    {
      id: 'en_letters',
      name: { fr: 'ABC English Adventure', ar: 'مغامرة الإنجليزية', en: 'ABC English Adventure' },
      icon: '🇬🇧',
      category: 'languages',
      primaryColor: '#DC2626',
      secondaryColor: '#FEF2F2',
      accentColor: '#2563EB',
      bgColor: '#FAFAFA',
      borderColor: '#FECACA',
      textColor: '#7F1D1D',
      badgeBg: '#FEE2E2',
      badgeText: '#991B1B',
      illustrationType: 'en_letters',
      previewThumbnail: '🇬🇧',
    },
    {
      id: 'en_grammar',
      name: { fr: 'Words & Grammar', ar: 'كلمات وقواعد', en: 'Words & Grammar' },
      icon: '💡',
      category: 'languages',
      primaryColor: '#0891B2',
      secondaryColor: '#ECFEFF',
      accentColor: '#F59E0B',
      bgColor: '#F8FAFC',
      borderColor: '#A5F3FC',
      textColor: '#164E63',
      badgeBg: '#CFFAFE',
      badgeText: '#0E7490',
      illustrationType: 'en_grammar',
      previewThumbnail: '💡',
    },
  ],
  islamic: [
    {
      id: 'isl_mosque',
      name: { fr: 'Mosquée & Minaret', ar: 'المسجد والمئذنة', en: 'Mosque & Minaret' },
      icon: '🕌',
      category: 'islamic',
      primaryColor: '#059669',
      secondaryColor: '#ECFDF5',
      accentColor: '#EAB308',
      bgColor: '#FDFBF7',
      borderColor: '#6EE7B7',
      textColor: '#064E3B',
      badgeBg: '#D1FAE5',
      badgeText: '#065F46',
      illustrationType: 'isl_mosque',
      previewThumbnail: '🕌',
    },
    {
      id: 'isl_geometric',
      name: { fr: 'Zakhrafa Arabesque', ar: 'زخارف إسلامية ذهبية', en: 'Golden Arabesque' },
      icon: '✨',
      category: 'islamic',
      primaryColor: '#D97706',
      secondaryColor: '#FFFBEB',
      accentColor: '#0D9488',
      bgColor: '#FFFDF9',
      borderColor: '#FDE68A',
      textColor: '#78350F',
      badgeBg: '#FEF3C7',
      badgeText: '#B45309',
      illustrationType: 'isl_geometric',
      previewThumbnail: '✨',
    },
    {
      id: 'isl_lantern',
      name: { fr: 'Fanous & Lumière', ar: 'فانوس ونور العلم', en: 'Lantern & Light' },
      icon: '🏮',
      category: 'islamic',
      primaryColor: '#0F766E',
      secondaryColor: '#F0FDFA',
      accentColor: '#F59E0B',
      bgColor: '#F7FCFA',
      borderColor: '#99F6E4',
      textColor: '#134E4A',
      badgeBg: '#CCFBF1',
      badgeText: '#0F766E',
      illustrationType: 'isl_lantern',
      previewThumbnail: '🏮',
    },
  ],
  exercise: [
    {
      id: 'ex_stationery',
      name: { fr: 'Stylos & Réussite', ar: 'أقلام وتمارين', en: 'Pens & Exercises' },
      icon: '✏️',
      category: 'notes',
      primaryColor: '#2563EB',
      secondaryColor: '#EFF6FF',
      accentColor: '#10B981',
      bgColor: '#F8FAFC',
      borderColor: '#93C5FD',
      textColor: '#1E3A8A',
      badgeBg: '#DBEAFE',
      badgeText: '#1D4ED8',
      illustrationType: 'ex_stationery',
      previewThumbnail: '✏️',
    },
    {
      id: 'ex_creative',
      name: { fr: 'Créativité & Couleurs', ar: 'إبداع وألوان', en: 'Creative Notes' },
      icon: '🎨',
      category: 'notes',
      primaryColor: '#E11D48',
      secondaryColor: '#FFF1F2',
      accentColor: '#F59E0B',
      bgColor: '#FAFAFA',
      borderColor: '#FECDD3',
      textColor: '#881337',
      badgeBg: '#FFE4E6',
      badgeText: '#9F1239',
      illustrationType: 'ex_creative',
      previewThumbnail: '🎨',
    },
  ],
  homework: [
    {
      id: 'hw_focus',
      name: { fr: 'Objectifs & Devoirs', ar: 'واجبات وتركيز', en: 'Focus & Homework' },
      icon: '🎯',
      category: 'notes',
      primaryColor: '#7C3AED',
      secondaryColor: '#FAF5FF',
      accentColor: '#F59E0B',
      bgColor: '#FAFAFA',
      borderColor: '#C4B5FD',
      textColor: '#5B21B6',
      badgeBg: '#EDE9FE',
      badgeText: '#6D28D9',
      illustrationType: 'hw_focus',
      previewThumbnail: '🎯',
    },
    {
      id: 'hw_stars',
      name: { fr: 'Étoiles du Travail', ar: 'نجوم المثابرة', en: 'Homework Stars' },
      icon: '⭐',
      category: 'notes',
      primaryColor: '#D97706',
      secondaryColor: '#FFFBEB',
      accentColor: '#2563EB',
      bgColor: '#FFFDF9',
      borderColor: '#FDE68A',
      textColor: '#78350F',
      badgeBg: '#FEF3C7',
      badgeText: '#92400E',
      illustrationType: 'hw_stars',
      previewThumbnail: '⭐',
    },
  ],
  textbook: [
    {
      id: 'tb_notes',
      name: { fr: 'Agenda & Textes', ar: 'نصوص ومذكرات', en: 'Agenda & Notes' },
      icon: '📓',
      category: 'notes',
      primaryColor: '#0284C7',
      secondaryColor: '#F0F9FF',
      accentColor: '#EC4899',
      bgColor: '#F8FAFC',
      borderColor: '#7DD3FC',
      textColor: '#075985',
      badgeBg: '#E0F2FE',
      badgeText: '#0369A1',
      illustrationType: 'tb_notes',
      previewThumbnail: '📓',
    },
  ],
  other: [
    {
      id: 'gen_classic',
      name: { fr: 'Classique & Élégant', ar: 'كلاسيكي وأنيق', en: 'Classic & Elegant' },
      icon: '🏅',
      category: 'general',
      primaryColor: '#1E293B',
      secondaryColor: '#F8FAFC',
      accentColor: '#EA580C',
      bgColor: '#FFFFFF',
      borderColor: '#CBD5E1',
      textColor: '#0F172A',
      badgeBg: '#F1F5F9',
      badgeText: '#334155',
      illustrationType: 'gen_classic',
      previewThumbnail: '🏅',
    },
  ],
};

export function getThemesForSelection(type: string, subject?: NotebookSubject): ThemeDefinition[] {
  if (type === 'notebook_cover' && subject && SUBJECT_THEMES[subject]) {
    return SUBJECT_THEMES[subject];
  }
  return GENERAL_THEMES;
}

export const COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'rose_pastel',
    name: { fr: 'Rose pastel', ar: 'وردي باستيل', en: 'Pastel Pink' },
    colors: ['#EC4899', '#F472B6', '#FBCFE8', '#FFF5F9'],
    primaryColor: '#EC4899',
    secondaryColor: '#FDF2F8',
    accentColor: '#F472B6',
    bgColor: '#FFF5F9',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
  },
  {
    id: 'bleu_ciel',
    name: { fr: 'Bleu ciel', ar: 'أزرق سماوي', en: 'Sky Blue' },
    colors: ['#2563EB', '#38BDF8', '#BAE6FD', '#F0F9FF'],
    primaryColor: '#2563EB',
    secondaryColor: '#EFF6FF',
    accentColor: '#38BDF8',
    bgColor: '#F0F9FF',
    borderColor: '#BAE6FD',
    textColor: '#0C4A6E',
    badgeBg: '#E0F2FE',
    badgeText: '#0369A1',
  },
  {
    id: 'lavande',
    name: { fr: 'Lilas / Lavande', ar: 'ليلكي / خزامى', en: 'Lilac / Lavender' },
    colors: ['#7C3AED', '#A855F7', '#DDD6FE', '#FAF5FF'],
    primaryColor: '#7C3AED',
    secondaryColor: '#FAF5FF',
    accentColor: '#A855F7',
    bgColor: '#FAF5FF',
    borderColor: '#DDD6FE',
    textColor: '#4C1D95',
    badgeBg: '#EDE9FE',
    badgeText: '#6D28D9',
  },
  {
    id: 'vert_menthe',
    name: { fr: 'Vert menthe', ar: 'أخضر نعناعي', en: 'Mint Green' },
    colors: ['#059669', '#10B981', '#A7F3D0', '#F0FDF4'],
    primaryColor: '#059669',
    secondaryColor: '#ECFDF5',
    accentColor: '#10B981',
    bgColor: '#F0FDF4',
    borderColor: '#A7F3D0',
    textColor: '#064E3B',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
  },
  {
    id: 'jaune_doux',
    name: { fr: 'Jaune doux', ar: 'أصفر هادئ', en: 'Soft Yellow' },
    colors: ['#D97706', '#F59E0B', '#FDE68A', '#FFFDF5'],
    primaryColor: '#D97706',
    secondaryColor: '#FFFBEB',
    accentColor: '#F59E0B',
    bgColor: '#FFFDF5',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
  },
  {
    id: 'peche_corail',
    name: { fr: 'Pêche / Corail pastel', ar: 'خوخي / مرجاني باستيل', en: 'Coral Peach' },
    colors: ['#EA580C', '#FB923C', '#FED7AA', '#FFFBF5'],
    primaryColor: '#EA580C',
    secondaryColor: '#FFF7ED',
    accentColor: '#FB923C',
    bgColor: '#FFFBF5',
    borderColor: '#FED7AA',
    textColor: '#7C2D12',
    badgeBg: '#FFEDD5',
    badgeText: '#9A3412',
  },
  {
    id: 'arc_en_ciel_pastel',
    name: { fr: 'Arc-en-ciel pastel', ar: 'قوس قزح باستيل', en: 'Pastel Rainbow' },
    colors: ['#F472B6', '#C084FC', '#60A5FA', '#FDE047'],
    primaryColor: '#EC4899',
    secondaryColor: '#FDF2F8',
    accentColor: '#818CF8',
    bgColor: '#FFFDF5',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
  },
  {
    id: 'beige_creme',
    name: { fr: 'Beige / Crème', ar: 'بيج / كريمي', en: 'Beige / Cream' },
    colors: ['#8D6E63', '#A18262', '#D7CCC8', '#FAF7F2'],
    primaryColor: '#8D6E63',
    secondaryColor: '#FAF7F2',
    accentColor: '#A18262',
    bgColor: '#FDFBF7',
    borderColor: '#E8DED3',
    textColor: '#4E342E',
    badgeBg: '#EFEBE9',
    badgeText: '#5D4037',
  },
  {
    id: 'turquoise',
    name: { fr: 'Turquoise lagon', ar: 'فيروزي بحري', en: 'Lagoon Turquoise' },
    colors: ['#0D9488', '#14B8A6', '#99F6E4', '#F0FDFA'],
    primaryColor: '#0D9488',
    secondaryColor: '#F0FDFA',
    accentColor: '#14B8A6',
    bgColor: '#F0FDFA',
    borderColor: '#99F6E4',
    textColor: '#134E4A',
    badgeBg: '#CCFBF1',
    badgeText: '#115E59',
  },
  {
    id: 'framboise',
    name: { fr: 'Framboise vif', ar: 'توتي مشرق', en: 'Vivid Raspberry' },
    colors: ['#E11D48', '#F43F5E', '#FECDD3', '#FFF1F2'],
    primaryColor: '#E11D48',
    secondaryColor: '#FFF1F2',
    accentColor: '#F43F5E',
    bgColor: '#FFF5F5',
    borderColor: '#FECDD3',
    textColor: '#881337',
    badgeBg: '#FFE4E6',
    badgeText: '#9F1239',
  },
  {
    id: 'bleu_marine',
    name: { fr: 'Bleu marine', ar: 'أزرق كلاسيكي', en: 'Classic Navy' },
    colors: ['#1D4ED8', '#3B82F6', '#BFDBFE', '#F8FAFC'],
    primaryColor: '#1D4ED8',
    secondaryColor: '#EFF6FF',
    accentColor: '#3B82F6',
    bgColor: '#F8FAFC',
    borderColor: '#BFDBFE',
    textColor: '#1E3A8A',
    badgeBg: '#DBEAFE',
    badgeText: '#1D4ED8',
  },
  {
    id: 'lilas',
    name: { fr: 'Lilas magique', ar: 'ليلكي ساحر', en: 'Magical Lilac' },
    colors: ['#9333EA', '#C084FC', '#E9D5FF', '#FDF4FF'],
    primaryColor: '#9333EA',
    secondaryColor: '#FAF5FF',
    accentColor: '#EC4899',
    bgColor: '#FDF4FF',
    borderColor: '#E9D5FF',
    textColor: '#581C87',
    badgeBg: '#F3E8FF',
    badgeText: '#6B21A8',
  },
  {
    id: 'vert_foret',
    name: { fr: 'Vert forêt', ar: 'أخضر غابي', en: 'Forest Green' },
    colors: ['#15803D', '#16A34A', '#BBF7D0', '#F7FEE7'],
    primaryColor: '#15803D',
    secondaryColor: '#F0FDF4',
    accentColor: '#84CC16',
    bgColor: '#F7FEE7',
    borderColor: '#BBF7D0',
    textColor: '#14532D',
    badgeBg: '#DCFCE7',
    badgeText: '#166534',
  },
  {
    id: 'ardoise',
    name: { fr: 'Gris ardoise', ar: 'رمادي أنيق', en: 'Slate Gray' },
    colors: ['#475569', '#64748B', '#CBD5E1', '#F8FAFC'],
    primaryColor: '#475569',
    secondaryColor: '#F8FAFC',
    accentColor: '#38BDF8',
    bgColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    textColor: '#1E293B',
    badgeBg: '#E2E8F0',
    badgeText: '#0F172A',
  },
  {
    id: 'terracotta',
    name: { fr: 'Terracotta', ar: 'تيراكوتا دافئ', en: 'Terracotta Warm' },
    colors: ['#C2410C', '#EA580C', '#FDBA74', '#FFF7ED'],
    primaryColor: '#C2410C',
    secondaryColor: '#FFF7ED',
    accentColor: '#FB923C',
    bgColor: '#FFF7ED',
    borderColor: '#FDBA74',
    textColor: '#7C2D12',
    badgeBg: '#FFEDD5',
    badgeText: '#9A3412',
  },
  {
    id: 'bleu_canard',
    name: { fr: 'Bleu canard', ar: 'أزرق بطي', en: 'Peacock Teal' },
    colors: ['#0E7490', '#06B6D4', '#A5F3FC', '#ECFEFF'],
    primaryColor: '#0E7490',
    secondaryColor: '#ECFEFF',
    accentColor: '#06B6D4',
    bgColor: '#ECFEFF',
    borderColor: '#A5F3FC',
    textColor: '#155E75',
    badgeBg: '#CFFAFE',
    badgeText: '#0E7490',
  },
  {
    id: 'vert_olive',
    name: { fr: 'Vert olive', ar: 'أخضر زيتوني', en: 'Olive Green' },
    colors: ['#4D7C0F', '#65A30D', '#BEF264', '#F7FEE7'],
    primaryColor: '#4D7C0F',
    secondaryColor: '#F7FEE7',
    accentColor: '#84CC16',
    bgColor: '#F7FEE7',
    borderColor: '#BEF264',
    textColor: '#365314',
    badgeBg: '#ECFCCB',
    badgeText: '#4D7C0F',
  },
  {
    id: 'soleil_ambre',
    name: { fr: 'Ambre solaire', ar: 'كهرمان شمسي', en: 'Amber Gold' },
    colors: ['#B45309', '#F59E0B', '#FDE047', '#FEFCE8'],
    primaryColor: '#B45309',
    secondaryColor: '#FEFCE8',
    accentColor: '#FBBF24',
    bgColor: '#FEFCE8',
    borderColor: '#FDE047',
    textColor: '#78350F',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
  },
  {
    id: 'rose_poudre',
    name: { fr: 'Rose poudré', ar: 'وردي ناعم', en: 'Powder Blush' },
    colors: ['#DB2777', '#F472B6', '#FCE7F3', '#FFF1F2'],
    primaryColor: '#DB2777',
    secondaryColor: '#FFF1F2',
    accentColor: '#F472B6',
    bgColor: '#FFF1F2',
    borderColor: '#FCE7F3',
    textColor: '#831843',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
  },
  {
    id: 'chocolat',
    name: { fr: 'Moka caramel', ar: 'موكا كراميل', en: 'Mocha Caramel' },
    colors: ['#78350F', '#92400E', '#E7E5E4', '#FAF7F5'],
    primaryColor: '#78350F',
    secondaryColor: '#FAF7F5',
    accentColor: '#B45309',
    bgColor: '#FAF7F5',
    borderColor: '#E7E5E4',
    textColor: '#451A03',
    badgeBg: '#F5EBE1',
    badgeText: '#78350F',
  },
  {
    id: 'prune_royale',
    name: { fr: 'Prune royale', ar: 'برقوقي ملكي', en: 'Royal Plum' },
    colors: ['#701A75', '#A21CAF', '#F0ABFC', '#FDF4FF'],
    primaryColor: '#701A75',
    secondaryColor: '#FDF4FF',
    accentColor: '#C026D3',
    bgColor: '#FDF4FF',
    borderColor: '#F0ABFC',
    textColor: '#4A044E',
    badgeBg: '#FAE8FF',
    badgeText: '#86198F',
  },
  {
    id: 'emeraude_menthol',
    name: { fr: 'Émeraude givrée', ar: 'زمردي نضر', en: 'Frosted Emerald' },
    colors: ['#047857', '#10B981', '#6EE7B7', '#F0FDF4'],
    primaryColor: '#047857',
    secondaryColor: '#F0FDF4',
    accentColor: '#34D399',
    bgColor: '#F0FDF4',
    borderColor: '#6EE7B7',
    textColor: '#064E3B',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
  },
];

export const ILLUSTRATION_THEMES: IllustrationDefinition[] = [
  { id: 'cute', name: { fr: 'Fleurs / Cute', ar: 'زهور / لطيف', en: 'Flowers / Cute' }, category: 'nature' },
  { id: 'dino', name: { fr: 'Dinosaures', ar: 'ديناصورات', en: 'Dinosaurs' }, category: 'animals' },
  { id: 'space', name: { fr: 'Espace', ar: 'فضاء', en: 'Space' }, category: 'space' },
  { id: 'football', name: { fr: 'Football', ar: 'كرة قدم', en: 'Football' }, category: 'sports' },
  { id: 'unicorn', name: { fr: 'Licorne', ar: 'وحيد القرن', en: 'Unicorn' }, category: 'fantasy' },
  { id: 'rainbow', name: { fr: 'Arc-en-ciel', ar: 'قوس قزح', en: 'Rainbow' }, category: 'fantasy' },
  { id: 'animals', name: { fr: 'Animaux', ar: 'حيوانات', en: 'Animals' }, category: 'animals' },
  { id: 'gamer', name: { fr: 'Gamer', ar: 'ألعاب فيديو', en: 'Gamer' }, category: 'gaming' },
  { id: 'superhero', name: { fr: 'Super-héros', ar: 'أبطال خارقين', en: 'Superhero' }, category: 'fantasy' },
  { id: 'cars', name: { fr: 'Voiture', ar: 'سيارات', en: 'Cars' }, category: 'vehicles' },
  { id: 'jurassic', name: { fr: 'Monde Jurassique', ar: 'عالم جوراسي', en: 'Jurassic World' }, category: 'animals' },
  { id: 'candy', name: { fr: 'Bonbons', ar: 'حلويات', en: 'Candy & Sweets' }, category: 'sweets' },
  { id: 'ocean', name: { fr: 'Océan', ar: 'مغامرة البحر', en: 'Ocean' }, category: 'ocean' },
  { id: 'pirate', name: { fr: 'Pirates', ar: 'قراصنة', en: 'Pirates' }, category: 'fantasy' },
  { id: 'nature', name: { fr: 'Nature', ar: 'طبيعة', en: 'Nature & Forest' }, category: 'nature' },
  { id: 'panda', name: { fr: 'Panda kawaii', ar: 'باندا لطيف', en: 'Cute Panda' }, category: 'animals' },
  { id: 'cupcake', name: { fr: 'Cupcake gourmand', ar: 'كب كيك شهي', en: 'Sweet Cupcake' }, category: 'sweets' },
  { id: 'butterfly', name: { fr: 'Papillon féerique', ar: 'فراشة ساحرة', en: 'Magical Butterfly' }, category: 'nature' },
  { id: 'koala', name: { fr: 'Koala mignon', ar: 'كوالا لطيف', en: 'Cute Koala' }, category: 'animals' },
  { id: 'robot', name: { fr: 'Robot mignon', ar: 'روبوت لطيف', en: 'Cute Robot' }, category: 'fantasy' },
  { id: 'strawberry', name: { fr: 'Fraise sucrée', ar: 'فراولة حلوة', en: 'Sweet Strawberry' }, category: 'sweets' },
  { id: 'star', name: { fr: 'Étoile magique', ar: 'نجمة سحرية', en: 'Magic Star' }, category: 'fantasy' },
  { id: 'fox', name: { fr: 'Petit renard', ar: 'ثعلب صغير', en: 'Little Fox' }, category: 'animals' },
  { id: 'music', name: { fr: 'Musique pop', ar: 'موسيقى ونغمات', en: 'Pop Music' }, category: 'art' },
  { id: 'balloon', name: { fr: 'Montgolfière', ar: 'منطاد الأحلام', en: 'Dream Balloon' }, category: 'fantasy' },
  { id: 'mermaid', name: { fr: 'Sirène pastel', ar: 'حورية بحر باستيل', en: 'Pastel Mermaid' }, category: 'fantasy' },
  { id: 'moon', name: { fr: 'Lune souriante étoilée', ar: 'قمر مبتسم مع نجوم', en: 'Smiling Moon & Stars' }, category: 'space' },
  { id: 'cactus', name: { fr: 'Cactus souriant', ar: 'صبار مبتسم', en: 'Smiling Cactus' }, category: 'nature' },
  { id: 'donut', name: { fr: 'Donut glacé mignon', ar: 'دونات مثلج لطيف', en: 'Sweet Glazed Donut' }, category: 'sweets' },
  { id: 'penguin', name: { fr: 'Manchot kawaii', ar: 'بطريق لطيف', en: 'Kawaii Penguin' }, category: 'animals' },
  { id: 'hedgehog', name: { fr: 'Hérisson kawaii', ar: 'قنفذ لطيف', en: 'Kawaii Hedgehog' }, category: 'animals' },
  { id: 'mushroom', name: { fr: 'Champignon magique souriant', ar: 'فطر سحري مبتسم', en: 'Magic Mushroom' }, category: 'nature' },
  { id: 'tropical_fish', name: { fr: 'Poisson tropical mignon', ar: 'سمكة استوائية لطيفة', en: 'Cute Tropical Fish' }, category: 'ocean' },
  { id: 'art_palette', name: { fr: "Palette d'artiste kawaii", ar: 'لوحة ألوان فنية لطيفة', en: 'Kawaii Art Palette' }, category: 'art' },
  { id: 'bunny', name: { fr: 'Lapin pastel', ar: 'أرنب باستيل', en: 'Pastel Bunny' }, category: 'animals' },
];

export function getEffectiveTheme(
  paletteId?: string,
  illustrationId?: string,
  subject?: NotebookSubject
): ThemeDefinition {
  // If notebook subject theme applies and no specific palette was selected
  if (subject && SUBJECT_THEMES[subject] && !paletteId) {
    return SUBJECT_THEMES[subject][0];
  }

  // Find selected palette or matching fallback
  const palette =
    COLOR_PALETTES.find((p) => p.id === paletteId) ||
    COLOR_PALETTES.find((p) => p.id === 'rose_pastel') ||
    COLOR_PALETTES[0];

  const illId = illustrationId || 'cute';
  const illustration =
    ILLUSTRATION_THEMES.find((i) => i.id === illId) || ILLUSTRATION_THEMES[0];

  return {
    id: `${palette.id}_${illId}`,
    name: {
      fr: `${palette.name.fr} • ${illustration.name.fr}`,
      ar: `${palette.name.ar} • ${illustration.name.ar}`,
      en: `${palette.name.en} • ${illustration.name.en}`,
    },
    icon: '✨',
    category: 'general',
    primaryColor: palette.primaryColor,
    secondaryColor: palette.secondaryColor,
    accentColor: palette.accentColor,
    bgColor: palette.bgColor,
    borderColor: palette.borderColor,
    textColor: palette.textColor,
    badgeBg: palette.badgeBg,
    badgeText: palette.badgeText,
    illustrationType: illId,
    previewThumbnail: '✨',
  };
}

