/**
 * Accurate Arabic letter contextual forms conforming strictly to Arabic phonology & orthography.
 * Letters that do NOT connect to the left (حروف الانفصال: ا, د, ذ, ر, ز, و)
 * never have a left connecting stem (tatweel).
 */

export interface ArabicLetterMeta {
  letter: string;
  name: string;
  nameAr: string;
  canConnectLeft: boolean; // false for ا, د, ذ, ر, ز, و
  isolated: string;
  initial: string;
  medial: string;
  final: string;
}

export const ARABIC_ALPHABET_DATA: ArabicLetterMeta[] = [
  {
    letter: 'أ',
    name: 'Alif',
    nameAr: 'أَلِف',
    canConnectLeft: false,
    isolated: 'أ',
    initial: 'أ',
    medial: 'ـأ',
    final: 'ـأ',
  },
  {
    letter: 'ب',
    name: 'Baa',
    nameAr: 'بَاء',
    canConnectLeft: true,
    isolated: 'ب',
    initial: 'بـ',
    medial: 'ـبـ',
    final: 'ـب',
  },
  {
    letter: 'ت',
    name: 'Taa',
    nameAr: 'تَاء',
    canConnectLeft: true,
    isolated: 'ت',
    initial: 'تـ',
    medial: 'ـتـ',
    final: 'ـت',
  },
  {
    letter: 'ث',
    name: 'Thaa',
    nameAr: 'ثَاء',
    canConnectLeft: true,
    isolated: 'ث',
    initial: 'ثـ',
    medial: 'ـثـ',
    final: 'ـث',
  },
  {
    letter: 'ج',
    name: 'Jeem',
    nameAr: 'جِيم',
    canConnectLeft: true,
    isolated: 'ج',
    initial: 'جـ',
    medial: 'ـجـ',
    final: 'ـج',
  },
  {
    letter: 'ح',
    name: 'Haa',
    nameAr: 'حَاء',
    canConnectLeft: true,
    isolated: 'ح',
    initial: 'حـ',
    medial: 'ـحـ',
    final: 'ـح',
  },
  {
    letter: 'خ',
    name: 'Khaa',
    nameAr: 'خَاء',
    canConnectLeft: true,
    isolated: 'خ',
    initial: 'خـ',
    medial: 'ـخـ',
    final: 'ـخ',
  },
  {
    letter: 'د',
    name: 'Daal',
    nameAr: 'دَال',
    canConnectLeft: false,
    isolated: 'د',
    initial: 'د',
    medial: 'ـد',
    final: 'ـد',
  },
  {
    letter: 'ذ',
    name: 'Thaal',
    nameAr: 'ذَال',
    canConnectLeft: false,
    isolated: 'ذ',
    initial: 'ذ',
    medial: 'ـذ',
    final: 'ـذ',
  },
  {
    letter: 'ر',
    name: 'Raa',
    nameAr: 'رَاء',
    canConnectLeft: false,
    isolated: 'ر',
    initial: 'ر',
    medial: 'ـر',
    final: 'ـر',
  },
  {
    letter: 'ز',
    name: 'Zay',
    nameAr: 'زَاي',
    canConnectLeft: false,
    isolated: 'ز',
    initial: 'ز',
    medial: 'ـز',
    final: 'ـز',
  },
  {
    letter: 'س',
    name: 'Seen',
    nameAr: 'سِين',
    canConnectLeft: true,
    isolated: 'س',
    initial: 'سـ',
    medial: 'ـسـ',
    final: 'ـس',
  },
  {
    letter: 'ش',
    name: 'Sheen',
    nameAr: 'شِين',
    canConnectLeft: true,
    isolated: 'ش',
    initial: 'شـ',
    medial: 'ـشـ',
    final: 'ـش',
  },
  {
    letter: 'ص',
    name: 'Saad',
    nameAr: 'صَاد',
    canConnectLeft: true,
    isolated: 'ص',
    initial: 'صـ',
    medial: 'ـصـ',
    final: 'ـص',
  },
  {
    letter: 'ض',
    name: 'Daad',
    nameAr: 'ضَاد',
    canConnectLeft: true,
    isolated: 'ض',
    initial: 'ضـ',
    medial: 'ـضـ',
    final: 'ـض',
  },
  {
    letter: 'ط',
    name: 'Taa',
    nameAr: 'طَاء',
    canConnectLeft: true,
    isolated: 'ط',
    initial: 'طـ',
    medial: 'ـطـ',
    final: 'ـط',
  },
  {
    letter: 'ظ',
    name: 'Zhaa',
    nameAr: 'ظَاء',
    canConnectLeft: true,
    isolated: 'ظ',
    initial: 'ظـ',
    medial: 'ـظـ',
    final: 'ـظ',
  },
  {
    letter: 'ع',
    name: 'Ayn',
    nameAr: 'عَيْن',
    canConnectLeft: true,
    isolated: 'ع',
    initial: 'عـ',
    medial: 'ـعـ',
    final: 'ـع',
  },
  {
    letter: 'غ',
    name: 'Ghayn',
    nameAr: 'غَيْن',
    canConnectLeft: true,
    isolated: 'غ',
    initial: 'غـ',
    medial: 'ـغـ',
    final: 'ـغ',
  },
  {
    letter: 'ف',
    name: 'Faa',
    nameAr: 'فَاء',
    canConnectLeft: true,
    isolated: 'ف',
    initial: 'فـ',
    medial: 'ـفـ',
    final: 'ـف',
  },
  {
    letter: 'ق',
    name: 'Qaaf',
    nameAr: 'قَاف',
    canConnectLeft: true,
    isolated: 'ق',
    initial: 'قـ',
    medial: 'ـقـ',
    final: 'ـق',
  },
  {
    letter: 'ك',
    name: 'Kaaf',
    nameAr: 'كَاف',
    canConnectLeft: true,
    isolated: 'ك',
    initial: 'كـ',
    medial: 'ـكـ',
    final: 'ـك',
  },
  {
    letter: 'ل',
    name: 'Laam',
    nameAr: 'لاَم',
    canConnectLeft: true,
    isolated: 'ل',
    initial: 'لـ',
    medial: 'ـلـ',
    final: 'ـل',
  },
  {
    letter: 'م',
    name: 'Meem',
    nameAr: 'مِيم',
    canConnectLeft: true,
    isolated: 'م',
    initial: 'مـ',
    medial: 'ـمـ',
    final: 'ـم',
  },
  {
    letter: 'ن',
    name: 'Noon',
    nameAr: 'نُون',
    canConnectLeft: true,
    isolated: 'ن',
    initial: 'نـ',
    medial: 'ـنـ',
    final: 'ـن',
  },
  {
    letter: 'ه',
    name: 'Haa',
    nameAr: 'هَاء',
    canConnectLeft: true,
    isolated: 'ه',
    initial: 'هـ',
    medial: 'ـهـ',
    final: 'ـه',
  },
  {
    letter: 'و',
    name: 'Waaw',
    nameAr: 'وَاو',
    canConnectLeft: false,
    isolated: 'و',
    initial: 'و',
    medial: 'ـو',
    final: 'ـو',
  },
  {
    letter: 'ي',
    name: 'Yaa',
    nameAr: 'يَاء',
    canConnectLeft: true,
    isolated: 'ي',
    initial: 'يـ',
    medial: 'ـيـ',
    final: 'ـي',
  },
];

export const LATIN_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

export const FRENCH_COMMON_WORDS = [
  'Maman',
  'Papa',
  'École',
  'Cahier',
  'Maison',
  'Bonjour',
  'Soleil',
  'Jardin',
  'Amour',
  'Papillon',
  'Chocolat',
  'Étoile',
];

export const ARABIC_COMMON_WORDS = [
  'أُمِّي',
  'أَبِي',
  'مَدْرَسَة',
  'كِتَاب',
  'بَيْت',
  'صَبَاحُ الخَيْر',
  'شَمْس',
  'حَدِيقَة',
  'قَلَم',
  'فَرَاشَة',
  'نَجْمَة',
  'زَهْرَة',
];

export const ENGLISH_COMMON_WORDS = [
  'Mom',
  'Dad',
  'School',
  'Book',
  'House',
  'Hello',
  'Sun',
  'Garden',
  'Star',
  'Butterfly',
  'Apple',
  'Friend',
];
