import { CertificateTemplateId, CertificateTypeId } from '../../types/plannerAndCertificates';

export interface CertificateTemplateConfig {
  id: CertificateTemplateId;
  name: string;
  nameFr: string;
  nameAr: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  borderColor: string;
  bgGradient: string;
  titleFont: string;
  nameFont: string;
  borderStyle: 'ornate_gold' | 'royal_double' | 'rainbow_stars' | 'floral_wreath' | 'modern_clean' | 'graduation_classic' | 'sport_dynamic';
  stampBadgeColor: string;
  badgeEmoji: string;
}

export const CERTIFICATE_TEMPLATES: Record<CertificateTemplateId, CertificateTemplateConfig> = {
  classic_gold: {
    id: 'classic_gold',
    name: 'Classic Gold Guilloché',
    nameFr: 'Or Classique & Prestige',
    nameAr: 'الذهبي الأكاديمي الفاخر',
    description: 'Bordure dorée ornementale, médaillon prestige et typographie solennelle pour distinctions officielles.',
    primaryColor: '#854D0E',
    secondaryColor: '#CA8A04',
    accentColor: '#FEF08A',
    borderColor: '#D97706',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 60%, #FEF9C3 100%)',
    titleFont: 'Outfit, serif',
    nameFont: 'Patrick Hand, cursive, serif',
    borderStyle: 'ornate_gold',
    stampBadgeColor: '#B45309',
    badgeEmoji: '🥇',
  },
  royal_blue: {
    id: 'royal_blue',
    name: 'Royal Blue Academic',
    nameFr: 'Bleu Royal & Or',
    nameAr: 'الأزرق الملكي والذهبي',
    description: 'Double cadre bleu nuit et or, ruban académique et allure officielle de remise des diplômes.',
    primaryColor: '#1E3A8A',
    secondaryColor: '#2563EB',
    accentColor: '#DBEAFE',
    borderColor: '#1D4ED8',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 60%, #EFF6FF 100%)',
    titleFont: 'Outfit, sans-serif',
    nameFont: 'Patrick Hand, cursive, sans-serif',
    borderStyle: 'royal_double',
    stampBadgeColor: '#1E40AF',
    badgeEmoji: '🎓',
  },
  kids_rainbow: {
    id: 'kids_rainbow',
    name: 'Kids Rainbow Fun',
    nameFr: 'Arc-en-Ciel Maternelle',
    nameAr: 'قوس قزح البهيج للصغار',
    description: 'Cadre multicolore festif avec ballons, étoiles et récompenses chaleureuses pour enfants.',
    primaryColor: '#E11D48',
    secondaryColor: '#F59E0B',
    accentColor: '#ECFDF5',
    borderColor: '#F43F5E',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 70%, #FFF1F2 100%)',
    titleFont: 'Comic Neue, cursive, sans-serif',
    nameFont: 'Schoolbell, cursive, sans-serif',
    borderStyle: 'rainbow_stars',
    stampBadgeColor: '#E11D48',
    badgeEmoji: '🌈',
  },
  little_stars: {
    id: 'little_stars',
    name: 'Little Stars Achievement',
    nameFr: 'Petites Étoiles du Savoir',
    nameAr: 'نجوم التميز والاجتهاد',
    description: 'Constellation d’étoiles scintillantes et félicitations chaleureuses pour les premiers succès scolaires.',
    primaryColor: '#7C3AED',
    secondaryColor: '#F59E0B',
    accentColor: '#FAF5FF',
    borderColor: '#8B5CF6',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 65%, #F5F3FF 100%)',
    titleFont: 'Outfit, sans-serif',
    nameFont: 'Patrick Hand, cursive, sans-serif',
    borderStyle: 'rainbow_stars',
    stampBadgeColor: '#7C3AED',
    badgeEmoji: '⭐',
  },
  modern_minimal: {
    id: 'modern_minimal',
    name: 'Modern Minimalist',
    nameFr: 'Minimaliste Contemporain',
    nameAr: 'العصري الأنيق الهادئ',
    description: 'Design contemporain sobre, géométrie raffinée et espacement parfait pour collégiens et lycéens.',
    primaryColor: '#0F172A',
    secondaryColor: '#475569',
    accentColor: '#F1F5F9',
    borderColor: '#0F172A',
    bgGradient: '#FFFFFF',
    titleFont: 'Outfit, sans-serif',
    nameFont: 'Outfit, sans-serif',
    borderStyle: 'modern_clean',
    stampBadgeColor: '#0F172A',
    badgeEmoji: '📜',
  },
  floral_elegance: {
    id: 'floral_elegance',
    name: 'Floral Botanical',
    nameFr: 'Botanique & Végétal',
    nameAr: 'الزهور واللمسة الطبيعية',
    description: 'Couronne de lauriers et feuillages délicats en teintes sauge et eucalyptus pour fêtes de fin d’année.',
    primaryColor: '#065F46',
    secondaryColor: '#059669',
    accentColor: '#ECFDF5',
    borderColor: '#10B981',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 65%, #ECFDF5 100%)',
    titleFont: 'Outfit, serif',
    nameFont: 'Patrick Hand, cursive, serif',
    borderStyle: 'floral_wreath',
    stampBadgeColor: '#047857',
    badgeEmoji: '🌿',
  },
  graduation_celebration: {
    id: 'graduation_celebration',
    name: 'Graduation Day',
    nameFr: 'Cérémonie de Promotion',
    nameAr: 'حفل التخرج السنوي',
    description: 'Toque de diplômé, rubans d’honneur et sceau officiel de validation de fin de cycle.',
    primaryColor: '#831843',
    secondaryColor: '#BE185D',
    accentColor: '#FDF2F8',
    borderColor: '#9D174D',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 65%, #FDF2F8 100%)',
    titleFont: 'Outfit, serif',
    nameFont: 'Schoolbell, cursive, serif',
    borderStyle: 'graduation_classic',
    stampBadgeColor: '#9D174D',
    badgeEmoji: '🎖️',
  },
  excellence_award: {
    id: 'excellence_award',
    name: 'Presidential Excellence',
    nameFr: 'Prix d’Excellence & Mérite',
    nameAr: 'وسام الامتياز والشرف',
    description: 'Médaille d’or et ruban tricolore, félicitations formelles de l’équipe pédagogique.',
    primaryColor: '#B45309',
    secondaryColor: '#D97706',
    accentColor: '#FFFBEB',
    borderColor: '#F59E0B',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 60%, #FEF3C7 100%)',
    titleFont: 'Outfit, serif',
    nameFont: 'Patrick Hand, cursive, serif',
    borderStyle: 'ornate_gold',
    stampBadgeColor: '#B45309',
    badgeEmoji: '🏆',
  },
  sport_achievement: {
    id: 'sport_achievement',
    name: 'Sports & Olympics',
    nameFr: 'Exploit Sportif & EPS',
    nameAr: 'الإنجاز الرياضي والأولمبي',
    description: 'Dynamisme, couronne athlétique et trophée pour tournois scolaires et olympiades de fin d’année.',
    primaryColor: '#C2410C',
    secondaryColor: '#EA580C',
    accentColor: '#FFF7ED',
    borderColor: '#F97316',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 70%, #FFF7ED 100%)',
    titleFont: 'Outfit, sans-serif',
    nameFont: 'Patrick Hand, cursive, sans-serif',
    borderStyle: 'sport_dynamic',
    stampBadgeColor: '#C2410C',
    badgeEmoji: '🏅',
  },
  kawaii_achievement: {
    id: 'kawaii_achievement',
    name: 'Kawaii Champion',
    nameFr: 'Super Champion Kawaii',
    nameAr: 'البطل الصغير الكواي',
    description: 'Mascottes mignonnes, étoiles douces et encouragements bienveillants.',
    primaryColor: '#DB2777',
    secondaryColor: '#F472B6',
    accentColor: '#FDF2F8',
    borderColor: '#F472B6',
    bgGradient: 'radial-gradient(ellipse at center, #FFFFFF 65%, #FDF2F8 100%)',
    titleFont: 'Comic Neue, cursive, sans-serif',
    nameFont: 'Schoolbell, cursive, sans-serif',
    borderStyle: 'rainbow_stars',
    stampBadgeColor: '#DB2777',
    badgeEmoji: '🌟',
  },
};

export const CERTIFICATE_PRESETS: Record<CertificateTypeId, {
  title: string;
  subtitle: string;
  awardTitle: string;
  reasonText: string;
}> = {
  encouragement: {
    title: "DIPLÔME D'ENCOURAGEMENT",
    subtitle: 'Décerné avec les chaleureuses félicitations de l’équipe enseignante à',
    awardTitle: 'Pour ses efforts remarquables et ses progrès constants',
    reasonText: 'En reconnaissance de son investissement quotidien, de sa persévérance face aux apprentissages et de sa belle attitude en classe.',
  },
  excellence: {
    title: "PRIX D'EXCELLENCE",
    subtitle: 'La Direction et le Conseil des Professeurs décernent ce titre d’honneur à',
    awardTitle: 'Major de Promotion & Félicitations du Jury',
    reasonText: 'Pour l’excellence exceptionnelle de ses résultats académiques, sa rigueur constante et son exemplarité tout au long de l’année scolaire.',
  },
  reussite: {
    title: 'CERTIFICAT DE RÉUSSITE',
    subtitle: 'Attestation solennelle remise avec grande fierté à',
    awardTitle: 'Validation complète des compétences du cycle',
    reasonText: 'Ayant satisfait avec succès à l’ensemble des évaluations et fait preuve d’une remarquable assiduité dans ses devoirs.',
  },
  brevet_fin_annee: {
    title: 'DIPLÔME DE FIN D’ANNÉE',
    subtitle: 'Célébration du passage de classe et fin de cycle décernée à',
    awardTitle: 'Passage en classe supérieure avec mention',
    reasonText: 'Pour avoir franchi cette étape clé avec enthousiasme, curiosité intellectuelle et esprit de camaraderie.',
  },
  participation: {
    title: 'CERTIFICAT DE PARTICIPATION',
    subtitle: 'Témoignage de reconnaissance officielle attribué à',
    awardTitle: 'Implication active & Esprit d’initiative',
    reasonText: 'Pour sa contribution enthousiaste, son écoute et sa bienveillance lors de notre projet scolaire.',
  },
  merite: {
    title: 'DIPLÔME DU MÉRITE SCOLAIRE',
    subtitle: 'Distinction spéciale remise à l’élève méritant(e)',
    awardTitle: 'Pour sa régularité exemplaire et son dévouement',
    reasonText: 'Pour sa remarquable persévérance, son respect des règles de vie commune et son sens de l’entraide auprès de ses camarades.',
  },
  lecture: {
    title: 'PRIX DU GRAND LECTEUR',
    subtitle: 'Le Défi Lecture décerne son trophée littéraire à',
    awardTitle: 'Champion de Lecture & Découverte de Livres',
    reasonText: 'Pour sa passion dévorante des récits, son imagination féconde et sa curiosité pour les beaux livres de notre bibliothèque.',
  },
  sport: {
    title: 'DIPLÔME DU CHAMPION SPORTIF',
    subtitle: 'Attestation de performance athlétique remise à',
    awardTitle: 'Fair-play, endurance et esprit d’équipe',
    reasonText: 'Pour son dépassement de soi, sa ténacité lors des tournois et son respect admirable de l’esprit sportif olympique.',
  },
  creativite: {
    title: 'PRIX DU JEUNE ARTISTE',
    subtitle: 'Atelier d’Arts Plastiques & Création décerne ce prix à',
    awardTitle: 'Imagination, talent artistique et originalité',
    reasonText: 'Pour la finesse de ses réalisations graphiques, son sens harmonieux des couleurs et sa sensibilité poétique.',
  },
  personnalise: {
    title: 'DIPLÔME D’HONNEUR',
    subtitle: 'Présenté solennellement à',
    awardTitle: 'Distinction Spéciale',
    reasonText: 'En hommage à ses remarquables qualités personnelles et à son parcours scolaire remarquable.',
  },
};
