/**
 * SUBJECT_REGISTRY — Central Registry for all 26 School Notebook Subjects
 * 
 * Strict Architecture Rules:
 * 1. 26 Subjects × 12 Templates = 312 Subject/Template Combinations.
 * 2. Hard Subject Lock: att_2 is the sole source of truth.
 * 3. AI artwork is strictly visual with NO readable text (anti-hallucination).
 * 4. Programmatic rendering of att_3 (main title) in template.titleZone.
 * 5. Programmatic rendering of att_4..att_7 in template.infoZone.
 */

import { NotebookPageFormat } from '../types';

export type SubjectLanguage = 'ar' | 'fr' | 'en' | 'mixed';
export type TextDirection = 'rtl' | 'ltr';

export interface LayoutZone {
  x: number; // percentage from left (0 to 100)
  y: number; // percentage from top (0 to 100)
  width: number; // percentage width (0 to 100)
  height: number; // percentage height (0 to 100)
}

export interface TitleZone extends LayoutZone {
  textAlign: 'center' | 'right' | 'left';
  verticalAlign: 'top' | 'middle' | 'bottom';
  fontFamily: string;
  fontWeight: string;
  minFontSize: number;
  maxFontSize: number;
  lineHeight: number;
  textEffects: {
    color: string;
    backgroundPlate: boolean;
    plateColor?: string;
    plateBorder?: string;
    plateShadow?: string;
    shadow?: string;
  };
}

export interface InfoZone extends LayoutZone {
  styleVariant: 'card' | 'badge' | 'minimal' | 'glass' | 'framed';
  backgroundColor: string;
  borderColor: string;
  textColor: string;
  accentColor: string;
  borderRadius: number;
  padding: number;
}

export type ArtDirectionId =
  | 'premium_school'
  | 'cute_school'
  | 'paper_craft'
  | 'doodle_academy'
  | 'luxury_education'
  | 'magic_school'
  | 'future_school'
  | 'nature_academy'
  | 'adventure'
  | 'minimal_premium'
  | 'cartoon_world'
  | 'clay_world';

export interface CoverTemplate {
  id: number; // 1 to 12
  subjectId: string;
  name: string;
  artDirection: ArtDirectionId;
  artDirectionName: string;
  palette: string[];
  illustrationStyle: string;
  primaryObjects: string[];
  secondaryObjects: string[];
  backgroundStyle: string;
  borderStyle: string;
  composition: string;
  compositionRules: string;
  titleZone: TitleZone & {
    styleVariant: '3d_premium' | 'cute_playful' | 'paper_cut' | 'doodle_sketch' | 'luxury_editorial';
  };
  infoZone: InfoZone & {
    customCardStyle: 'premium_3d' | 'cute_kawaii' | 'paper_relief' | 'doodle_sheet' | 'luxury_filigree';
  };
  decorativeZones: LayoutZone[];
  forbiddenZones: LayoutZone[];
  imagePrompt?: string;
  illustrationPrompt: string;
  negativePrompt: string;
  bgSvgGenerator?: (w: number, h: number) => string;
}

export interface SubjectDefinition {
  id: string;
  label: string;
  language: SubjectLanguage;
  direction: TextDirection;
  palette: string[];
  allowedObjects: string[];
  forbiddenObjects: string[];
  illustrationStyle: string;
  heroObjects?: string[];
  secondaryObjects?: string[];
  backgroundAtmosphere?: string;
  borderDesign?: string;
  compositionStructure?: string;
  lowerSceneDescription?: string;
  titleStyle: {
    fontFamily: string;
    fontWeight: string;
    defaultColor: string;
    badgeBg: string;
    badgeText: string;
  };
  templates: CoverTemplate[];
}

export const MINIMAL_QUALITY_PROMPT =
  'Premium professional school notebook cover, commercial stationery design, highly detailed editorial composition, rich subject-specific educational illustrations, balanced visual hierarchy, professional border, polished background, depth and dimensionality, premium children educational publishing quality, print-ready aesthetic, carefully composed decorative objects, harmonious empty zones reserved for title and student information, no readable text.';

export const GLOBAL_NEGATIVE_PROMPT =
  'simple gradient background, empty abstract background, generic SaaS UI, website card design, presentation slide, mobile app interface, random geometric shapes only, low-detail illustration, flat empty poster, poor composition, cheap template, unrelated subject, wrong educational objects, random readable text, watermark, logo generated by AI, duplicated objects, cropped objects, bad anatomy, visual clutter behind text zones, cahier d exercices, devoirs, text, words, letters, labels';

export const ACTIVE_MODEL_COUNT = 5;

/**
 * 12 Distinct Graphic Models / Artistic Directions
 * First 5 are actively deployed for all 26 subjects.
 * 7 subsequent models are structured and ready for Phase 2.
 */
export const ART_DIRECTIONS: {
  id: number;
  artDirection: ArtDirectionId;
  name: string;
  artDirectionName: string;
  styleDescription: string;
  illustrationStyle: string;
  backgroundStyle: string;
  borderStyle: string;
  composition: string;
  compositionRules: string;
  titleY: number;
  titleH: number;
  titleW: number;
  titleX: number;
  titleStyleVariant: '3d_premium' | 'cute_playful' | 'paper_cut' | 'doodle_sketch' | 'luxury_editorial';
  infoY: number;
  infoH: number;
  infoW: number;
  infoX: number;
  infoStyleVariant: 'card' | 'badge' | 'minimal' | 'glass' | 'framed';
  infoCustomCardStyle: 'premium_3d' | 'cute_kawaii' | 'paper_relief' | 'doodle_sheet' | 'luxury_filigree';
  infoBorderRadius: number;
  plate: boolean;
}[] = [
  // MODEL_01 — PREMIUM SCHOOL
  {
    id: 1,
    artDirection: 'premium_school',
    name: 'Modèle 01 — Premium School (3D Pro)',
    artDirectionName: 'Premium School',
    styleDescription: '3D premium, moderne, propre, riche. Objets scolaires 3D, formes douces, profondeur, ombres propres, lumière studio, composition commerciale très équilibrée, illustrations détaillées, finition premium.',
    illustrationStyle: 'High-end 3D educational studio render, smooth volumetric curves, soft specular highlights, clean realistic shadows, polished finish',
    backgroundStyle: 'Luminous studio gradient backdrop with subtle ambient light spheres and refined depth',
    borderStyle: 'Modern beveled outer border with rounded corners and delicate metallic inner line',
    composition: 'Heroic 3D subject props centered and framing the composition, pristine floating title zone at top, elevated rounded card below',
    compositionRules: 'Clear visual hierarchy: 3D subject scene centered between 22% and 66%, clean upper zone for title, solid white rounded container for student info',
    titleY: 6,
    titleH: 16,
    titleW: 86,
    titleX: 7,
    titleStyleVariant: '3d_premium',
    infoY: 68,
    infoH: 25,
    infoW: 88,
    infoX: 6,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'premium_3d',
    infoBorderRadius: 20,
    plate: true,
  },
  // MODEL_02 — CUTE SCHOOL
  {
    id: 2,
    artDirection: 'cute_school',
    name: 'Modèle 02 — Cute School (Kawaii Premium)',
    artDirectionName: 'Cute School',
    styleDescription: 'Kawaii premium / illustration scolaire mignonne. Personnages sympathiques, objets avec expressions discrètes, formes arrondies, couleurs douces, composition enfantine mais premium, petits éléments ludiques, profondeur légère.',
    illustrationStyle: 'Gentle Kawaii educational illustration, friendly smiling subject characters with discreet cute facial expressions, soft rounded pastel shapes, sparkling stars',
    backgroundStyle: 'Soft warm pastel canvas adorned with gentle starbursts, floating cloud shapes and playful confetti dots',
    borderStyle: 'Playful scalloped border with pastel candy dashed lines and sweet corner star stamps',
    composition: 'Joyful circular arrangement of smiling subject tools around central canvas, cloud title badge up top, kawaii rounded card at bottom',
    compositionRules: 'Playful yet clean: mascots frame the upper and center areas without interfering with the cloud title pill or the dashed student card',
    titleY: 7,
    titleH: 17,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: 'cute_playful',
    infoY: 69,
    infoH: 25,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'cute_kawaii',
    infoBorderRadius: 26,
    plate: true,
  },
  // MODEL_03 — PAPER CRAFT
  {
    id: 3,
    artDirection: 'paper_craft',
    name: 'Modèle 03 — Paper Craft (Découpe Papier 3D)',
    artDirectionName: 'Paper Craft',
    styleDescription: 'Papier découpé 3D. Couches de papier, silhouettes découpées, ombres douces, relief, illustrations comme faites en carton/papier premium, profondeur par superposition, textures papier.',
    illustrationStyle: '3D layered paper-cut art, realistic die-cut cardboard silhouettes, stepped depth with tactile shadows, artisan craft aesthetic, subtle fibrous paper textures',
    backgroundStyle: 'Layered paper topography cutouts forming a framed natural window in the center with progressive drop shadows',
    borderStyle: 'Scissor-cut layered paper edge with gentle relief and visible tactile cut margin',
    composition: 'Layered stage depth with multi-tiered paper cutouts framing the scene from left, right, and top; paper banner title and stacked cardboard info card',
    compositionRules: 'Multi-layer depth: concentric paper layers frame the title and central subject tools, student card looks like stacked die-cut paper',
    titleY: 9,
    titleH: 16,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: 'paper_cut',
    infoY: 67,
    infoH: 26,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'paper_relief',
    infoBorderRadius: 14,
    plate: true,
  },
  // MODEL_04 — DOODLE ACADEMY
  {
    id: 4,
    artDirection: 'doodle_academy',
    name: 'Modèle 04 — Doodle Academy (Carnet Illustré)',
    artDirectionName: 'Doodle Academy',
    styleDescription: 'Illustration dessinée professionnelle. Doodles, petits objets dessinés, lignes dynamiques, symboles scolaires, composition riche, cadres illustrés, petits détails autour du contenu principal, style cahier/école premium, coloré, propre et commercial.',
    illustrationStyle: 'Professional hand-drawn sketchbook doodles, clean ink outlines with vibrant energetic color fills, dynamic hatching, playful notebook symbols, rich and lively',
    backgroundStyle: 'Off-white sketchbook paper background with subtle graph grid and dense decorative scholastic doodles along the borders',
    borderStyle: 'Hand-drawn marker border with doodle corner flourishes and washi tape banner accents',
    composition: 'Full-perimeter illustrated doodle frame encircling the central canvas; sketchbook title banner at top, grid-sheet student card at bottom',
    compositionRules: 'Energetic doodles occupy all four edges and corners, leaving pure white space for title banner and notebook student card',
    titleY: 7,
    titleH: 17,
    titleW: 86,
    titleX: 7,
    titleStyleVariant: 'doodle_sketch',
    infoY: 66,
    infoH: 27,
    infoW: 88,
    infoX: 6,
    infoStyleVariant: 'framed',
    infoCustomCardStyle: 'doodle_sheet',
    infoBorderRadius: 10,
    plate: true,
  },
  // MODEL_05 — LUXURY EDUCATION
  {
    id: 5,
    artDirection: 'luxury_education',
    name: 'Modèle 05 — Luxury Education (Haut de Gamme Éditorial)',
    artDirectionName: 'Luxury Education',
    styleDescription: 'Haut de gamme éditorial. Papier texturé, effets embossés, dorures légères, détails fins, bordures sophistiquées, palette plus élégante, composition éditoriale, éléments premium, moins enfantin mais toujours scolaire.',
    illustrationStyle: 'Prestigious editorial stationery design, delicate hot-stamped gold foil motifs, embossed relief lines, classical academic heraldry, fine filigree engraving',
    backgroundStyle: 'Deep noble linen-textured background with vintage watermark patterns and delicate gold filigree corner ornaments',
    borderStyle: 'Double gold-foil pinstripe frame with ornate classical corner rosettes and laurel leaf garlands',
    composition: 'Architectural classical symmetry, central academic medallion, royal crest title plaque at top, engraved ivory cartouche below',
    compositionRules: 'High-end symmetry: elegant heraldic laurel emblems frame the title and corners, ivory cartouche with double gold rule for student info',
    titleY: 8,
    titleH: 15,
    titleW: 82,
    titleX: 9,
    titleStyleVariant: 'luxury_editorial',
    infoY: 68,
    infoH: 25,
    infoW: 84,
    infoX: 8,
    infoStyleVariant: 'framed',
    infoCustomCardStyle: 'luxury_filigree',
    infoBorderRadius: 8,
    plate: true,
  },
  // MODEL_06 — MAGIC SCHOOL (Phase 2 Archetype)
  {
    id: 6,
    artDirection: 'magic_school',
    name: 'Modèle 06 — Magic School (Univers Magique)',
    artDirectionName: 'Magic School',
    styleDescription: 'Étoiles lumineuses, objets scolaires flottants, univers enchanté et fantastique.',
    illustrationStyle: 'Enchanted academy style, floating glowing educational artifacts, ethereal star trails',
    backgroundStyle: 'Deep celestial violet canvas with golden constellations',
    borderStyle: 'Arcane filigree borders with glowing corner runes',
    composition: 'Floating magical objects orbiting the central axis',
    compositionRules: 'Luminous sparkles guide eye to title plaque; clean crystal card below',
    titleY: 8,
    titleH: 16,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: '3d_premium',
    infoY: 67,
    infoH: 26,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'premium_3d',
    infoBorderRadius: 18,
    plate: true,
  },
  // MODEL_07 — FUTURE SCHOOL (Phase 2 Archetype)
  {
    id: 7,
    artDirection: 'future_school',
    name: 'Modèle 07 — Future School (Cyber Académie)',
    artDirectionName: 'Future School',
    styleDescription: 'Futuriste, hologrammes éducatifs, néons doux et technologie moderne.',
    illustrationStyle: 'Cyber-pedagogic aesthetic, clean isometric holograms and soft neon trace lines',
    backgroundStyle: 'Dark cyber slate background with glowing cyan circuit grid',
    borderStyle: 'High-tech chamfered HUD border with digital corner markers',
    composition: 'Holographic subject projection in center with sci-fi title plate',
    compositionRules: 'Digital HUD framing with crisp glowing margins',
    titleY: 7,
    titleH: 16,
    titleW: 86,
    titleX: 7,
    titleStyleVariant: '3d_premium',
    infoY: 68,
    infoH: 25,
    infoW: 88,
    infoX: 6,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'premium_3d',
    infoBorderRadius: 12,
    plate: true,
  },
  // MODEL_08 — NATURE ACADEMY (Phase 2 Archetype)
  {
    id: 8,
    artDirection: 'nature_academy',
    name: 'Modèle 08 — Nature Academy (Botanique & Éco-École)',
    artDirectionName: 'Nature Academy',
    styleDescription: 'Feuilles, fleurs douces, nature vivante entrelacée avec les objets scolaires.',
    illustrationStyle: 'Lush botanical illustration, watercolor foliage entangling subject instruments',
    backgroundStyle: 'Organic recycled parchment texture with pressed flower silhouettes',
    borderStyle: 'Flowing vine border with delicate leaves and buds',
    composition: 'Botanical wreath encircling central educational motifs',
    compositionRules: 'Natural organic framing leaving central upper and lower zones pristine',
    titleY: 8,
    titleH: 16,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: 'paper_cut',
    infoY: 68,
    infoH: 25,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'paper_relief',
    infoBorderRadius: 20,
    plate: true,
  },
  // MODEL_09 — ADVENTURE (Phase 2 Archetype)
  {
    id: 9,
    artDirection: 'adventure',
    name: 'Modèle 09 — Adventure (Exploration & Découverte)',
    artDirectionName: 'Adventure',
    styleDescription: 'Exploration cartographique, voyage, parchemins et découvertes historiques.',
    illustrationStyle: 'Expedition cartography style, vintage travel compasses and discovery journals',
    backgroundStyle: 'Antique treasure map watermark on warm sepia canvas',
    borderStyle: 'Nautical rope and compass-rose corner flourishes',
    composition: 'Exploration gear framing a panoramic discovery landscape',
    compositionRules: 'Expedition theme with antique parchment student log card',
    titleY: 8,
    titleH: 16,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: 'luxury_editorial',
    infoY: 68,
    infoH: 25,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'framed',
    infoCustomCardStyle: 'luxury_filigree',
    infoBorderRadius: 10,
    plate: true,
  },
  // MODEL_10 — MINIMAL PREMIUM (Phase 2 Archetype)
  {
    id: 10,
    artDirection: 'minimal_premium',
    name: 'Modèle 10 — Minimal Premium (Design Suisse Épuré)',
    artDirectionName: 'Minimal Premium',
    styleDescription: 'Composition épurée, espace négatif généreux, typographie et grille architecturales.',
    illustrationStyle: 'Swiss modernist educational layout, single heroic subject sculpture with pristine negative space',
    backgroundStyle: 'Architectural pure off-white paper with subtle tactile texture',
    borderStyle: 'Ultra-thin hairline framing with precise mathematical corner brackets',
    composition: 'Single focal educational object floating in generous negative space',
    compositionRules: 'Maximal air and breathability, clean geometric typography',
    titleY: 10,
    titleH: 15,
    titleW: 80,
    titleX: 10,
    titleStyleVariant: 'luxury_editorial',
    infoY: 68,
    infoH: 24,
    infoW: 82,
    infoX: 9,
    infoStyleVariant: 'minimal',
    infoCustomCardStyle: 'premium_3d',
    infoBorderRadius: 6,
    plate: false,
  },
  // MODEL_11 — CARTOON WORLD (Phase 2 Archetype)
  {
    id: 11,
    artDirection: 'cartoon_world',
    name: 'Modèle 11 — Cartoon World (Animation & Narration)',
    artDirectionName: 'Cartoon World',
    styleDescription: 'Illustration animée dynamique, scène narrative riche et personnages vivants.',
    illustrationStyle: 'Animated feature film concept art, dynamic character poses and warm lighting',
    backgroundStyle: 'Lively illustrated schoolroom environment in warm gouache tones',
    borderStyle: 'Film-strip and sticker-accented borders with vibrant corners',
    composition: 'Dynamic action scene of student characters exploring the subject',
    compositionRules: 'Narrative storytelling with speech-bubble title plaque',
    titleY: 7,
    titleH: 17,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: 'cute_playful',
    infoY: 69,
    infoH: 25,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'cute_kawaii',
    infoBorderRadius: 22,
    plate: true,
  },
  // MODEL_12 — CLAY WORLD (Phase 2 Archetype)
  {
    id: 12,
    artDirection: 'clay_world',
    name: 'Modèle 12 — Clay World (Pâte à Modeler 3D)',
    artDirectionName: 'Clay World',
    styleDescription: 'Figurines et objets scolaires miniatures en pâte à modeler et argile texturée.',
    illustrationStyle: 'Stop-motion claymation plasticine 3D render, tactile fingerprints and handmade warmth',
    backgroundStyle: 'Warm cardboard backdrop with colorful clay specks and soft shadows',
    borderStyle: 'Molded clay strip border with rounded thumb-pressed corners',
    composition: 'Handcrafted plasticine subject models resting on wooden table',
    compositionRules: 'Tactile handmade charm with clay slab title and info plaques',
    titleY: 8,
    titleH: 16,
    titleW: 84,
    titleX: 8,
    titleStyleVariant: '3d_premium',
    infoY: 68,
    infoH: 25,
    infoW: 86,
    infoX: 7,
    infoStyleVariant: 'card',
    infoCustomCardStyle: 'premium_3d',
    infoBorderRadius: 18,
    plate: true,
  },
];

/**
 * Generates 12 distinct templates for a given subject definition
 */
function buildSubjectTemplates(
  subjectId: string,
  subjectLabel: string,
  direction: TextDirection,
  palette: string[],
  allowedObjects: string[],
  forbiddenObjects: string[]
): CoverTemplate[] {
  const primaryColor = palette[0] || '#2563EB';
  const secondaryColor = palette[1] || '#0D9488';
  const bgColor = palette[2] || '#F8FAFC';
  const accentColor = palette[3] || '#F59E0B';

  const primarySubset = allowedObjects.slice(0, 4);
  const secondarySubset = allowedObjects.slice(4);

  return ART_DIRECTIONS.map((arch) => {
    const titleZone: TitleZone & {
      styleVariant: '3d_premium' | 'cute_playful' | 'paper_cut' | 'doodle_sketch' | 'luxury_editorial';
    } = {
      x: arch.titleX,
      y: arch.titleY,
      width: arch.titleW,
      height: arch.titleH,
      textAlign: 'center',
      verticalAlign: 'middle',
      fontFamily: direction === 'rtl' ? 'Cairo, Tajawal, sans-serif' : 'Outfit, Plus Jakarta Sans, sans-serif',
      fontWeight: '800',
      minFontSize: 16,
      maxFontSize: 34,
      lineHeight: 1.25,
      styleVariant: arch.titleStyleVariant,
      textEffects: {
        color: arch.plate ? '#FFFFFF' : primaryColor,
        backgroundPlate: arch.plate,
        plateColor: arch.plate ? primaryColor : 'transparent',
        plateBorder: arch.plate ? `${secondaryColor}80` : 'transparent',
        plateShadow: arch.plate ? '0 10px 25px -5px rgba(0,0,0,0.18)' : 'none',
        shadow: arch.plate ? '0 2px 4px rgba(0,0,0,0.3)' : '0 2px 8px rgba(255,255,255,0.9)',
      },
    };

    const infoZone: InfoZone & {
      customCardStyle: 'premium_3d' | 'cute_kawaii' | 'paper_relief' | 'doodle_sheet' | 'luxury_filigree';
    } = {
      x: arch.infoX,
      y: arch.infoY,
      width: arch.infoW,
      height: arch.infoH,
      styleVariant: arch.infoStyleVariant,
      customCardStyle: arch.infoCustomCardStyle,
      backgroundColor: arch.artDirection === 'luxury_education' ? 'rgba(252, 251, 247, 0.98)' : 'rgba(255, 255, 255, 0.98)',
      borderColor: `${secondaryColor}70`,
      textColor: '#0F172A',
      accentColor: primaryColor,
      borderRadius: arch.infoBorderRadius,
      padding: 14,
    };

    const decorativeZones: LayoutZone[] = [
      { x: 0, y: arch.titleY + arch.titleH, width: 100, height: arch.infoY - (arch.titleY + arch.titleH) },
      { x: 0, y: 0, width: 100, height: 100 },
    ];

    const forbiddenZones: LayoutZone[] = [
      titleZone,
      infoZone,
    ];

    const illustrationPrompt = [
      MINIMAL_QUALITY_PROMPT,
      `Modèle artistique sélectionné : ${arch.name} (${arch.artDirection}).`,
      `Style visuel : ${arch.illustrationStyle}.`,
      `Style d'arrière-plan : ${arch.backgroundStyle}.`,
      `Style de bordure : ${arch.borderStyle}.`,
      `Règles de composition : ${arch.compositionRules}.`,
      `Matière exclusive (att_2) : ${subjectLabel} (${subjectId}).`,
      `Objets principaux autorisés UNIQUEMENT : ${primarySubset.join(', ')}.`,
      secondarySubset.length > 0 ? `Objets secondaires autorisés : ${secondarySubset.join(', ')}.` : '',
      `Palette chromatique officielle : ${palette.join(', ')}.`,
      `Zone réservée pour le titre : haut du cahier (y: ${arch.titleY}% à ${arch.titleY + arch.titleH}%). Laisser propre et non obstrué.`,
      `Zone réservée pour le cartouche élève : bas du cahier (y: ${arch.infoY}% à ${arch.infoY + arch.infoH}%). Laisser propre et net.`,
      `AUCUN mot, AUCUN texte, AUCUNE lettre dans l'illustration d'arrière-plan.`,
    ].filter(Boolean).join(' ');

    const negativePrompt = [
      GLOBAL_NEGATIVE_PROMPT,
      ...forbiddenObjects,
    ].join(', ');

    return {
      id: arch.id,
      subjectId,
      name: arch.name,
      artDirection: arch.artDirection,
      artDirectionName: arch.artDirectionName,
      palette,
      illustrationStyle: arch.illustrationStyle,
      primaryObjects: primarySubset,
      secondaryObjects: secondarySubset,
      backgroundStyle: arch.backgroundStyle,
      borderStyle: arch.borderStyle,
      composition: arch.composition,
      compositionRules: arch.compositionRules,
      titleZone,
      infoZone,
      decorativeZones,
      forbiddenZones,
      imagePrompt: illustrationPrompt,
      illustrationPrompt,
      negativePrompt,
    };
  });
}

/**
 * 26 SUBJECT DEFINITIONS (SECTION 5 OF SPECIFICATION)
 */
export const RAW_SUBJECTS: Omit<SubjectDefinition, 'templates'>[] = [
  // 01. كرّاس الرياضيات
  {
    id: 'maths',
    label: 'كرّاس الرياضيات',
    language: 'ar',
    direction: 'rtl',
    palette: ['#1D4ED8', '#0284C7', '#F0F9FF', '#FFFFFF', '#38BDF8'],
    allowedObjects: ['numbers', '+ − × ÷', 'ruler', 'calculator', 'compass', 'triangles', 'circles', 'geometric shapes', 'cube', 'protractor'],
    forbiddenObjects: ['plants', 'microscope', 'french text', 'cahier d exercices', 'history maps', 'paint palette'],
    illustrationStyle: 'Modern geometric educational vector art, clean mathematical shapes and blue harmonies',
    heroObjects: ['gleaming isometric 3D blue geometric cube', 'golden brass drafting compass with graphite tip', 'frosted transparent set-square triangle ruler and protractor'],
    secondaryObjects: ['delicate floating math symbols (+, −, ×, ÷, =)', 'neat drafting grid lines', 'subtle mathematical circle arcs and coordinate axes'],
    backgroundAtmosphere: 'Sophisticated technical blueprint paper grid background in crisp azure and soft sky blue hues with clean radial studio lighting',
    borderDesign: 'Precision technical drafting border with subtle centimeter calibrations and rounded corner brackets',
    compositionStructure: 'Framed architectural layout; upper quadrant reserved clean for programmatic title, bottom 35% enriched with technical drawing tools on a desk, center open',
    lowerSceneDescription: 'An organized student drafting desk featuring an open geometry set, polished triangle ruler, brass compass, and crisp isometric solids nestled among clean technical coordinate lines',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#1D4ED8', badgeBg: '#1D4ED8', badgeText: '#FFFFFF' },
  },

  // 02. كرّاس الإيقاظ العلمي
  {
    id: 'eveil_scientifique',
    label: 'كرّاس الإيقاظ العلمي',
    language: 'ar',
    direction: 'rtl',
    palette: ['#7C3AED', '#0D9488', '#F5F3FF', '#CCFBF1', '#8B5CF6'],
    allowedObjects: ['microscope', 'planets', 'DNA helix', 'atoms', 'test tubes', 'plants', 'scientific exploration', 'magnifying glass', 'beaker'],
    forbiddenObjects: ['numbers + -', 'calculator', 'french words', 'cahier d exercices', 'music notes'],
    illustrationStyle: 'Vibrant scientific exploration style, cosmic and laboratory motifs, turquoise and violet palette',
    heroObjects: ['sleek optical student microscope with brass adjustment knobs', 'glowing glass laboratory beaker with bubbling teal liquid', 'orbital atom model with vibrant electrons', 'spiraling DNA double helix'],
    secondaryObjects: ['sprouting green seedling in a glass flask', 'ringed miniature planet with stardust trail', 'brass handheld magnifying glass', 'floating effervescent bubbles'],
    backgroundAtmosphere: 'Luminous deep teal and violet cosmos-laboratory fusion canvas with ambient glowing scientific constellation lines and clean gradient depth',
    borderDesign: 'High-tech observatory border featuring delicate molecular bond links and smooth curved corner shields',
    compositionStructure: 'Exploration observatory frame; top reserved for title plaque, bottom 38% populated with vibrant laboratory equipment and celestial globes, center clean',
    lowerSceneDescription: 'A glowing school science discovery bench with an optical microscope, bubbling Erlenmeyer flasks, a fresh green sprout in a test tube, and orbiting atomic particles glowing softly',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#7C3AED', badgeBg: '#7C3AED', badgeText: '#FFFFFF' },
  },

  // 03. Cahier de Français
  {
    id: 'francais',
    label: 'Cahier de Français',
    language: 'fr',
    direction: 'ltr',
    palette: ['#1E3A8A', '#DC2626', '#FEF3C7', '#FFFFFF', '#3B82F6'],
    allowedObjects: ['alphabet', 'books', 'fountain pen', 'pencil', 'letters', 'elegant French educational elements', 'ink pot', 'scroll'],
    forbiddenObjects: ['calculator', 'numbers + -', 'science tubes', 'arabic text', 'cahier d exercices'],
    illustrationStyle: 'Classic elegant French school stationery art, vintage books, fountain pens, royal blue and scarlet',
    heroObjects: ['fine gilded nib fountain pen with glossy royal navy barrel', 'stack of clothbound classical books with bookmark ribbons', 'antique glass inkwell with deep indigo ink droplets'],
    secondaryObjects: ['flowing parchment ribbon scroll', 'gilded vintage brass paperclip', 'delicate wooden dip pen', 'graceful flourishes and ink splashes'],
    backgroundAtmosphere: 'Noble French academic stationery canvas in warm ivory linen texture with discreet royal blue watermark guilloche patterns',
    borderDesign: 'Sophisticated French collegiate border with double pinstripes in royal navy and fine scarlet corner rosettes',
    compositionStructure: 'Bilateral classical balance; upper tier clear for bold title badge, bottom 35% showcasing an author desk composition, center airy and elegant',
    lowerSceneDescription: 'An inspiring student writing table with stacked vintage books, an open leather notebook, a fine fountain pen poised above parchment, and a crystal inkwell',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#1E3A8A', badgeBg: '#1E3A8A', badgeText: '#FFFFFF' },
  },

  // 04. Cahier de production écrite
  {
    id: 'production_ecrite_fr',
    label: 'Cahier de production écrite',
    language: 'fr',
    direction: 'ltr',
    palette: ['#831843', '#DB2777', '#FDF2F8', '#FDE68A', '#BE185D'],
    allowedObjects: ['fountain pen', 'notebook', 'sheets of paper', 'pencil', 'illustrated storytelling', 'feather quill', 'idea lightbulb', 'writing ink'],
    forbiddenObjects: ['microscope', 'compass ruler', 'cahier d exercices', 'arabic calligraphy', 'geography maps'],
    illustrationStyle: 'Poetic creative writing aesthetic, flowing ink droplets, warm paper sheets, rich burgundy and soft pink',
    heroObjects: ['ornate golden feather quill pen', 'glowing incandescent idea lightbulb with golden filament', 'open writer journal with fluttering cream pages'],
    secondaryObjects: ['floating warm ink droplets', 'paper airplane soaring upward', 'wax seal stamp with monogram', 'swirling story ribbon trails'],
    backgroundAtmosphere: 'Soft poetic rose-cream parchment canvas bathed in warm golden dawn light with subtle ink wash gradients',
    borderDesign: 'Delicate storybook scrollwork border with filigree corner flourishes and warm rose-gold pinstripes',
    compositionStructure: 'Whimsical ascending spiral; title zone at top stays clear, bottom 35% features the writing desk where imagination floats upward into the margins',
    lowerSceneDescription: 'A dreamy creative writing workspace with open journal, feather quill pen, golden glowing inspiration bulb, and miniature storybook clouds rising gently',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#831843', badgeBg: '#831843', badgeText: '#FFFFFF' },
  },

  // 05. Cahier de lecture
  {
    id: 'lecture_fr',
    label: 'Cahier de lecture',
    language: 'fr',
    direction: 'ltr',
    palette: ['#1E1B4B', '#EAB308', '#FEFCE8', '#4338CA', '#FDE047'],
    allowedObjects: ['open books', 'library shelves', 'reading glasses', 'stars and imagination emerging from books', 'bookmarks', 'flying pages'],
    forbiddenObjects: ['calculator', 'test tubes', 'cahier d exercices', 'sports gear'],
    illustrationStyle: 'Whimsical dreamlike reading universe, midnight blue atmosphere with golden glowing imagination stars',
    heroObjects: ['illuminated giant open storybook casting warm golden light', 'tortoiseshell round reading spectacles', 'stack of whimsical fairy-tale books with gilded spines'],
    secondaryObjects: ['golden shooting stars emerging from open book pages', 'magical flying book with spread wings', 'tasseled silk bookmark', 'glowing crescent moon sliver'],
    backgroundAtmosphere: 'Enchanting twilight midnight-blue sky canvas sprinkled with warm stardust, nebular glows and dreamlike floating silhouettes',
    borderDesign: 'Celestial library border adorned with miniature golden stars and curved archway corners',
    compositionStructure: 'Imaginative portal composition; top zone clean for title, bottom 40% anchored by a magnificent illuminated open book radiating magical imagination',
    lowerSceneDescription: 'A magical open storybook resting on a vintage wooden shelf, glowing warmly as tiny golden stars, paper lanterns, and floating book pages ascend into the night',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#1E1B4B', badgeBg: '#1E1B4B', badgeText: '#FFFFFF' },
  },

  // 06. Cahier de grammaire
  {
    id: 'grammaire_fr',
    label: 'Cahier de grammaire',
    language: 'fr',
    direction: 'ltr',
    palette: ['#1D4ED8', '#DC2626', '#FFFFFF', '#EFF6FF', '#93C5FD'],
    allowedObjects: ['letters', 'punctuation marks', 'word blocks', 'pencils', 'books', 'speech bubbles', 'quotation marks', 'syntax blocks'],
    forbiddenObjects: ['test tubes', 'microscope', 'cahier d exercices', 'arabic text'],
    illustrationStyle: 'Structured editorial educational design, colorful typography building blocks, crisp primary tones',
    heroObjects: ['3D wooden grammatical modular building blocks', 'bold sculptural question mark and exclamation mark icons', 'crisp red and blue checking pencil with brass ferrule'],
    secondaryObjects: ['smooth dialog speech bubbles', 'quotation marks stylized as glossy jewels', 'stacked syntax bricks', 'neat alphabet reference cards'],
    backgroundAtmosphere: 'Luminous light blue structured French school ruled grid backdrop with clean architectural highlights and shadow play',
    borderDesign: 'Geometric pedagogical frame with alternating red and blue interlocking puzzle-piece corner brackets',
    compositionStructure: 'Orderly modular layout; title zone perfectly framed at top, lower 32% displaying an organized grammatical architecture workbench',
    lowerSceneDescription: 'A tidy grammar workshop scene with colorful interlocking word building blocks, giant decorative punctuation marks, and sharp pencils neatly arranged',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#1D4ED8', badgeBg: '#1D4ED8', badgeText: '#FFFFFF' },
  },

  // 07. English Notebook
  {
    id: 'anglais',
    label: 'English Notebook',
    language: 'en',
    direction: 'ltr',
    palette: ['#EA580C', '#2563EB', '#FEF3C7', '#FFF7ED', '#F97316'],
    allowedObjects: ['ABC letters', 'speech bubbles', 'books', 'pencils', 'yellow school bus', 'educational English elements', 'London bridge motif', 'clock tower silhouette'],
    forbiddenObjects: ['arabic calligraphy', 'cahier d exercices', 'science beakers'],
    illustrationStyle: 'Playful British & international school motifs, warm orange and cobalt blue palette, bold modern shapes',
    heroObjects: ['iconic red British telephone kiosk and double-decker bus silhouette', 'playful oversized 3D ABC wooden alphabet blocks', 'friendly Big Ben clock tower miniature model'],
    secondaryObjects: ['bilingual dialog speech bubble with hello greeting waves', 'classic yellow school pencil', 'vintage postal airmail envelope with red and blue stripes'],
    backgroundAtmosphere: 'Warm creamy amber background featuring subtle world map contours, playful compass roses, and vibrant cobalt blue accents',
    borderDesign: 'Classic international airmail chevron border in vivid cobalt blue, clean white, and warm orange',
    compositionStructure: 'Dynamic cosmopolitan stationery layout; top reserved for English title, lower 36% populated with friendly London and international school icons',
    lowerSceneDescription: 'An energetic English learning corner featuring 3D alphabet blocks, miniature London landmark silhouettes, an open illustrated dialogue booklet, and colorful speech bubbles',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#EA580C', badgeBg: '#EA580C', badgeText: '#FFFFFF' },
  },

  // 08. كرّاس اللغة العربية
  {
    id: 'arabe',
    label: 'كرّاس اللغة العربية',
    language: 'ar',
    direction: 'rtl',
    palette: ['#BE123C', '#F43F5E', '#FFF1F2', '#FDE68A', '#881337'],
    allowedObjects: ['Arabic letters', 'books', 'traditional pen', 'ink pot', 'calligraphy paper', 'elegant Arabic school motifs', 'lantern'],
    forbiddenObjects: ['french words', 'latin letters', 'calculator', 'cahier d exercices', 'test tubes'],
    illustrationStyle: 'Warm traditional Arabic cultural school art, soft red and pink tones with gentle beige calligraphy scrolls',
    heroObjects: ['polished carved reed calligraphy pen (Qalam) with chiseled nib', 'antique ceramic inkwell with rich cinnabar red ink', 'rolled parchment scroll tied with golden cord'],
    secondaryObjects: ['delicate non-textual arabesque flourish curves', 'warm brass filigree lantern casting gentle light', 'leather-bound traditional book with embossed geometric medallion'],
    backgroundAtmosphere: 'Regal crimson and warm ivory textured canvas adorned with soft watermarked Islamic geometric patterns and warm ambient lighting',
    borderDesign: 'Noble Andalusian geometric interlacing border with traditional 8-point star corner medallions in crimson and gold',
    compositionStructure: 'Symmetric cultural prestige layout; upper zone pristine for Arabic title, bottom 36% presenting a master calligrapher desk scene, center balanced',
    lowerSceneDescription: 'An authentic Arabic calligraphy desk with carved wooden reed pen, fine ceramic inkpot, unrolled handmade parchment, and an ornate brass lantern glowing gently',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#BE123C', badgeBg: '#BE123C', badgeText: '#FFFFFF' },
  },

  // 09. كرّاس الإنتاج الكتابي
  {
    id: 'production_ecrite_ar',
    label: 'كرّاس الإنتاج الكتابي',
    language: 'ar',
    direction: 'rtl',
    palette: ['#DB2777', '#F472B6', '#FDF2F8', '#7C3AED', '#FBCFE8'],
    allowedObjects: ['traditional pen', 'paper sheets', 'books', 'Arabic letters', 'illustrated storytelling', 'feather', 'idea bulb'],
    forbiddenObjects: ['calculator', 'test tubes', 'cahier d exercices', 'french words'],
    illustrationStyle: 'Soft pastel storytelling and creative imagination universe, delicate pink, peach and violet accents',
    heroObjects: ['iridescent white and gold feather quill poised over parchment', 'illuminated creative imagination crystal lamp with violet glow', 'open illustrated storybook with blossoming fantasy branches'],
    secondaryObjects: ['fluttering deckled-edge paper sheets', 'gentle floating jasmine flower blossoms', 'delicate ink swirls and rose-gold sparkle dust'],
    backgroundAtmosphere: 'Dreamy soft rose and lavender gradient backdrop with warm silk watercolor clouds and luminous starlight highlights',
    borderDesign: 'Floral arabesque scroll border with delicate blossom buds at the corners and shimmering rose-gold inner hairline',
    compositionStructure: 'Flowing poetic spiral; spacious title area at top, bottom 36% blossoming with open story pages, crystal inspiration lantern, and floral vines',
    lowerSceneDescription: 'A poetically staged student writing table with an open journal, golden feather quill, fluttering sheets of creative prose, and delicate blooming jasmine petals drifting softly',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#DB2777', badgeBg: '#DB2777', badgeText: '#FFFFFF' },
  },

  // 10. كرّاس القراءة
  {
    id: 'lecture_ar',
    label: 'كرّاس القراءة',
    language: 'ar',
    direction: 'rtl',
    palette: ['#0D9488', '#EAB308', '#2563EB', '#F0FDFA', '#14B8A6'],
    allowedObjects: ['open books', 'library', 'Arabic letters', 'imaginative reading universe', 'flying pages', 'gentle stars'],
    forbiddenObjects: ['calculator', 'math ruler', 'cahier d exercices', 'french text'],
    illustrationStyle: 'Luminous imaginative reading wonderland, turquoise water and sky tones with golden yellow glowing stars',
    heroObjects: ['magnificent open treasury book of tales with glowing turquoise pages', 'friendly scholastic owl reading with round brass spectacles', 'golden antique reading lamp casting a warm cone of light'],
    secondaryObjects: ['stack of colorful bound reader anthologies', 'golden bookmark ribbon with star charm', 'whimsical floating origami paper birds'],
    backgroundAtmosphere: 'Enchanting turquoise and oceanic teal canvas illuminated by soft lantern glows, magical fireflies, and floating stardust',
    borderDesign: 'Arching Eastern library arch border with scalloped scalloping and golden lantern corner vignettes',
    compositionStructure: 'Storybook garden composition; top third reserved for reader title, bottom 38% enriched with the open treasury book, wise reading owl, and glowing lamp',
    lowerSceneDescription: 'A charming storybook reading nook with a grand open book on a carved wooden lectern, a friendly reading owl with spectacles, and stacks of colorful illustrated readers',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#0D9488', badgeBg: '#0D9488', badgeText: '#FFFFFF' },
  },

  // 11. كرّاس قواعد اللغة
  {
    id: 'grammaire_ar',
    label: 'كرّاس قواعد اللغة',
    language: 'ar',
    direction: 'rtl',
    palette: ['#047857', '#10B981', '#F0FDF4', '#FDE68A', '#065F46'],
    allowedObjects: ['Arabic letters', 'words', 'Arabic vowel marks', 'punctuation', 'pen', 'book', 'structured scrolls'],
    forbiddenObjects: ['calculator', 'microscope', 'french words', 'cahier d exercices'],
    illustrationStyle: 'Emerald green scholarly aesthetic, refined structured borders, academic Arabic elegance and beige papyrus',
    heroObjects: ['grand leather-bound lexicon of grammar with emerald green and gold tooling', 'ornate wooden bookstand (Rehal) holding an open manuscript', 'gilded scholar pen and ink well set'],
    secondaryObjects: ['sculptural Arabic diacritic vowel accents (Fatha, Damma, Kasra) rendered as golden gems', 'parchment rule scroll', 'brass balance scale of precision'],
    backgroundAtmosphere: 'Prestigious deep emerald and sage green academic paper background with subtle geometric watermark lattices and warm parchment radiance',
    borderDesign: 'Formal scholarly geometric framing border with interlocking emerald ribbon patterns and gilded corner cartouches',
    compositionStructure: 'Dignified architectural balance; upper quadrant clear for title plate, lower 34% anchored by the traditional bookstand, lexicon, and golden vowel ornaments',
    lowerSceneDescription: 'A prestigious Arabic linguistic study scene featuring an open grammar manuscript on a carved wooden rehal stand, flanked by inkwell, scholar pen, and golden diacritic accents',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#047857', badgeBg: '#047857', badgeText: '#FFFFFF' },
  },

  // 12. كرّاس التاريخ والجغرافيا
  {
    id: 'histoire_geo',
    label: 'كرّاس التاريخ والجغرافيا',
    language: 'ar',
    direction: 'rtl',
    palette: ['#065F46', '#1E40AF', '#D97706', '#FEF3C7', '#059669'],
    allowedObjects: ['globe', 'maps', 'compass', 'historic monuments', 'books', 'geographic exploration', 'hourglass', 'caravel ship motif'],
    forbiddenObjects: ['calculator', 'test tubes', 'cahier d exercices', 'music staff'],
    illustrationStyle: 'Explorer cartography and heritage art, rich earth tones, green, ocean blue and antique parchment gold',
    heroObjects: ['antique spinning desktop terrestrial globe on brass stand', 'nautical brass navigation compass with magnetic needle', 'rolled vintage world map scroll showing continents and sea routes'],
    secondaryObjects: ['caravel exploration sailing ship silhouette on ocean waves', 'flowing antique sand hourglass with golden sand', 'magnifying loupe with wooden handle', 'ancient stone pyramid and citadel silhouettes'],
    backgroundAtmosphere: 'Aged parchment and antique explorer chart canvas with faint longitude/latitude coordinate lines and sepia nautical wind roses',
    borderDesign: 'Vintage nautical cartography border featuring rope twist details, quadrant corner compass roses, and latitude tick marks',
    compositionStructure: 'Grand exploration staging; clean title banner at the top, bottom 40% richly populated with the spinning globe, brass compass, rolled maps, and historical relics',
    lowerSceneDescription: 'An explorer expedition desk loaded with a brass-mounted desktop globe, an unrolled antique world map, a polished navigation compass, a sand hourglass, and historical monuments in the backdrop',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#065F46', badgeBg: '#065F46', badgeText: '#FFFFFF' },
  },

  // 13. كرّاس التربية الإسلامية
  {
    id: 'education_islamique',
    label: 'كرّاس التربية الإسلامية',
    language: 'ar',
    direction: 'rtl',
    palette: ['#D97706', '#F59E0B', '#065F46', '#FFFBEB', '#FDE68A'],
    allowedObjects: ['mosque silhouette', 'crescent moon', 'stars', 'Islamic geometric ornaments', 'prayer beads', 'open Quran stand motif', 'lantern'],
    forbiddenObjects: ['calculator', 'animals', 'human faces', 'cahier d exercices', 'science test tubes'],
    illustrationStyle: 'Sublime Islamic geometric arabesques, dignified golden crescent, soft cream and spiritual olive green',
    heroObjects: ['magnificent mosque minaret and dome silhouette in soft golden light', 'gleaming slender golden crescent moon with radiant evening star', 'carved wooden Quran stand (Rehal) motif holding an open golden-edged volume'],
    secondaryObjects: ['glowing brass Fanous lantern with intricate pierced patterns', 'wooden Misbaha prayer beads with silk tassel', 'harmonious 12-pointed Islamic geometric star rosettes'],
    backgroundAtmosphere: 'Spiritual warm amber, gold, and serene olive cream canvas bathed in heavenly celestial dawn luminescence with delicate geometric tracery',
    borderDesign: 'Sacred architectural arch border inspired by mihrab arches, decorated with intricate golden arabesques and refined corner palmettes',
    compositionStructure: 'Serene spiritual symmetry; upper zone reserved for Quranic/Islamic study title, bottom 38% adorned with dignified mosque silhouette, glowing fanous lantern, and prayer beads',
    lowerSceneDescription: 'A peaceful spiritual setting featuring the silhouette of illuminated mosque domes, a glowing brass lantern casting intricate light patterns, polished prayer beads, and a crescent moon in a starry twilight',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#D97706', badgeBg: '#D97706', badgeText: '#FFFFFF' },
  },

  // 14. كرّاس التربية المدنية (PRIMARY ACCEPTANCE TEST SUBJECT)
  {
    id: 'education_civique',
    label: 'كرّاس التربية المدنية',
    language: 'ar',
    direction: 'rtl',
    palette: ['#0284C7', '#16A34A', '#EAB308', '#F0F9FF', '#38BDF8'],
    allowedObjects: [
      'school building',
      'children in community',
      'community handshake',
      'city architecture',
      'citizenship symbols',
      'cooperation and civic responsibility',
      'olive branch of peace',
      'friendly civic square',
      'school flag motif',
      'united hands',
    ],
    forbiddenObjects: [
      'mathematics',
      'numbers + -',
      'calculator',
      'french homework',
      'cahier d exercices',
      'devoirs',
      'science test tubes',
      'microscope',
      'music staff',
      'english speech bubbles',
    ],
    illustrationStyle: 'Vibrant civic harmony and citizenship, sky blue, lush civic green and joyful sunny yellow, schoolhouse and community emblems',
    heroObjects: ['classic friendly schoolhouse building with clock tower and flying national flag', 'emblematic handshake of solidarity and community cooperation', 'lush silver-green olive branch of peace with golden leaves'],
    secondaryObjects: ['modern city skyline and community park trees', 'round civic citizenship seal medallion', 'cheerful school bell ringing', 'diverse silhouettes of children holding hands in unity'],
    backgroundAtmosphere: 'Clear radiant sky blue and clean park green background symbolizing civic pride, community peace, and bright democratic future',
    borderDesign: 'Civic garland border intertwined with olive leaves, golden civic ribbons, and clean modern corner safety shields',
    compositionStructure: 'Community harmony panorama; top reserved for civic education title, bottom 40% depicting a charming schoolhouse in a community park with friendly civic emblems',
    lowerSceneDescription: 'A vibrant community scene showcasing a welcoming schoolhouse with bell tower, surrounded by lush green trees, a cooperative handshake crest, olive branches of peace, and clean civic architecture under sunny skies',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#0284C7', badgeBg: '#0284C7', badgeText: '#FFFFFF' },
  },

  // 15. كرّاس التربية التشكيليّة
  {
    id: 'arts_plastiques',
    label: 'كرّاس التربية التشكيليّة',
    language: 'ar',
    direction: 'rtl',
    palette: ['#E11D48', '#8B5CF6', '#F59E0B', '#06B6D4', '#FFF1F2'],
    allowedObjects: ['paint palette', 'brushes', 'colored pencils', 'watercolor splatters', 'easel', 'creative abstract shapes', 'color wheel'],
    forbiddenObjects: ['calculator', 'test tubes', 'cahier d exercices', 'french words'],
    illustrationStyle: 'Explosion of artist creativity, paintbrushes, tubes of acrylic color, vivid multicolor harmony and joyful paint splashes',
    heroObjects: ['classic wooden painter palette with dollops of vibrant wet paint', 'bundle of fine artist bristle brushes dripping bright pigment', 'wooden tabletop studio easel holding a blank white canvas'],
    secondaryObjects: ['squeezed tubes of vermilion, cobalt, and cadmium yellow acrylic paint', 'dynamic expressive watercolor paint splashes and drips', 'chromatic color wheel medallion', 'colorful wooden coloring pencils'],
    backgroundAtmosphere: 'Bright textured watercolor paper background with luminous organic artistic paint washes and gentle splatter depth',
    borderDesign: 'Playful artist frame made of overlapping watercolor brush strokes and vibrant paint dab corner rosettes',
    compositionStructure: 'Dynamic studio burst; top zone clean for art subject title, bottom 38% overflowing with painter palette, dripping brushes, and joyful color splashes',
    lowerSceneDescription: 'An inspiring artist studio workbench with a traditional wooden palette covered in rich colorful oil paints, brushes in a jar, tubes of paint, and energetic watercolor splashes',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#E11D48', badgeBg: '#E11D48', badgeText: '#FFFFFF' },
  },

  // 16. كرّاس الموسيقى
  {
    id: 'musique',
    label: 'كرّاس الموسيقى',
    language: 'ar',
    direction: 'rtl',
    palette: ['#7C3AED', '#EC4899', '#2563EB', '#FAF5FF', '#A855F7'],
    allowedObjects: ['musical notes', 'piano keys', 'acoustic guitar', 'headphones', 'music staff', 'treble clef', 'tambourine', 'sound waves'],
    forbiddenObjects: ['calculator', 'microscope', 'cahier d exercices', 'history maps'],
    illustrationStyle: 'Musical rhythm in motion, floating treble clefs and melodies, harmonic violet, magenta and melodic blue',
    heroObjects: ['sculptural golden treble clef (G-clef) floating gracefully', 'curved flowing piano keyboard ribbon with black and white keys', 'warm wooden acoustic guitar body with polished soundboard'],
    secondaryObjects: ['floating eighth notes and sixteenth note clusters', 'flowing 5-line musical stave ribbon', 'modern studio audio headphones', 'harmonic vibrating resonance wave rings'],
    backgroundAtmosphere: 'Luminous deep violet and vibrant magenta twilight canvas with pulsing rhythmic soundwave ripples and starlight melodies',
    borderDesign: 'Rhythmic musical stave border with notes dancing along the edges and treble clef corner anchors',
    compositionStructure: 'Harmonic flow layout; upper area airy for music notebook title, lower 36% carrying a dynamic wave of piano keys, guitar silhouette, and floating golden notes',
    lowerSceneDescription: 'A melodic symphony scene with an undulating wave of glossy piano keys, a polished acoustic guitar, studio headphones, and glowing musical notes swirling upward',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#7C3AED', badgeBg: '#7C3AED', badgeText: '#FFFFFF' },
  },

  // 17. كرّاس الإيقاظ الموسيقي
  {
    id: 'eveil_musical',
    label: 'كرّاس الإيقاظ الموسيقي',
    language: 'ar',
    direction: 'rtl',
    palette: ['#EAB308', '#06B6D4', '#F43F5E', '#FEFCE8', '#F59E0B'],
    allowedObjects: ['playful notes', 'small xylophone', 'rattle drum', 'friendly musical characters', 'maracas', 'triangle instrument', 'smiles'],
    forbiddenObjects: ['complex formulas', 'cahier d exercices', 'science lab'],
    illustrationStyle: 'Childhood musical initiation, colorful playful percussion, bright sunny yellow, fresh turquoise and coral',
    heroObjects: ['bright rainbow-keyed children xylophone with red wooden mallets', 'colorful painted wooden maracas with festive patterns', 'cheerful brass percussion triangle with striker'],
    secondaryObjects: ['whimsical bouncing musical notes with friendly smiles', 'small tambourine with jingles', 'curving colorful sound ribbon trails', 'playful confetti stars'],
    backgroundAtmosphere: 'Sunny, joyful canary yellow and fresh turquoise canvas with dancing pastel polka dots and bubbly musical joy',
    borderDesign: 'Playful scalloped border with cheerful xylophone key bars and colorful percussion shaker corner stamps',
    compositionStructure: 'Joyful playground composition; top reserved for music discovery title, bottom 38% filled with friendly rhythm instruments and dancing notes',
    lowerSceneDescription: 'A delightful early-childhood music playroom with a bright rainbow xylophone, wooden maracas, a shiny triangle, and happy smiling notes dancing playfully',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#D97706', badgeBg: '#D97706', badgeText: '#FFFFFF' },
  },

  // 18. كرّاس التكنولوجيا
  {
    id: 'technologie',
    label: 'كرّاس التكنولوجيا',
    language: 'ar',
    direction: 'rtl',
    palette: ['#0284C7', '#EA580C', '#0F172A', '#F0F9FF', '#38BDF8'],
    allowedObjects: ['interlocking gears', 'friendly robot', 'electronic circuits', 'hand tools', 'invention light bulb', 'blueprint grid', 'solar panel motif'],
    forbiddenObjects: ['paint palette', 'cahier d exercices', 'music notes'],
    illustrationStyle: 'Engineering and invention aesthetic, electric blue and vibrant orange gears, crisp technical blueprint motifs',
    heroObjects: ['set of interlocking 3D mechanical gears in burnished bronze and electric blue', 'friendly scholastic robot companion with illuminated visor', 'glowing invention filament bulb with geometric internal circuits'],
    secondaryObjects: ['precision digital caliper and screwdriver', 'microchip processor board with copper trace paths', 'technical isometric blueprint grid', 'miniature solar cell panel motif'],
    backgroundAtmosphere: 'High-precision technical drafting blueprint canvas in cobalt and deep slate with fine metric grid lines and circuit pathways',
    borderDesign: 'Industrial engineering border with subtle cog tooth patterns, hex-nut accents, and technical chamfered corners',
    compositionStructure: 'Maker engineering workbench; clear header zone for technology title, lower 38% showcasing interlocking mechanical gears, circuit components, and the friendly robot',
    lowerSceneDescription: 'An inventive student robotics lab workspace with precision interlocking gears, an open microchip breadboard, workshop hand tools, a glowing invention bulb, and a miniature robot assistant',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#0284C7', badgeBg: '#0284C7', badgeText: '#FFFFFF' },
  },

  // 19. كرّاس الإعلامية
  {
    id: 'informatique',
    label: 'كرّاس الإعلامية',
    language: 'ar',
    direction: 'rtl',
    palette: ['#0F172A', '#06B6D4', '#8B5CF6', '#F8FAFC', '#38BDF8'],
    allowedObjects: ['computer screen', 'code symbols < / >', 'keyboard', 'computer mouse', 'electronic microchips', 'digital cloud', 'matrix nodes'],
    forbiddenObjects: ['fountain pen', 'cahier d exercices', 'paint palette'],
    illustrationStyle: 'Futuristic computer science art, midnight dark blue, luminous cyan circuits and violet code symbols',
    heroObjects: ['sleek modern computer monitor with illuminated holographic display', 'glowing 3D code brackets < / > in neon cyan and electric violet', 'ergonomic optical computer mouse with glowing scroll wheel'],
    secondaryObjects: ['floating digital cloud network with connected server nodes', 'printed circuit board matrix with cyan bus lines', 'stylized binary pulse ribbons', 'silicon microchip processor'],
    backgroundAtmosphere: 'Deep midnight navy cyberpunk canvas with glowing cyan cyber-grid perspective, floating data nodes, and neon violet ambient lighting',
    borderDesign: 'High-tech fiber-optic border with glowing circuit trace lines and digital corner bracket chips',
    compositionStructure: 'Cybernetic workstation layout; top kept crisp and clean for computer science title, bottom 38% centered on the futuristic workstation, floating code brackets, and network nodes',
    lowerSceneDescription: 'A cutting-edge student computer science hub with a glowing slim workstation monitor, illuminated neon code symbols, glowing circuit board tracks, and interconnected digital nodes',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#0284C7', badgeBg: '#0F172A', badgeText: '#38BDF8' },
  },

  // 20. كرّاس المحفوظات
  {
    id: 'memorisation',
    label: 'كرّاس المحفوظات',
    language: 'ar',
    direction: 'rtl',
    palette: ['#9333EA', '#F472B6', '#FAF5FF', '#FDE68A', '#A855F7'],
    allowedObjects: ['poetry book', 'fountain pen', 'gentle night stars', 'lyrical letters', 'poetic decorative universe', 'blooming flower', 'dove motif'],
    forbiddenObjects: ['calculator', 'test tubes', 'cahier d exercices', 'sports gear'],
    illustrationStyle: 'Poetic recital aesthetic, gentle mauve, powdery rose petals, twinkling stars and elegant Arabic verses',
    heroObjects: ['ornate velvet-bound poetry anthology with gilded corners', 'slender iridescent pearl fountain pen', 'peaceful white dove in graceful flight with olive twig'],
    secondaryObjects: ['cluster of twinkling evening stars and crescent moon', 'delicate blooming damask rose with velvet petals', 'flowing silk recital banner ribbons', 'gentle musical resonance ripples'],
    backgroundAtmosphere: 'Dreamy twilight mauve and powdery lavender sky canvas dotted with gentle glowing stars, soft moonlight, and rose petal wisps',
    borderDesign: 'Poetic filigree border intertwined with delicate rose vines, twinkling starlight studs, and graceful corner loops',
    compositionStructure: 'Lyrical recital composition; upper area reserved clean for poem memorization title, bottom 36% showcasing the open poetry book, soaring dove, and blooming rose',
    lowerSceneDescription: 'A peaceful poetic garden setting featuring an open gilded anthology of verse, a graceful white dove soaring past, blooming fragrant roses, and gentle starlight illuminating the pages',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#9333EA', badgeBg: '#9333EA', badgeText: '#FFFFFF' },
  },

  // 21. كرّاس التمارين
  {
    id: 'exercices',
    label: 'كرّاس التمارين',
    language: 'ar',
    direction: 'rtl',
    palette: ['#EA580C', '#2563EB', '#16A34A', '#FFF7ED', '#FB923C'],
    allowedObjects: ['checklists', 'pencils', 'ruler', 'numbers', 'open practice books', 'achievement badges', 'green checkmarks', 'trophy icon'],
    forbiddenObjects: ['cahier d exercices in french text', 'unrelated symbols'],
    illustrationStyle: 'Engaging study practice motifs, vibrant orange, energetic blue and success green checkmarks',
    heroObjects: ['open practice exercise workbook with neat blue rulings', 'sharpened student pencils with clean pink erasers', 'golden achievement trophy star badge with success ribbon'],
    secondaryObjects: ['bold vibrant green checkmarks of successful completion', 'colorful sticky note checklist tabs', 'wooden study ruler and sharpener', 'energetic starburst motivation badges'],
    backgroundAtmosphere: 'Crisp energetic warm cream and citrus orange canvas with subtle geometric school graph paper texture and uplifting morning lighting',
    borderDesign: 'Dynamic scholastic checklist border with alternating orange and blue pinstripes and star corner badges',
    compositionStructure: 'Uplifting study motivation layout; title area clearly marked at top, lower 36% packed with open workbooks, sharp pencils, and cheerful success trophies',
    lowerSceneDescription: 'An inspiring and productive student homework desk with open lined practice books, sharpened pencils, colorful achievement badges, and glowing green checkmarks symbolizing mastery',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#EA580C', badgeBg: '#EA580C', badgeText: '#FFFFFF' },
  },

  // 22. كرّاس المطالعة
  {
    id: 'mutalaa',
    label: 'كرّاس المطالعة',
    language: 'ar',
    direction: 'rtl',
    palette: ['#166534', '#0D9488', '#F0FDF4', '#FDE68A', '#22C55E'],
    allowedObjects: ['stack of books', 'reading tree of knowledge', 'library corner', 'imaginary world emerging from open book', 'reading lamp', 'friendly owl'],
    forbiddenObjects: ['calculator', 'cahier d exercices', 'french words'],
    illustrationStyle: 'Lush forest green tree of wisdom, open pages spreading branches, tranquil emerald and turquoise tones',
    heroObjects: ['magnificent grand tree of knowledge whose branches are formed of open book pages', 'cozy library reading armchair with a stack of classic tomes', 'friendly wise owl sitting among leafy book branches'],
    secondaryObjects: ['vintage brass reading floor lamp casting warm amber glow', 'wooden library ladder resting against tall shelves', 'fluttering leaf-shaped bookmarks', 'gentle woodland butterflies'],
    backgroundAtmosphere: 'Tranquil emerald forest and warm library sanctuary canvas with dappled sunbeams filtering through leafy book canopies',
    borderDesign: 'Botanical book-leaf border with interwoven ivy tendrils and oak leaf corner medallions in forest green and gold',
    compositionStructure: 'Enchanted library garden; top kept pristine for reading notebook title, bottom 40% dominated by the majestic tree of knowledge, open books, and cozy reading atmosphere',
    lowerSceneDescription: 'A sanctuary of reading where an ancient leafy tree of wisdom grows from open books, surrounded by cozy library shelves, an amber reading lamp, and a peaceful reading owl',
    titleStyle: { fontFamily: 'Cairo, sans-serif', fontWeight: '800', defaultColor: '#166534', badgeBg: '#166534', badgeText: '#FFFFFF' },
  },

  // 23. Cahier de devoirs
  {
    id: 'devoirs',
    label: 'Cahier de devoirs',
    language: 'fr',
    direction: 'ltr',
    palette: ['#1D4ED8', '#EAB308', '#EFF6FF', '#FEF08A', '#2563EB'],
    allowedObjects: ['study checklists', 'analog clock', 'books', 'pencils', 'calendar days', 'hour hand', 'assignment badge', 'pencil case'],
    forbiddenObjects: ['cahier d exercices text', 'arabic calligraphy', 'random text'],
    illustrationStyle: 'Royal blue and sunshine yellow school agenda style, neat clocks, organized assignment checklists',
    heroObjects: ['classic round student alarm clock with brass bells showing 4 o\'clock', 'neat zippered pencil case filled with colorful pens and highlighters', 'spiral-bound school agenda and daily study planner'],
    secondaryObjects: ['colorful assignment checklist bookmarks', 'wooden ruler and erasers', 'golden star stickers of excellence', 'neat calendar day grid icons'],
    backgroundAtmosphere: 'Crisp, organized royal cobalt blue and bright sunshine yellow canvas with subtle clean agenda grid lines',
    borderDesign: 'Punctual school planner border with tick mark corner tabs and vibrant yellow-blue dual pinstripes',
    compositionStructure: 'Organized student station; top banner clean for homework title, lower 35% displaying an orderly homework prep desk with clock, pencil case, and planner',
    lowerSceneDescription: 'An orderly after-school study desk with an analog clock, a filled colorful pencil case, open agenda planner, and neat textbooks ready for focused study',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#1D4ED8', badgeBg: '#1D4ED8', badgeText: '#FFFFFF' },
  },

  // 24. Cahier de brouillon
  {
    id: 'brouillon',
    label: 'Cahier de brouillon',
    language: 'fr',
    direction: 'ltr',
    palette: ['#475569', '#F59E0B', '#EA580C', '#F8FAFC', '#94A3B8'],
    allowedObjects: ['pencil sketch', 'eraser with crumbs', 'grid notebook paper', 'curved doodles', 'handwritten-note motifs', 'paper plane', 'pencil shavings'],
    forbiddenObjects: ['cahier d exercices text', 'formal crests'],
    illustrationStyle: 'Artistic draft studio style, blueprint slate grey, warm pencil graphite and energetic terracotta accents',
    heroObjects: ['sharpened graphite wooden pencils with spiral wood shavings', 'sculpted white eraser with playful eraser crumbs', 'origami folded paper airplane ready for takeoff'],
    secondaryObjects: ['subtle graph grid paper texture', 'playful spiral binder rings along the edge', 'dynamic doodle curves and geometric sketch ideas', 'terracotta pencil sharpener'],
    backgroundAtmosphere: 'Authentic slate grey and ivory graph paper canvas with tactile paper grain and warm terracotta studio lighting',
    borderDesign: 'Creative sketchbook border with hand-drawn marker effect, washi tape corner strips, and perforated page edges',
    compositionStructure: 'Creative draft table; top reserved for draft notebook title, bottom 35% showcasing the dynamic creativity of pencils, paper plane, and sketch ideas',
    lowerSceneDescription: 'A playful creative draft workbench with curling pencil shavings, a sharp graphite pencil, a sleek paper airplane, and whimsical geometric doodle sketches on graph paper',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#475569', badgeBg: '#475569', badgeText: '#FFFFFF' },
  },

  // 25. Cahier de correspondance
  {
    id: 'correspondance',
    label: 'Cahier de correspondance',
    language: 'fr',
    direction: 'ltr',
    palette: ['#0D9488', '#F43F5E', '#F0FDFA', '#FFF1F2', '#14B8A6'],
    allowedObjects: ['envelope with school stamp', 'school building', 'communication message notes', 'calendar date', 'wooden pencil', 'friendly mailbox', 'paper clip'],
    forbiddenObjects: ['cahier d exercices text', 'math formulas'],
    illustrationStyle: 'Friendly school-home communication aesthetic, fresh turquoise envelopes, warm coral accents and postal stamp motifs',
    heroObjects: ['crisp postal letter envelope with decorative school postmark and wax seal', 'friendly red community mailbox with open letter slot', 'cheerful school bell tower silhouette in the background'],
    secondaryObjects: ['golden paperclip holding neat notification notes', 'miniature calendar day badge with checkmark', 'friendly communication speech note', 'warm coral heart postage stamp'],
    backgroundAtmosphere: 'Welcoming soft seafoam turquoise and warm coral canvas with subtle postal chevron motifs and airy daylight',
    borderDesign: 'Charming postal correspondence border with airmail corner chevrons in turquoise, white, and coral',
    compositionStructure: 'Warm connection layout; clear title frame at top, lower 36% featuring the friendly mailbox, stamped envelopes, and schoolhouse in the background',
    lowerSceneDescription: 'A heartwarming liaison scene between school and home with postal envelopes, a cheerful school mailbox, golden paperclips, and the friendly schoolhouse under a bright sky',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#0D9488', badgeBg: '#0D9488', badgeText: '#FFFFFF' },
  },

  // 26. Autre – Spécifier
  {
    id: 'autre',
    label: 'Autre – Spécifier',
    language: 'mixed',
    direction: 'ltr',
    palette: ['#4338CA', '#0D9488', '#F59E0B', '#FAF5FF', '#6366F1'],
    allowedObjects: ['universal school notebook', 'educational stationery', 'pencils and rulers', 'open book', 'delicate geometric ornaments', 'learning stars'],
    forbiddenObjects: ['cahier d exercices text', 'misleading subject labels'],
    illustrationStyle: 'Universal premium school stationery aesthetic, versatile harmonious multicolor palette and elegant school crests',
    heroObjects: ['prestigious universal scholastic crest with open encyclopedia and torch of knowledge', 'fine drafting instruments (pencil, ruler, compass) arranged symmetrically', 'golden laurels of academic achievement'],
    secondaryObjects: ['shining eight-pointed star of wisdom', 'delicate geometric guilloche rosettes', 'subtle universal graduation cap tassel motif', 'harmonious multicolor ribbons'],
    backgroundAtmosphere: 'Dignified indigo and warm amber stationery canvas with refined radial guilloche engraving and clean academic depth',
    borderDesign: 'Prestigious academic pinstripe frame with double gold fillets and classical laurel corner rosettes',
    compositionStructure: 'Universal prestige heraldry; top zone reserved for custom title, bottom 36% displaying the grand encyclopedia, scholastic crest, and golden laurels',
    lowerSceneDescription: 'A prestigious universal academic still-life featuring an open leather encyclopedia, glowing torch of wisdom, golden laurels, and fine student drafting tools arranged harmoniously',
    titleStyle: { fontFamily: 'Outfit, sans-serif', fontWeight: '800', defaultColor: '#4338CA', badgeBg: '#4338CA', badgeText: '#FFFFFF' },
  },
];

/**
 * FULL SUBJECT REGISTRY
 * Maps each subject ID to its complete configuration and 12 dedicated templates.
 */
export const SUBJECT_REGISTRY: Record<string, SubjectDefinition> = {};

// Initialize all 26 subjects with their 12 templates
RAW_SUBJECTS.forEach((subj) => {
  const templates = buildSubjectTemplates(
    subj.id,
    subj.label,
    subj.direction,
    subj.palette,
    subj.allowedObjects,
    subj.forbiddenObjects
  );

  SUBJECT_REGISTRY[subj.id] = {
    ...subj,
    templates,
  };
});

/**
 * Mapping table for backward compatibility with older aliases or display labels
 */
const SUBJECT_ALIASES: Record<string, string> = {
  mathematiques: 'maths',
  math: 'maths',
  sciences: 'eveil_scientifique',
  science: 'eveil_scientifique',
  islamique: 'education_islamique',
  islamic: 'education_islamique',
  civisme_devoirs: 'education_civique',
  cahier_texte: 'correspondance',
  dessin_arts: 'arts_plastiques',
  multi_matieres: 'autre',
  french: 'francais',
  arabic: 'arabe',
  english: 'anglais',
  history: 'histoire_geo',
  geography: 'histoire_geo',
  exercise: 'exercices',
  homework: 'devoirs',
  textbook: 'correspondance',
  other: 'autre',
};

/**
 * Resolves a subject ID or label to the exact registered subject ID
 */
export function resolveSubjectId(rawInput: string): string {
  if (!rawInput) return 'autre';
  const normalized = rawInput.trim().toLowerCase();

  // Exact ID match
  if (SUBJECT_REGISTRY[normalized]) return normalized;

  // Alias match
  if (SUBJECT_ALIASES[normalized]) return SUBJECT_ALIASES[normalized];

  // Match by exact label
  const foundByLabel = RAW_SUBJECTS.find((s) => s.label === rawInput.trim());
  if (foundByLabel) return foundByLabel.id;

  // Partial match fallback
  const foundPartial = RAW_SUBJECTS.find((s) =>
    rawInput.includes(s.label) || s.label.includes(rawInput)
  );
  if (foundPartial) return foundPartial.id;

  return 'autre';
}

/**
 * Retrieves the SubjectDefinition with strict verification
 */
export function getSubjectDefinition(subjectId: string): SubjectDefinition {
  const resolvedId = resolveSubjectId(subjectId);
  const subject = SUBJECT_REGISTRY[resolvedId];
  if (!subject) {
    return SUBJECT_REGISTRY.autre;
  }
  return subject;
}

/**
 * Anti-repetition state memory per subject
 */
export const lastTemplateBySubject: Record<string, number> = {};

/**
 * Selects an artistic model for a subject, respecting the active 5-model pool (or user requested model)
 * strictly avoiding repeating the immediately previous model to guarantee variety.
 */
export function selectNextTemplateForSubject(
  subjectId: string,
  preferredTemplateId?: number
): CoverTemplate {
  const subject = getSubjectDefinition(subjectId);
  const activePool = subject.templates.slice(0, ACTIVE_MODEL_COUNT);

  // If specific template requested and valid
  if (preferredTemplateId && preferredTemplateId >= 1 && preferredTemplateId <= subject.templates.length) {
    const directMatch = subject.templates.find((t) => t.id === preferredTemplateId);
    if (directMatch) {
      lastTemplateBySubject[subject.id] = directMatch.id;
      return directMatch;
    }
  }

  const lastId = lastTemplateBySubject[subject.id];
  const candidates = activePool.filter((t) => t.id !== lastId);

  // Fallback to active pool if candidates is empty
  const pool = candidates.length > 0 ? candidates : activePool;
  const chosen = pool[Math.floor(Math.random() * pool.length)] || activePool[0];

  lastTemplateBySubject[subject.id] = chosen.id;
  return chosen;
}

/**
 * Builds the AI generation prompt with STRICT SEPARATION:
 * Artwork only, zero text, reserved zones.
 * Incorporates the 26 unique professional stationery identities.
 */
export function buildAiBackgroundPrompt(
  subject: SubjectDefinition,
  template: CoverTemplate,
  formatPage: NotebookPageFormat
): string {
  // Strict Subject Validation
  if (template.subjectId !== subject.id) {
    throw new Error(
      `Subject lock violation: Template ${template.id} belongs to ${template.subjectId}, not ${subject.id}`
    );
  }

  const isLandscape = formatPage === 'A4_double_horizontal' || formatPage === 'custom_double_horizontal';

  // Extract visual identity fields (with fallbacks if undefined)
  const heroObjectsStr = (subject.heroObjects && subject.heroObjects.length > 0)
    ? subject.heroObjects.join(', ')
    : subject.allowedObjects.slice(0, 3).join(', ');
  const secondaryObjectsStr = (subject.secondaryObjects && subject.secondaryObjects.length > 0)
    ? subject.secondaryObjects.join(', ')
    : subject.allowedObjects.slice(3).join(', ');
  const atmosphereStr = subject.backgroundAtmosphere || 'Clean premium school stationery paper with subtle warm studio lighting and refined gradients';
  const borderDesignStr = subject.borderDesign || 'Elegant school stationery border with refined corner brackets and matching accent pinstripes';
  const lowerSceneStr = subject.lowerSceneDescription || `A rich, beautifully composed stationery scene with ${heroObjectsStr}`;
  const compositionStr = subject.compositionStructure || 'Top area clear for programmatic title, bottom 35-40% enriched with a dedicated illustrated scene, center balanced and uncluttered';

  return `You are a Senior Creative Director specializing in luxury children's school stationery for the brand "CreaRocket".
Generate STRICTLY the decorative, high-resolution background artwork for a premium school notebook cover.

============================================================
ABSOLUTE PRODUCTION RULE — ZERO TEXT IN THE IMAGE
============================================================
THE IMAGE MUST BE 100% PURE VISUAL ARTWORK.
- DO NOT DRAW ANY WORDS, LETTERS, NUMBERS, OR READABLE TEXT.
- DO NOT WRITE ANY TITLE (Strictly forbidden: "Cahier d'Exercices", "Mathématiques", "Devoirs", subject names, etc.).
- DO NOT DRAW ANY STUDENT NAMES, GRADE LABELS, SCHOOL NAMES, OR ACADEMIC YEARS.
- DO NOT DRAW DOTTED FORM LINES, BARCODES, OR UI LABELS.
- All typography and labels will be rendered programmatically in vector overlays by the web application.

============================================================
STATIONERY IDENTITY: ${subject.label.toUpperCase()} (${subject.id})
============================================================
Subject: ${subject.label}
Cohesive Brand Palette: ${template.palette.join(', ')}
Visual Style: ${subject.illustrationStyle}

1. HERO OBJECTS (Prominent, tangible, beautifully rendered):
   ${heroObjectsStr}

2. SECONDARY DECORATIVE OBJECTS:
   ${secondaryObjectsStr}

3. BACKGROUND ATMOSPHERE & TEXTURE:
   ${atmosphereStr}

4. BORDER & FRAMING:
   ${borderDesignStr}

5. LOWER SCENE COMPOSITION (BOTTOM 35%–40%):
   ${lowerSceneStr}

6. COMPOSITION ARCHITECTURE:
   ${compositionStr}
   Format: ${isLandscape ? 'A4 Landscape spread with twin notebook covers side-by-side' : 'A4 Portrait single notebook cover'}.
   Keep the upper quadrant (title placement zone) light, clean, and uncluttered so that the white/colored title badge remains 100% legible.
   Do NOT leave a huge empty void in the center, and do NOT float 2-3 isolated icons. Instead, create an interconnected, delightful, high-end stationery illustration.

============================================================
STRICT FORBIDDEN LIST (DO NOT INCLUDE):
============================================================
${subject.forbiddenObjects.join(', ')}, blurry low-res textures, muddy dark tones, ugly generic cliparts, watermark text.

Include a tiny, elegant stylized origami rocket icon as an Easter egg tribute to the CreaRocket stationery brand. Commercial stationery catalog quality.`;
}

/**
 * Pre-render Layout Validation
 * Enforces all 6 checks before presenting the cover to the user
 */
export interface LayoutValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export function validateCoverLayout(
  subjectId: string,
  template: CoverTemplate,
  titleText: string,
  studentInfo: {
    fullName?: string;
    grade?: string;
    schoolName?: string;
    academicYear?: string;
  }
): LayoutValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // 1. Subject Consistency
  if (!subjectId) {
    errors.push('Missing subject ID');
  } else if (template.subjectId !== subjectId) {
    errors.push(`Template mismatch: template belongs to ${template.subjectId}, requested ${subjectId}`);
  }

  // 2. Title validation
  if (!titleText || !titleText.trim()) {
    errors.push('Title (att_3) cannot be empty');
  }

  // 3. Information Panel validation
  if (!template.infoZone || template.infoZone.height <= 0) {
    errors.push('Invalid infoZone geometry');
  }

  // 4. Safe Zone check
  if (template.titleZone.y < 4 || template.titleZone.y + template.titleZone.height > 96) {
    warnings.push('Title zone extends into edge bleed margin');
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

